
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point en en -type PI PI
add mapped point numerator[31] numerator[31] -type PI PI
add mapped point numerator[30] numerator[30] -type PI PI
add mapped point numerator[29] numerator[29] -type PI PI
add mapped point numerator[28] numerator[28] -type PI PI
add mapped point numerator[27] numerator[27] -type PI PI
add mapped point numerator[26] numerator[26] -type PI PI
add mapped point numerator[25] numerator[25] -type PI PI
add mapped point numerator[24] numerator[24] -type PI PI
add mapped point numerator[23] numerator[23] -type PI PI
add mapped point numerator[22] numerator[22] -type PI PI
add mapped point numerator[21] numerator[21] -type PI PI
add mapped point numerator[20] numerator[20] -type PI PI
add mapped point numerator[19] numerator[19] -type PI PI
add mapped point numerator[18] numerator[18] -type PI PI
add mapped point numerator[17] numerator[17] -type PI PI
add mapped point numerator[16] numerator[16] -type PI PI
add mapped point numerator[15] numerator[15] -type PI PI
add mapped point numerator[14] numerator[14] -type PI PI
add mapped point numerator[13] numerator[13] -type PI PI
add mapped point numerator[12] numerator[12] -type PI PI
add mapped point numerator[11] numerator[11] -type PI PI
add mapped point numerator[10] numerator[10] -type PI PI
add mapped point numerator[9] numerator[9] -type PI PI
add mapped point numerator[8] numerator[8] -type PI PI
add mapped point numerator[7] numerator[7] -type PI PI
add mapped point numerator[6] numerator[6] -type PI PI
add mapped point numerator[5] numerator[5] -type PI PI
add mapped point numerator[4] numerator[4] -type PI PI
add mapped point numerator[3] numerator[3] -type PI PI
add mapped point numerator[2] numerator[2] -type PI PI
add mapped point numerator[1] numerator[1] -type PI PI
add mapped point numerator[0] numerator[0] -type PI PI
add mapped point denominator[31] denominator[31] -type PI PI
add mapped point denominator[30] denominator[30] -type PI PI
add mapped point denominator[29] denominator[29] -type PI PI
add mapped point denominator[28] denominator[28] -type PI PI
add mapped point denominator[27] denominator[27] -type PI PI
add mapped point denominator[26] denominator[26] -type PI PI
add mapped point denominator[25] denominator[25] -type PI PI
add mapped point denominator[24] denominator[24] -type PI PI
add mapped point denominator[23] denominator[23] -type PI PI
add mapped point denominator[22] denominator[22] -type PI PI
add mapped point denominator[21] denominator[21] -type PI PI
add mapped point denominator[20] denominator[20] -type PI PI
add mapped point denominator[19] denominator[19] -type PI PI
add mapped point denominator[18] denominator[18] -type PI PI
add mapped point denominator[17] denominator[17] -type PI PI
add mapped point denominator[16] denominator[16] -type PI PI
add mapped point denominator[15] denominator[15] -type PI PI
add mapped point denominator[14] denominator[14] -type PI PI
add mapped point denominator[13] denominator[13] -type PI PI
add mapped point denominator[12] denominator[12] -type PI PI
add mapped point denominator[11] denominator[11] -type PI PI
add mapped point denominator[10] denominator[10] -type PI PI
add mapped point denominator[9] denominator[9] -type PI PI
add mapped point denominator[8] denominator[8] -type PI PI
add mapped point denominator[7] denominator[7] -type PI PI
add mapped point denominator[6] denominator[6] -type PI PI
add mapped point denominator[5] denominator[5] -type PI PI
add mapped point denominator[4] denominator[4] -type PI PI
add mapped point denominator[3] denominator[3] -type PI PI
add mapped point denominator[2] denominator[2] -type PI PI
add mapped point denominator[1] denominator[1] -type PI PI
add mapped point denominator[0] denominator[0] -type PI PI
add mapped point in_valid in_valid -type PI PI

//output ports
add mapped point quotient[31] quotient[31] -type PO PO
add mapped point quotient[30] quotient[30] -type PO PO
add mapped point quotient[29] quotient[29] -type PO PO
add mapped point quotient[28] quotient[28] -type PO PO
add mapped point quotient[27] quotient[27] -type PO PO
add mapped point quotient[26] quotient[26] -type PO PO
add mapped point quotient[25] quotient[25] -type PO PO
add mapped point quotient[24] quotient[24] -type PO PO
add mapped point quotient[23] quotient[23] -type PO PO
add mapped point quotient[22] quotient[22] -type PO PO
add mapped point quotient[21] quotient[21] -type PO PO
add mapped point quotient[20] quotient[20] -type PO PO
add mapped point quotient[19] quotient[19] -type PO PO
add mapped point quotient[18] quotient[18] -type PO PO
add mapped point quotient[17] quotient[17] -type PO PO
add mapped point quotient[16] quotient[16] -type PO PO
add mapped point quotient[15] quotient[15] -type PO PO
add mapped point quotient[14] quotient[14] -type PO PO
add mapped point quotient[13] quotient[13] -type PO PO
add mapped point quotient[12] quotient[12] -type PO PO
add mapped point quotient[11] quotient[11] -type PO PO
add mapped point quotient[10] quotient[10] -type PO PO
add mapped point quotient[9] quotient[9] -type PO PO
add mapped point quotient[8] quotient[8] -type PO PO
add mapped point quotient[7] quotient[7] -type PO PO
add mapped point quotient[6] quotient[6] -type PO PO
add mapped point quotient[5] quotient[5] -type PO PO
add mapped point quotient[4] quotient[4] -type PO PO
add mapped point quotient[3] quotient[3] -type PO PO
add mapped point quotient[2] quotient[2] -type PO PO
add mapped point quotient[1] quotient[1] -type PO PO
add mapped point quotient[0] quotient[0] -type PO PO
add mapped point out_valid out_valid -type PO PO

//inout ports




//Sequential Pins
add mapped point den_r[0]/q den_r_reg[0]/Q  -type DFF DFF
add mapped point den_r[1]/q den_r_reg[1]/Q  -type DFF DFF
add mapped point den_r[2]/q den_r_reg[2]/Q  -type DFF DFF
add mapped point den_r[3]/q den_r_reg[3]/Q  -type DFF DFF
add mapped point den_r[4]/q den_r_reg[4]/Q  -type DFF DFF
add mapped point den_r[5]/q den_r_reg[5]/Q  -type DFF DFF
add mapped point den_r[6]/q den_r_reg[6]/Q  -type DFF DFF
add mapped point den_r[7]/q den_r_reg[7]/Q  -type DFF DFF
add mapped point den_r[8]/q den_r_reg[8]/Q  -type DFF DFF
add mapped point den_r[9]/q den_r_reg[9]/Q  -type DFF DFF
add mapped point den_r[10]/q den_r_reg[10]/Q  -type DFF DFF
add mapped point den_r[11]/q den_r_reg[11]/Q  -type DFF DFF
add mapped point den_r[12]/q den_r_reg[12]/Q  -type DFF DFF
add mapped point den_r[13]/q den_r_reg[13]/Q  -type DFF DFF
add mapped point den_r[14]/q den_r_reg[14]/Q  -type DFF DFF
add mapped point den_r[15]/q den_r_reg[15]/Q  -type DFF DFF
add mapped point den_r[16]/q den_r_reg[16]/Q  -type DFF DFF
add mapped point den_r[17]/q den_r_reg[17]/Q  -type DFF DFF
add mapped point den_r[18]/q den_r_reg[18]/Q  -type DFF DFF
add mapped point den_r[19]/q den_r_reg[19]/Q  -type DFF DFF
add mapped point den_r[20]/q den_r_reg[20]/Q  -type DFF DFF
add mapped point den_r[21]/q den_r_reg[21]/Q  -type DFF DFF
add mapped point den_r[22]/q den_r_reg[22]/Q  -type DFF DFF
add mapped point den_r[23]/q den_r_reg[23]/Q  -type DFF DFF
add mapped point den_r[24]/q den_r_reg[24]/Q  -type DFF DFF
add mapped point den_r[25]/q den_r_reg[25]/Q  -type DFF DFF
add mapped point den_r[26]/q den_r_reg[26]/Q  -type DFF DFF
add mapped point den_r[27]/q den_r_reg[27]/Q  -type DFF DFF
add mapped point den_r[28]/q den_r_reg[28]/Q  -type DFF DFF
add mapped point den_r[29]/q den_r_reg[29]/Q  -type DFF DFF
add mapped point den_r[30]/q den_r_reg[30]/Q  -type DFF DFF
add mapped point den_r[31]/q den_r_reg[31]/Q  -type DFF DFF
add mapped point num_r[0]/q num_r_reg[0]/Q  -type DFF DFF
add mapped point num_r[1]/q num_r_reg[1]/Q  -type DFF DFF
add mapped point num_r[2]/q num_r_reg[2]/Q  -type DFF DFF
add mapped point num_r[3]/q num_r_reg[3]/Q  -type DFF DFF
add mapped point num_r[4]/q num_r_reg[4]/Q  -type DFF DFF
add mapped point num_r[5]/q num_r_reg[5]/Q  -type DFF DFF
add mapped point num_r[6]/q num_r_reg[6]/Q  -type DFF DFF
add mapped point num_r[7]/q num_r_reg[7]/Q  -type DFF DFF
add mapped point num_r[8]/q num_r_reg[8]/Q  -type DFF DFF
add mapped point num_r[9]/q num_r_reg[9]/Q  -type DFF DFF
add mapped point num_r[10]/q num_r_reg[10]/Q  -type DFF DFF
add mapped point num_r[11]/q num_r_reg[11]/Q  -type DFF DFF
add mapped point num_r[12]/q num_r_reg[12]/Q  -type DFF DFF
add mapped point num_r[13]/q num_r_reg[13]/Q  -type DFF DFF
add mapped point num_r[14]/q num_r_reg[14]/Q  -type DFF DFF
add mapped point num_r[15]/q num_r_reg[15]/Q  -type DFF DFF
add mapped point num_r[16]/q num_r_reg[16]/Q  -type DFF DFF
add mapped point num_r[17]/q num_r_reg[17]/Q  -type DFF DFF
add mapped point num_r[18]/q num_r_reg[18]/Q  -type DFF DFF
add mapped point num_r[19]/q num_r_reg[19]/Q  -type DFF DFF
add mapped point num_r[20]/q num_r_reg[20]/Q  -type DFF DFF
add mapped point num_r[21]/q num_r_reg[21]/Q  -type DFF DFF
add mapped point num_r[22]/q num_r_reg[22]/Q  -type DFF DFF
add mapped point num_r[23]/q num_r_reg[23]/Q  -type DFF DFF
add mapped point num_r[24]/q num_r_reg[24]/Q  -type DFF DFF
add mapped point num_r[25]/q num_r_reg[25]/Q  -type DFF DFF
add mapped point num_r[26]/q num_r_reg[26]/Q  -type DFF DFF
add mapped point num_r[27]/q num_r_reg[27]/Q  -type DFF DFF
add mapped point num_r[28]/q num_r_reg[28]/Q  -type DFF DFF
add mapped point num_r[29]/q num_r_reg[29]/Q  -type DFF DFF
add mapped point num_r[30]/q num_r_reg[30]/Q  -type DFF DFF
add mapped point num_r[31]/q num_r_reg[31]/Q  -type DFF DFF
add mapped point out_valid/q out_valid_reg/Q  -type DFF DFF
add mapped point quotient[0]/q quotient_reg[0]/Q  -type DFF DFF
add mapped point quotient[1]/q quotient_reg[1]/Q  -type DFF DFF
add mapped point quotient[2]/q quotient_reg[2]/Q  -type DFF DFF
add mapped point quotient[3]/q quotient_reg[3]/Q  -type DFF DFF
add mapped point quotient[4]/q quotient_reg[4]/Q  -type DFF DFF
add mapped point quotient[5]/q quotient_reg[5]/Q  -type DFF DFF
add mapped point quotient[6]/q quotient_reg[6]/Q  -type DFF DFF
add mapped point quotient[7]/q quotient_reg[7]/Q  -type DFF DFF
add mapped point quotient[8]/q quotient_reg[8]/Q  -type DFF DFF
add mapped point quotient[9]/q quotient_reg[9]/Q  -type DFF DFF
add mapped point quotient[10]/q quotient_reg[10]/Q  -type DFF DFF
add mapped point quotient[11]/q quotient_reg[11]/Q  -type DFF DFF
add mapped point quotient[12]/q quotient_reg[12]/Q  -type DFF DFF
add mapped point quotient[13]/q quotient_reg[13]/Q  -type DFF DFF
add mapped point quotient[14]/q quotient_reg[14]/Q  -type DFF DFF
add mapped point quotient[15]/q quotient_reg[15]/Q  -type DFF DFF
add mapped point quotient[16]/q quotient_reg[16]/Q  -type DFF DFF
add mapped point quotient[17]/q quotient_reg[17]/Q  -type DFF DFF
add mapped point quotient[18]/q quotient_reg[18]/Q  -type DFF DFF
add mapped point quotient[19]/q quotient_reg[19]/Q  -type DFF DFF
add mapped point quotient[20]/q quotient_reg[20]/Q  -type DFF DFF
add mapped point quotient[21]/q quotient_reg[21]/Q  -type DFF DFF
add mapped point quotient[22]/q quotient_reg[22]/Q  -type DFF DFF
add mapped point quotient[23]/q quotient_reg[23]/Q  -type DFF DFF
add mapped point quotient[24]/q quotient_reg[24]/Q  -type DFF DFF
add mapped point quotient[25]/q quotient_reg[25]/Q  -type DFF DFF
add mapped point quotient[26]/q quotient_reg[26]/Q  -type DFF DFF
add mapped point quotient[27]/q quotient_reg[27]/Q  -type DFF DFF
add mapped point quotient[28]/q quotient_reg[28]/Q  -type DFF DFF
add mapped point quotient[29]/q quotient_reg[29]/Q  -type DFF DFF
add mapped point quotient[30]/q quotient_reg[30]/Q  -type DFF DFF
add mapped point quotient[31]/q quotient_reg[31]/Q  -type DFF DFF
add mapped point valid_r/q valid_r_reg/Q  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
