/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module sram_bank(clk, req, we, addr, wdata, rdata, rvalid);
  wire [5:0] _000_;
  wire [31:0] _001_;
  wire [31:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  input [5:0] addr;
  wire [5:0] addr;
  input clk;
  wire clk;
  output [31:0] rdata;
  wire [31:0] rdata;
  input req;
  wire req;
  output rvalid;
  wire rvalid;
  input [31:0] wdata;
  wire [31:0] wdata;
  input we;
  wire we;
  reg [31:0] mem [63:0];
  always @(posedge clk) begin
    if (_002_[31])
      mem[_000_] <= _001_;
  end
  assign { _060_, _059_, _057_, _056_, _055_, _054_, _053_, _052_, _051_, _050_, _049_, _048_, _046_, _045_, _044_, _043_, _042_, _041_, _040_, _039_, _038_, _037_, _067_, _066_, _065_, _064_, _063_, _062_, _061_, _058_, _047_, _036_ } = mem[addr];
  sky130_fd_sc_hd__and2b_2 _172_ (
    .A_N(we),
    .B(req),
    .X(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _173_ (
    .A(rdata[0]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__clkinv_1 _174_ (
    .A(we),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand3_1 _175_ (
    .A(_069_),
    .B(req),
    .C(_036_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__o21ai_0 _176_ (
    .A1(_068_),
    .A2(_003_),
    .B1(_070_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _177_ (
    .A(rdata[1]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand3_1 _178_ (
    .A(_069_),
    .B(req),
    .C(_047_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__o21ai_0 _179_ (
    .A1(_071_),
    .A2(_003_),
    .B1(_072_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _180_ (
    .A(rdata[2]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand3_1 _181_ (
    .A(_069_),
    .B(req),
    .C(_058_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o21ai_0 _182_ (
    .A1(_073_),
    .A2(_003_),
    .B1(_074_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _183_ (
    .A(rdata[3]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand3_1 _184_ (
    .A(_069_),
    .B(req),
    .C(_061_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__o21ai_0 _185_ (
    .A1(_075_),
    .A2(_003_),
    .B1(_076_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _186_ (
    .A(rdata[4]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand3_1 _187_ (
    .A(_069_),
    .B(req),
    .C(_062_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__o21ai_0 _188_ (
    .A1(_077_),
    .A2(_003_),
    .B1(_078_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _189_ (
    .A(rdata[5]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand3_1 _190_ (
    .A(_069_),
    .B(req),
    .C(_063_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__o21ai_0 _191_ (
    .A1(_079_),
    .A2(_003_),
    .B1(_080_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _192_ (
    .A(rdata[6]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand3_1 _193_ (
    .A(_069_),
    .B(req),
    .C(_064_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__o21ai_0 _194_ (
    .A1(_081_),
    .A2(_003_),
    .B1(_082_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _195_ (
    .A(rdata[7]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand3_1 _196_ (
    .A(_069_),
    .B(req),
    .C(_065_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__o21ai_0 _197_ (
    .A1(_083_),
    .A2(_003_),
    .B1(_084_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _198_ (
    .A(rdata[8]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand3_1 _199_ (
    .A(_069_),
    .B(req),
    .C(_066_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__o21ai_0 _200_ (
    .A1(_085_),
    .A2(_003_),
    .B1(_086_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _201_ (
    .A(rdata[9]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand3_1 _202_ (
    .A(_069_),
    .B(req),
    .C(_067_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__o21ai_0 _203_ (
    .A1(_087_),
    .A2(_003_),
    .B1(_088_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _204_ (
    .A(rdata[10]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand3_1 _205_ (
    .A(_069_),
    .B(req),
    .C(_037_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__o21ai_0 _206_ (
    .A1(_089_),
    .A2(_003_),
    .B1(_090_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _207_ (
    .A(rdata[11]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand3_1 _208_ (
    .A(_069_),
    .B(req),
    .C(_038_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__o21ai_0 _209_ (
    .A1(_091_),
    .A2(_003_),
    .B1(_092_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _210_ (
    .A(rdata[12]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand3_1 _211_ (
    .A(_069_),
    .B(req),
    .C(_039_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__o21ai_0 _212_ (
    .A1(_093_),
    .A2(_003_),
    .B1(_094_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__clkinv_1 _213_ (
    .A(rdata[13]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand3_1 _214_ (
    .A(_069_),
    .B(req),
    .C(_040_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__o21ai_0 _215_ (
    .A1(_095_),
    .A2(_003_),
    .B1(_096_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__clkinv_1 _216_ (
    .A(rdata[14]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand3_1 _217_ (
    .A(_069_),
    .B(req),
    .C(_041_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__o21ai_0 _218_ (
    .A1(_097_),
    .A2(_003_),
    .B1(_098_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__clkinv_1 _219_ (
    .A(rdata[15]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand3_1 _220_ (
    .A(_069_),
    .B(req),
    .C(_042_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__o21ai_0 _221_ (
    .A1(_099_),
    .A2(_003_),
    .B1(_100_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _222_ (
    .A(rdata[16]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand3_1 _223_ (
    .A(_069_),
    .B(req),
    .C(_043_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__o21ai_0 _224_ (
    .A1(_101_),
    .A2(_003_),
    .B1(_102_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _225_ (
    .A(rdata[17]),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand3_1 _226_ (
    .A(_069_),
    .B(req),
    .C(_044_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o21ai_0 _227_ (
    .A1(_103_),
    .A2(_003_),
    .B1(_104_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__clkinv_1 _228_ (
    .A(rdata[18]),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand3_1 _229_ (
    .A(_069_),
    .B(req),
    .C(_045_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__o21ai_0 _230_ (
    .A1(_105_),
    .A2(_003_),
    .B1(_106_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__clkinv_1 _231_ (
    .A(rdata[19]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand3_1 _232_ (
    .A(_069_),
    .B(req),
    .C(_046_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__o21ai_0 _233_ (
    .A1(_107_),
    .A2(_003_),
    .B1(_108_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__clkinv_1 _234_ (
    .A(rdata[20]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand3_1 _235_ (
    .A(_069_),
    .B(req),
    .C(_048_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__o21ai_0 _236_ (
    .A1(_109_),
    .A2(_003_),
    .B1(_110_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _237_ (
    .A(rdata[21]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nand3_1 _238_ (
    .A(_069_),
    .B(req),
    .C(_049_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__o21ai_0 _239_ (
    .A1(_111_),
    .A2(_003_),
    .B1(_112_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__clkinv_1 _240_ (
    .A(rdata[22]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand3_1 _241_ (
    .A(_069_),
    .B(req),
    .C(_050_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__o21ai_0 _242_ (
    .A1(_113_),
    .A2(_003_),
    .B1(_114_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__clkinv_1 _243_ (
    .A(rdata[23]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nand3_1 _244_ (
    .A(_069_),
    .B(req),
    .C(_051_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__o21ai_0 _245_ (
    .A1(_115_),
    .A2(_003_),
    .B1(_116_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _246_ (
    .A(rdata[24]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand3_1 _247_ (
    .A(_069_),
    .B(req),
    .C(_052_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__o21ai_0 _248_ (
    .A1(_117_),
    .A2(_003_),
    .B1(_118_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__clkinv_1 _249_ (
    .A(rdata[25]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand3_1 _250_ (
    .A(_069_),
    .B(req),
    .C(_053_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__o21ai_0 _251_ (
    .A1(_119_),
    .A2(_003_),
    .B1(_120_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__clkinv_1 _252_ (
    .A(rdata[26]),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand3_1 _253_ (
    .A(_069_),
    .B(req),
    .C(_054_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__o21ai_0 _254_ (
    .A1(_121_),
    .A2(_003_),
    .B1(_122_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__clkinv_1 _255_ (
    .A(rdata[27]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand3_1 _256_ (
    .A(_069_),
    .B(req),
    .C(_055_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__o21ai_0 _257_ (
    .A1(_123_),
    .A2(_003_),
    .B1(_124_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__clkinv_1 _258_ (
    .A(rdata[28]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand3_1 _259_ (
    .A(_069_),
    .B(req),
    .C(_056_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__o21ai_0 _260_ (
    .A1(_125_),
    .A2(_003_),
    .B1(_126_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__clkinv_1 _261_ (
    .A(rdata[29]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nand3_1 _262_ (
    .A(_069_),
    .B(req),
    .C(_057_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__o21ai_0 _263_ (
    .A1(_127_),
    .A2(_003_),
    .B1(_128_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__clkinv_1 _264_ (
    .A(rdata[30]),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand3_1 _265_ (
    .A(_069_),
    .B(req),
    .C(_059_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__o21ai_0 _266_ (
    .A1(_129_),
    .A2(_003_),
    .B1(_130_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__clkinv_1 _267_ (
    .A(rdata[31]),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand3_1 _268_ (
    .A(_069_),
    .B(req),
    .C(_060_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__o21ai_0 _269_ (
    .A1(_131_),
    .A2(_003_),
    .B1(_132_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(req),
    .B(we),
    .Y(_133_)
  );
  sky130_fd_sc_hd__clkinv_1 _271_ (
    .A(_133_),
    .Y(_002_[31])
  );
  sky130_fd_sc_hd__clkinv_1 _272_ (
    .A(wdata[0]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nor2_1 _273_ (
    .A(_134_),
    .B(_133_),
    .Y(_001_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _274_ (
    .A(wdata[1]),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nor2_1 _275_ (
    .A(_135_),
    .B(_133_),
    .Y(_001_[1])
  );
  sky130_fd_sc_hd__clkinv_1 _276_ (
    .A(wdata[2]),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nor2_1 _277_ (
    .A(_136_),
    .B(_133_),
    .Y(_001_[2])
  );
  sky130_fd_sc_hd__clkinv_1 _278_ (
    .A(wdata[3]),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nor2_1 _279_ (
    .A(_137_),
    .B(_133_),
    .Y(_001_[3])
  );
  sky130_fd_sc_hd__clkinv_1 _280_ (
    .A(wdata[4]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor2_1 _281_ (
    .A(_138_),
    .B(_133_),
    .Y(_001_[4])
  );
  sky130_fd_sc_hd__clkinv_1 _282_ (
    .A(wdata[5]),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nor2_1 _283_ (
    .A(_139_),
    .B(_133_),
    .Y(_001_[5])
  );
  sky130_fd_sc_hd__clkinv_1 _284_ (
    .A(wdata[6]),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nor2_1 _285_ (
    .A(_140_),
    .B(_133_),
    .Y(_001_[6])
  );
  sky130_fd_sc_hd__clkinv_1 _286_ (
    .A(wdata[7]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nor2_1 _287_ (
    .A(_141_),
    .B(_133_),
    .Y(_001_[7])
  );
  sky130_fd_sc_hd__clkinv_1 _288_ (
    .A(wdata[8]),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nor2_1 _289_ (
    .A(_142_),
    .B(_133_),
    .Y(_001_[8])
  );
  sky130_fd_sc_hd__clkinv_1 _290_ (
    .A(wdata[9]),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nor2_1 _291_ (
    .A(_143_),
    .B(_133_),
    .Y(_001_[9])
  );
  sky130_fd_sc_hd__clkinv_1 _292_ (
    .A(wdata[10]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nor2_1 _293_ (
    .A(_144_),
    .B(_133_),
    .Y(_001_[10])
  );
  sky130_fd_sc_hd__clkinv_1 _294_ (
    .A(wdata[11]),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nor2_1 _295_ (
    .A(_145_),
    .B(_133_),
    .Y(_001_[11])
  );
  sky130_fd_sc_hd__clkinv_1 _296_ (
    .A(wdata[12]),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nor2_1 _297_ (
    .A(_146_),
    .B(_133_),
    .Y(_001_[12])
  );
  sky130_fd_sc_hd__clkinv_1 _298_ (
    .A(wdata[13]),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nor2_1 _299_ (
    .A(_147_),
    .B(_133_),
    .Y(_001_[13])
  );
  sky130_fd_sc_hd__clkinv_1 _300_ (
    .A(wdata[14]),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nor2_1 _301_ (
    .A(_148_),
    .B(_133_),
    .Y(_001_[14])
  );
  sky130_fd_sc_hd__clkinv_1 _302_ (
    .A(wdata[15]),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nor2_1 _303_ (
    .A(_149_),
    .B(_133_),
    .Y(_001_[15])
  );
  sky130_fd_sc_hd__clkinv_1 _304_ (
    .A(wdata[16]),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor2_1 _305_ (
    .A(_150_),
    .B(_133_),
    .Y(_001_[16])
  );
  sky130_fd_sc_hd__clkinv_1 _306_ (
    .A(wdata[17]),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nor2_1 _307_ (
    .A(_151_),
    .B(_133_),
    .Y(_001_[17])
  );
  sky130_fd_sc_hd__clkinv_1 _308_ (
    .A(wdata[18]),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nor2_1 _309_ (
    .A(_152_),
    .B(_133_),
    .Y(_001_[18])
  );
  sky130_fd_sc_hd__clkinv_1 _310_ (
    .A(wdata[19]),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nor2_1 _311_ (
    .A(_153_),
    .B(_133_),
    .Y(_001_[19])
  );
  sky130_fd_sc_hd__clkinv_1 _312_ (
    .A(wdata[20]),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _313_ (
    .A(_154_),
    .B(_133_),
    .Y(_001_[20])
  );
  sky130_fd_sc_hd__clkinv_1 _314_ (
    .A(wdata[21]),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nor2_1 _315_ (
    .A(_155_),
    .B(_133_),
    .Y(_001_[21])
  );
  sky130_fd_sc_hd__clkinv_1 _316_ (
    .A(wdata[22]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor2_1 _317_ (
    .A(_156_),
    .B(_133_),
    .Y(_001_[22])
  );
  sky130_fd_sc_hd__clkinv_1 _318_ (
    .A(wdata[23]),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nor2_1 _319_ (
    .A(_157_),
    .B(_133_),
    .Y(_001_[23])
  );
  sky130_fd_sc_hd__clkinv_1 _320_ (
    .A(wdata[24]),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nor2_1 _321_ (
    .A(_158_),
    .B(_133_),
    .Y(_001_[24])
  );
  sky130_fd_sc_hd__clkinv_1 _322_ (
    .A(wdata[25]),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nor2_1 _323_ (
    .A(_159_),
    .B(_133_),
    .Y(_001_[25])
  );
  sky130_fd_sc_hd__clkinv_1 _324_ (
    .A(wdata[26]),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nor2_1 _325_ (
    .A(_160_),
    .B(_133_),
    .Y(_001_[26])
  );
  sky130_fd_sc_hd__clkinv_1 _326_ (
    .A(wdata[27]),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nor2_1 _327_ (
    .A(_161_),
    .B(_133_),
    .Y(_001_[27])
  );
  sky130_fd_sc_hd__clkinv_1 _328_ (
    .A(wdata[28]),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nor2_1 _329_ (
    .A(_162_),
    .B(_133_),
    .Y(_001_[28])
  );
  sky130_fd_sc_hd__clkinv_1 _330_ (
    .A(wdata[29]),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nor2_1 _331_ (
    .A(_163_),
    .B(_133_),
    .Y(_001_[29])
  );
  sky130_fd_sc_hd__clkinv_1 _332_ (
    .A(wdata[30]),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nor2_1 _333_ (
    .A(_164_),
    .B(_133_),
    .Y(_001_[30])
  );
  sky130_fd_sc_hd__clkinv_1 _334_ (
    .A(wdata[31]),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nor2_1 _335_ (
    .A(_165_),
    .B(_133_),
    .Y(_001_[31])
  );
  sky130_fd_sc_hd__clkinv_1 _336_ (
    .A(addr[0]),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nor2_1 _337_ (
    .A(_166_),
    .B(_133_),
    .Y(_000_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _338_ (
    .A(addr[1]),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nor2_1 _339_ (
    .A(_167_),
    .B(_133_),
    .Y(_000_[1])
  );
  sky130_fd_sc_hd__clkinv_1 _340_ (
    .A(addr[2]),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nor2_1 _341_ (
    .A(_168_),
    .B(_133_),
    .Y(_000_[2])
  );
  sky130_fd_sc_hd__clkinv_1 _342_ (
    .A(addr[3]),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nor2_1 _343_ (
    .A(_169_),
    .B(_133_),
    .Y(_000_[3])
  );
  sky130_fd_sc_hd__clkinv_1 _344_ (
    .A(addr[4]),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nor2_1 _345_ (
    .A(_170_),
    .B(_133_),
    .Y(_000_[4])
  );
  sky130_fd_sc_hd__clkinv_1 _346_ (
    .A(addr[5]),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nor2_1 _347_ (
    .A(_171_),
    .B(_133_),
    .Y(_000_[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _348_ (
    .CLK(clk),
    .D(_003_),
    .Q(rvalid)
  );
  sky130_fd_sc_hd__dfxtp_1 _349_ (
    .CLK(clk),
    .D(_004_),
    .Q(rdata[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _350_ (
    .CLK(clk),
    .D(_005_),
    .Q(rdata[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _351_ (
    .CLK(clk),
    .D(_006_),
    .Q(rdata[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _352_ (
    .CLK(clk),
    .D(_007_),
    .Q(rdata[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _353_ (
    .CLK(clk),
    .D(_008_),
    .Q(rdata[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _354_ (
    .CLK(clk),
    .D(_009_),
    .Q(rdata[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _355_ (
    .CLK(clk),
    .D(_010_),
    .Q(rdata[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _356_ (
    .CLK(clk),
    .D(_011_),
    .Q(rdata[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _357_ (
    .CLK(clk),
    .D(_012_),
    .Q(rdata[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _358_ (
    .CLK(clk),
    .D(_013_),
    .Q(rdata[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _359_ (
    .CLK(clk),
    .D(_014_),
    .Q(rdata[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _360_ (
    .CLK(clk),
    .D(_015_),
    .Q(rdata[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _361_ (
    .CLK(clk),
    .D(_016_),
    .Q(rdata[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _362_ (
    .CLK(clk),
    .D(_017_),
    .Q(rdata[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _363_ (
    .CLK(clk),
    .D(_018_),
    .Q(rdata[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _364_ (
    .CLK(clk),
    .D(_019_),
    .Q(rdata[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _365_ (
    .CLK(clk),
    .D(_020_),
    .Q(rdata[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _366_ (
    .CLK(clk),
    .D(_021_),
    .Q(rdata[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _367_ (
    .CLK(clk),
    .D(_022_),
    .Q(rdata[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _368_ (
    .CLK(clk),
    .D(_023_),
    .Q(rdata[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _369_ (
    .CLK(clk),
    .D(_024_),
    .Q(rdata[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _370_ (
    .CLK(clk),
    .D(_025_),
    .Q(rdata[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _371_ (
    .CLK(clk),
    .D(_026_),
    .Q(rdata[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _372_ (
    .CLK(clk),
    .D(_027_),
    .Q(rdata[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _373_ (
    .CLK(clk),
    .D(_028_),
    .Q(rdata[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _374_ (
    .CLK(clk),
    .D(_029_),
    .Q(rdata[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _375_ (
    .CLK(clk),
    .D(_030_),
    .Q(rdata[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _376_ (
    .CLK(clk),
    .D(_031_),
    .Q(rdata[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _377_ (
    .CLK(clk),
    .D(_032_),
    .Q(rdata[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _378_ (
    .CLK(clk),
    .D(_033_),
    .Q(rdata[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _379_ (
    .CLK(clk),
    .D(_034_),
    .Q(rdata[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _380_ (
    .CLK(clk),
    .D(_035_),
    .Q(rdata[31])
  );
  assign _002_[30:0] = { _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31], _002_[31] };
endmodule
