/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module pipeline_stage(clk, rst_n, in_data, in_valid, in_ready, out_data, out_valid, out_ready);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  input clk;
  wire clk;
  input [31:0] in_data;
  wire [31:0] in_data;
  output in_ready;
  wire in_ready;
  input in_valid;
  wire in_valid;
  output [31:0] out_data;
  wire [31:0] out_data;
  input out_ready;
  wire out_ready;
  output out_valid;
  wire out_valid;
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__clkinv_1 _100_ (
    .A(out_ready),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _101_ (
    .A(_033_),
    .B(out_valid),
    .Y(in_ready)
  );
  sky130_fd_sc_hd__clkinv_1 _102_ (
    .A(in_data[0]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__and2b_2 _103_ (
    .A_N(out_ready),
    .B(out_valid),
    .X(_035_)
  );
  sky130_fd_sc_hd__nand3_1 _104_ (
    .A(_033_),
    .B(out_data[0]),
    .C(out_valid),
    .Y(_036_)
  );
  sky130_fd_sc_hd__o21ai_0 _105_ (
    .A1(_034_),
    .A2(_035_),
    .B1(_036_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _106_ (
    .A(in_data[1]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand3_1 _107_ (
    .A(_033_),
    .B(out_data[1]),
    .C(out_valid),
    .Y(_038_)
  );
  sky130_fd_sc_hd__o21ai_0 _108_ (
    .A1(_037_),
    .A2(_035_),
    .B1(_038_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _109_ (
    .A(in_data[2]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand3_1 _110_ (
    .A(_033_),
    .B(out_data[2]),
    .C(out_valid),
    .Y(_040_)
  );
  sky130_fd_sc_hd__o21ai_0 _111_ (
    .A1(_039_),
    .A2(_035_),
    .B1(_040_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _112_ (
    .A(in_data[3]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand3_1 _113_ (
    .A(_033_),
    .B(out_data[3]),
    .C(out_valid),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o21ai_0 _114_ (
    .A1(_041_),
    .A2(_035_),
    .B1(_042_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _115_ (
    .A(in_data[4]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand3_1 _116_ (
    .A(_033_),
    .B(out_data[4]),
    .C(out_valid),
    .Y(_044_)
  );
  sky130_fd_sc_hd__o21ai_0 _117_ (
    .A1(_043_),
    .A2(_035_),
    .B1(_044_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _118_ (
    .A(in_data[5]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand3_1 _119_ (
    .A(_033_),
    .B(out_data[5]),
    .C(out_valid),
    .Y(_046_)
  );
  sky130_fd_sc_hd__o21ai_0 _120_ (
    .A1(_045_),
    .A2(_035_),
    .B1(_046_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _121_ (
    .A(in_data[6]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand3_1 _122_ (
    .A(_033_),
    .B(out_data[6]),
    .C(out_valid),
    .Y(_048_)
  );
  sky130_fd_sc_hd__o21ai_0 _123_ (
    .A1(_047_),
    .A2(_035_),
    .B1(_048_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _124_ (
    .A(in_data[7]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand3_1 _125_ (
    .A(_033_),
    .B(out_data[7]),
    .C(out_valid),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o21ai_0 _126_ (
    .A1(_049_),
    .A2(_035_),
    .B1(_050_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _127_ (
    .A(in_data[8]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand3_1 _128_ (
    .A(_033_),
    .B(out_data[8]),
    .C(out_valid),
    .Y(_052_)
  );
  sky130_fd_sc_hd__o21ai_0 _129_ (
    .A1(_051_),
    .A2(_035_),
    .B1(_052_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _130_ (
    .A(in_data[9]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand3_1 _131_ (
    .A(_033_),
    .B(out_data[9]),
    .C(out_valid),
    .Y(_054_)
  );
  sky130_fd_sc_hd__o21ai_0 _132_ (
    .A1(_053_),
    .A2(_035_),
    .B1(_054_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _133_ (
    .A(in_data[10]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand3_1 _134_ (
    .A(_033_),
    .B(out_data[10]),
    .C(out_valid),
    .Y(_056_)
  );
  sky130_fd_sc_hd__o21ai_0 _135_ (
    .A1(_055_),
    .A2(_035_),
    .B1(_056_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _136_ (
    .A(in_data[11]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand3_1 _137_ (
    .A(_033_),
    .B(out_data[11]),
    .C(out_valid),
    .Y(_058_)
  );
  sky130_fd_sc_hd__o21ai_0 _138_ (
    .A1(_057_),
    .A2(_035_),
    .B1(_058_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _139_ (
    .A(in_data[12]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand3_1 _140_ (
    .A(_033_),
    .B(out_data[12]),
    .C(out_valid),
    .Y(_060_)
  );
  sky130_fd_sc_hd__o21ai_0 _141_ (
    .A1(_059_),
    .A2(_035_),
    .B1(_060_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _142_ (
    .A(in_data[13]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand3_1 _143_ (
    .A(_033_),
    .B(out_data[13]),
    .C(out_valid),
    .Y(_062_)
  );
  sky130_fd_sc_hd__o21ai_0 _144_ (
    .A1(_061_),
    .A2(_035_),
    .B1(_062_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _145_ (
    .A(in_data[14]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand3_1 _146_ (
    .A(_033_),
    .B(out_data[14]),
    .C(out_valid),
    .Y(_064_)
  );
  sky130_fd_sc_hd__o21ai_0 _147_ (
    .A1(_063_),
    .A2(_035_),
    .B1(_064_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _148_ (
    .A(in_data[15]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand3_1 _149_ (
    .A(_033_),
    .B(out_data[15]),
    .C(out_valid),
    .Y(_066_)
  );
  sky130_fd_sc_hd__o21ai_0 _150_ (
    .A1(_065_),
    .A2(_035_),
    .B1(_066_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _151_ (
    .A(in_data[16]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand3_1 _152_ (
    .A(_033_),
    .B(out_data[16]),
    .C(out_valid),
    .Y(_068_)
  );
  sky130_fd_sc_hd__o21ai_0 _153_ (
    .A1(_067_),
    .A2(_035_),
    .B1(_068_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__clkinv_1 _154_ (
    .A(in_data[17]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand3_1 _155_ (
    .A(_033_),
    .B(out_data[17]),
    .C(out_valid),
    .Y(_070_)
  );
  sky130_fd_sc_hd__o21ai_0 _156_ (
    .A1(_069_),
    .A2(_035_),
    .B1(_070_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__clkinv_1 _157_ (
    .A(in_data[18]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand3_1 _158_ (
    .A(_033_),
    .B(out_data[18]),
    .C(out_valid),
    .Y(_072_)
  );
  sky130_fd_sc_hd__o21ai_0 _159_ (
    .A1(_071_),
    .A2(_035_),
    .B1(_072_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__clkinv_1 _160_ (
    .A(in_data[19]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand3_1 _161_ (
    .A(_033_),
    .B(out_data[19]),
    .C(out_valid),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o21ai_0 _162_ (
    .A1(_073_),
    .A2(_035_),
    .B1(_074_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _163_ (
    .A(in_data[20]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand3_1 _164_ (
    .A(_033_),
    .B(out_data[20]),
    .C(out_valid),
    .Y(_076_)
  );
  sky130_fd_sc_hd__o21ai_0 _165_ (
    .A1(_075_),
    .A2(_035_),
    .B1(_076_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _166_ (
    .A(in_data[21]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand3_1 _167_ (
    .A(_033_),
    .B(out_data[21]),
    .C(out_valid),
    .Y(_078_)
  );
  sky130_fd_sc_hd__o21ai_0 _168_ (
    .A1(_077_),
    .A2(_035_),
    .B1(_078_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__clkinv_1 _169_ (
    .A(in_data[22]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand3_1 _170_ (
    .A(_033_),
    .B(out_data[22]),
    .C(out_valid),
    .Y(_080_)
  );
  sky130_fd_sc_hd__o21ai_0 _171_ (
    .A1(_079_),
    .A2(_035_),
    .B1(_080_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__clkinv_1 _172_ (
    .A(in_data[23]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand3_1 _173_ (
    .A(_033_),
    .B(out_data[23]),
    .C(out_valid),
    .Y(_082_)
  );
  sky130_fd_sc_hd__o21ai_0 _174_ (
    .A1(_081_),
    .A2(_035_),
    .B1(_082_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__clkinv_1 _175_ (
    .A(in_data[24]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand3_1 _176_ (
    .A(_033_),
    .B(out_data[24]),
    .C(out_valid),
    .Y(_084_)
  );
  sky130_fd_sc_hd__o21ai_0 _177_ (
    .A1(_083_),
    .A2(_035_),
    .B1(_084_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _178_ (
    .A(in_data[25]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand3_1 _179_ (
    .A(_033_),
    .B(out_data[25]),
    .C(out_valid),
    .Y(_086_)
  );
  sky130_fd_sc_hd__o21ai_0 _180_ (
    .A1(_085_),
    .A2(_035_),
    .B1(_086_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__clkinv_1 _181_ (
    .A(in_data[26]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand3_1 _182_ (
    .A(_033_),
    .B(out_data[26]),
    .C(out_valid),
    .Y(_088_)
  );
  sky130_fd_sc_hd__o21ai_0 _183_ (
    .A1(_087_),
    .A2(_035_),
    .B1(_088_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__clkinv_1 _184_ (
    .A(in_data[27]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand3_1 _185_ (
    .A(_033_),
    .B(out_data[27]),
    .C(out_valid),
    .Y(_090_)
  );
  sky130_fd_sc_hd__o21ai_0 _186_ (
    .A1(_089_),
    .A2(_035_),
    .B1(_090_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _187_ (
    .A(in_data[28]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand3_1 _188_ (
    .A(_033_),
    .B(out_data[28]),
    .C(out_valid),
    .Y(_092_)
  );
  sky130_fd_sc_hd__o21ai_0 _189_ (
    .A1(_091_),
    .A2(_035_),
    .B1(_092_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__clkinv_1 _190_ (
    .A(in_data[29]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand3_1 _191_ (
    .A(_033_),
    .B(out_data[29]),
    .C(out_valid),
    .Y(_094_)
  );
  sky130_fd_sc_hd__o21ai_0 _192_ (
    .A1(_093_),
    .A2(_035_),
    .B1(_094_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__clkinv_1 _193_ (
    .A(in_data[30]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand3_1 _194_ (
    .A(_033_),
    .B(out_data[30]),
    .C(out_valid),
    .Y(_096_)
  );
  sky130_fd_sc_hd__o21ai_0 _195_ (
    .A1(_095_),
    .A2(_035_),
    .B1(_096_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__clkinv_1 _196_ (
    .A(in_data[31]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand3_1 _197_ (
    .A(_033_),
    .B(out_data[31]),
    .C(out_valid),
    .Y(_098_)
  );
  sky130_fd_sc_hd__o21ai_0 _198_ (
    .A1(_097_),
    .A2(_035_),
    .B1(_098_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__clkinv_1 _199_ (
    .A(in_valid),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _200_ (
    .A(in_ready),
    .B(_099_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__dfrtp_1 _201_ (
    .CLK(clk),
    .D(_000_),
    .Q(out_data[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _202_ (
    .CLK(clk),
    .D(_001_),
    .Q(out_data[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _203_ (
    .CLK(clk),
    .D(_002_),
    .Q(out_data[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _204_ (
    .CLK(clk),
    .D(_003_),
    .Q(out_data[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _205_ (
    .CLK(clk),
    .D(_004_),
    .Q(out_data[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _206_ (
    .CLK(clk),
    .D(_005_),
    .Q(out_data[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _207_ (
    .CLK(clk),
    .D(_006_),
    .Q(out_data[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _208_ (
    .CLK(clk),
    .D(_007_),
    .Q(out_data[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _209_ (
    .CLK(clk),
    .D(_008_),
    .Q(out_data[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _210_ (
    .CLK(clk),
    .D(_009_),
    .Q(out_data[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _211_ (
    .CLK(clk),
    .D(_010_),
    .Q(out_data[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _212_ (
    .CLK(clk),
    .D(_011_),
    .Q(out_data[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _213_ (
    .CLK(clk),
    .D(_012_),
    .Q(out_data[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _214_ (
    .CLK(clk),
    .D(_013_),
    .Q(out_data[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _215_ (
    .CLK(clk),
    .D(_014_),
    .Q(out_data[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _216_ (
    .CLK(clk),
    .D(_015_),
    .Q(out_data[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _217_ (
    .CLK(clk),
    .D(_016_),
    .Q(out_data[16]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _218_ (
    .CLK(clk),
    .D(_017_),
    .Q(out_data[17]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _219_ (
    .CLK(clk),
    .D(_018_),
    .Q(out_data[18]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _220_ (
    .CLK(clk),
    .D(_019_),
    .Q(out_data[19]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _221_ (
    .CLK(clk),
    .D(_020_),
    .Q(out_data[20]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _222_ (
    .CLK(clk),
    .D(_021_),
    .Q(out_data[21]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _223_ (
    .CLK(clk),
    .D(_022_),
    .Q(out_data[22]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _224_ (
    .CLK(clk),
    .D(_023_),
    .Q(out_data[23]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _225_ (
    .CLK(clk),
    .D(_024_),
    .Q(out_data[24]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _226_ (
    .CLK(clk),
    .D(_025_),
    .Q(out_data[25]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _227_ (
    .CLK(clk),
    .D(_026_),
    .Q(out_data[26]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _228_ (
    .CLK(clk),
    .D(_027_),
    .Q(out_data[27]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _229_ (
    .CLK(clk),
    .D(_028_),
    .Q(out_data[28]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _230_ (
    .CLK(clk),
    .D(_029_),
    .Q(out_data[29]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _231_ (
    .CLK(clk),
    .D(_030_),
    .Q(out_data[30]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _232_ (
    .CLK(clk),
    .D(_031_),
    .Q(out_data[31]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _233_ (
    .CLK(clk),
    .D(_032_),
    .Q(out_valid),
    .RESET_B(rst_n)
  );
endmodule
