#!/usr/bin/env python3
"""collect_sweep_csv.py -- Walk out_sweep/* and emit sweep_results.csv.

For each subdirectory under out_sweep/, extracts:
    top, N, NRD, cells, cell_area_um2, total_area_um2, WNS_ps,
    leakage_W, internal_W, switching_W, total_W
from reports/{area,timing,power,qor}.rpt.

Outputs a CSV that analyze_sweep.py can consume.

Runs on phobos (after the sweep) or locally on Windows (after pulling
out_sweep/ down via rsync/scp).

Usage:
    python3 collect_sweep_csv.py [--root out_sweep] [--out sweep_results.csv]

Robust to:
  - Missing reports (point still in flight or failed) -> 'NA'
  - Different Genus 21.12 report layouts (Cell Area / Total Area / etc.)
"""

from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path

# Tag patterns -> (top, N, NRD)
_TAG_PATTERNS = [
    # systolic_array_64x64_8x8 -> top="systolic_array_64x64", N=8
    (re.compile(r"^(systolic_array_64x64)_(\d+)x\2$"),
     lambda m: (m.group(1), int(m.group(2)), 1)),
    # stream_pipeline_8x8 -> top="stream_pipeline", N=8
    (re.compile(r"^(stream_pipeline)_(\d+)x\2$"),
     lambda m: (m.group(1), int(m.group(2)), 1)),
    # tile_buffer_d32_p1 -> top="tile_buffer", N=32 (TILE_DIM), NRD=1
    # Must be matched before the legacy p<NRD> form below.
    (re.compile(r"^(tile_buffer)_d(\d+)_p(\d+)$"),
     lambda m: (m.group(1), int(m.group(2)), int(m.group(3)))),
    # tile_buffer_p64 -> top="tile_buffer", N=64 (legacy TILE_DIM=64 default), NRD=64
    (re.compile(r"^(tile_buffer)_p(\d+)$"),
     lambda m: (m.group(1), 64, int(m.group(2)))),
    # softmax_unit_v32 -> top="softmax_unit", N=32 (VEC_LEN), NRD=1
    (re.compile(r"^(softmax_unit)_v(\d+)$"),
     lambda m: (m.group(1), int(m.group(2)), 1)),
    # adder_tree_n32 -> top="adder_tree", N=32 (NUM_INPUTS), NRD=1
    (re.compile(r"^(adder_tree)_n(\d+)$"),
     lambda m: (m.group(1), int(m.group(2)), 1)),
    # everything else: top is the whole tag, N=1, NRD=1
    (re.compile(r"^(.+)$"),
     lambda m: (m.group(1), 1, 1)),
]


def parse_tag(tag: str) -> tuple[str, int, int]:
    for rx, fn in _TAG_PATTERNS:
        m = rx.match(tag)
        if m:
            return fn(m)
    return (tag, 1, 1)


# ---------------------------------------------------------------------------
# area.rpt -- look for the synth top instance row in the area table.
#
# Genus 21.12 report_area emits something like:
#
#   Generated by: ...
#   Module: systolic_array_64x64
#       Instance      Module       Cell Count   Cell Area    ...   Total Area
#       ----------    ----------   ----------   ----------         ----------
#       <top>         <module>     12345        23456.789          24567.890
#
# We grab the first non-header content row whose first token matches the
# synth-top name (or, failing that, the first numeric row after the dashes).
# ---------------------------------------------------------------------------
def parse_area(rpt: Path, top: str) -> dict[str, str]:
    out = {"cells": "NA", "cell_area_um2": "NA", "total_area_um2": "NA"}
    if not rpt.exists():
        return out
    saw_dashes = False
    for line in rpt.read_text(errors="ignore").splitlines():
        s = line.strip()
        if not s:
            continue
        if set(s) <= set("- "):
            saw_dashes = True
            continue
        if not saw_dashes:
            continue
        # Content row. Tokens: instance, module, cell_count, areas...
        toks = s.split()
        if len(toks) < 4:
            continue
        # First numeric token is cell count
        num_idx = None
        for i, t in enumerate(toks):
            if t.replace(",", "").isdigit():
                num_idx = i
                break
        if num_idx is None:
            continue
        try:
            cells = int(toks[num_idx].replace(",", ""))
            cell_area = float(toks[num_idx + 1].replace(",", ""))
            # If there's a 'Total Area' column it's the last float on the row
            total_area = cell_area
            for t in reversed(toks[num_idx + 1:]):
                try:
                    total_area = float(t.replace(",", ""))
                    break
                except ValueError:
                    continue
        except (ValueError, IndexError):
            continue
        # Prefer the row whose instance matches the synth top
        if toks[0] == top or out["cells"] == "NA":
            out["cells"] = str(cells)
            out["cell_area_um2"] = f"{cell_area:.3f}"
            out["total_area_um2"] = f"{total_area:.3f}"
        if toks[0] == top:
            break
    return out


# ---------------------------------------------------------------------------
# qor.rpt -- Genus prints a "Cost Group" table with one row per clock domain:
#
#   Cost    Critical               Violating
#  Group   Path Slack     TNS        Paths
# -------------------------------------------
# clk          -668.9   -730897.5       1423
#
# We extract the slack column of the clk row (already in ps).
# Fall back to timing.rpt scanning for a "Slack" line if qor isn't there.
# ---------------------------------------------------------------------------
_QOR_CLK_ROW_RX = re.compile(
    r"^\s*clk\s+(-?\d+\.?\d*)\s+(-?\d+\.?\d*)\s+\d+\s*$",
    re.MULTILINE,
)
_QOR_CLK_NOPATHS_RX = re.compile(r"^\s*clk\s+No paths\s+", re.MULTILINE)
_TIMING_SLACK_RX = re.compile(r"^\s*Slack\s*:?\s*(-?\d+\.?\d*)", re.MULTILINE)


def parse_wns_ps(qor: Path, timing: Path) -> str:
    for f in (qor, timing):
        if not f.exists():
            continue
        txt = f.read_text(errors="ignore")
        m = _QOR_CLK_ROW_RX.search(txt)
        if m:
            return m.group(1)
        if _QOR_CLK_NOPATHS_RX.search(txt):
            return "0.0"
        m = _TIMING_SLACK_RX.search(txt)
        if m:
            # Slack reported in ns by default -> convert to ps for the CSV
            try:
                return f"{float(m.group(1)) * 1000.0:.1f}"
            except ValueError:
                return m.group(1)
    return "NA"


# ---------------------------------------------------------------------------
# power.rpt -- Genus prints a table with a "Subtotal" row containing all
# four power values in Watts (the "Power Unit: W" line at top sets unit):
#
#   Category         Leakage     Internal    Switching        Total    Row%
#   Subtotal     2.71706e-03  2.66715e-02  3.96298e-03  3.33516e-02 100.00%
#
# We grab the Subtotal row directly. If "Power Unit: <X>" specifies a
# different unit (mW/uW/nW), we apply the scale.
# ---------------------------------------------------------------------------
_UNIT_SCALE = {"W": 1.0, "mW": 1e-3, "uW": 1e-6, "nW": 1e-9, "pW": 1e-12}
_POWER_UNIT_RX = re.compile(r"Power Unit:\s*(\S+)", re.IGNORECASE)
_POWER_SUBTOTAL_RX = re.compile(
    r"Subtotal\s+([\d.eE+-]+)\s+([\d.eE+-]+)\s+([\d.eE+-]+)\s+([\d.eE+-]+)",
)


def parse_power(rpt: Path) -> dict[str, str]:
    out = {"leakage_W": "NA", "internal_W": "NA",
           "switching_W": "NA", "total_W": "NA"}
    if not rpt.exists():
        return out
    txt = rpt.read_text(errors="ignore")
    unit_match = _POWER_UNIT_RX.search(txt)
    scale = _UNIT_SCALE.get(unit_match.group(1), 1.0) if unit_match else 1.0
    m = _POWER_SUBTOTAL_RX.search(txt)
    if not m:
        return out
    try:
        leak, intern, switch, total = (float(m.group(i)) * scale for i in (1, 2, 3, 4))
    except ValueError:
        return out
    out["leakage_W"] = f"{leak:.6e}"
    out["internal_W"] = f"{intern:.6e}"
    out["switching_W"] = f"{switch:.6e}"
    out["total_W"] = f"{total:.6e}"
    return out


# ---------------------------------------------------------------------------
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default="out_sweep",
                    help="Directory containing per-point subdirs (default: out_sweep)")
    ap.add_argument("--out", default="sweep_results.csv",
                    help="Output CSV path (default: sweep_results.csv)")
    args = ap.parse_args()

    root = Path(args.root)
    if not root.is_dir():
        print(f"ERROR: {root} not a directory")
        return 1

    rows = []
    for sub in sorted(root.iterdir()):
        if not sub.is_dir():
            continue
        tag = sub.name
        top, n, nrd = parse_tag(tag)
        pe_count = n * n if top in ("systolic_array_64x64", "stream_pipeline") else "NA"

        rdir = sub / "reports"
        area = parse_area(rdir / "area.rpt", top)
        wns = parse_wns_ps(rdir / "qor.rpt", rdir / "timing.rpt")
        power = parse_power(rdir / "power.rpt")

        rows.append({
            "tag": tag,
            "top": top,
            "N": n,
            "PEs": pe_count,
            "NUM_RD_PORTS": nrd,
            "cells": area["cells"],
            "cell_area_um2": area["cell_area_um2"],
            "total_area_um2": area["total_area_um2"],
            "WNS_ps": wns,
            "leakage_W": power["leakage_W"],
            "internal_W": power["internal_W"],
            "switching_W": power["switching_W"],
            "total_W": power["total_W"],
        })

    if not rows:
        print(f"WARNING: no subdirectories in {root}")

    fieldnames = ["tag", "top", "N", "PEs", "NUM_RD_PORTS",
                  "cells", "cell_area_um2", "total_area_um2", "WNS_ps",
                  "leakage_W", "internal_W", "switching_W", "total_W"]
    with open(args.out, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)

    print(f"Wrote {len(rows)} rows to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
