/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module double_buffer_ctrl(clk, rst_n, swap, active_buf, compute_base, load_base);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  output active_buf;
  wire active_buf;
  input clk;
  wire clk;
  output [15:0] compute_base;
  wire [15:0] compute_base;
  output [15:0] load_base;
  wire [15:0] load_base;
  input rst_n;
  wire rst_n;
  input swap;
  wire swap;
  sky130_fd_sc_hd__clkinv_1 _4_ (
    .A(active_buf),
    .Y(load_base[12])
  );
  sky130_fd_sc_hd__clkinv_1 _5_ (
    .A(swap),
    .Y(_1_)
  );
  sky130_fd_sc_hd__nand2_1 _6_ (
    .A(_1_),
    .B(active_buf),
    .Y(_2_)
  );
  sky130_fd_sc_hd__or2b_2 _7_ (
    .A(active_buf),
    .B_N(swap),
    .X(_3_)
  );
  sky130_fd_sc_hd__nand2_1 _8_ (
    .A(_2_),
    .B(_3_),
    .Y(_0_)
  );
  sky130_fd_sc_hd__dfrtp_1 _9_ (
    .CLK(clk),
    .D(_0_),
    .Q(active_buf),
    .RESET_B(rst_n)
  );
  assign compute_base = { 3'h0, active_buf, 12'h000 };
  assign { load_base[15:13], load_base[11:0] } = 15'h0000;
endmodule
