/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module mode_decoder(cmd, cmd_valid, mode, fused_sel, dim_m, dim_n, dim_k, addr_a, addr_b, addr_out, valid);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  output [15:0] addr_a;
  wire [15:0] addr_a;
  output [15:0] addr_b;
  wire [15:0] addr_b;
  output [15:0] addr_out;
  wire [15:0] addr_out;
  input [98:0] cmd;
  wire [98:0] cmd;
  input cmd_valid;
  wire cmd_valid;
  output [7:0] dim_k;
  wire [7:0] dim_k;
  output [7:0] dim_m;
  wire [7:0] dim_m;
  output [7:0] dim_n;
  wire [7:0] dim_n;
  output [2:0] fused_sel;
  wire [2:0] fused_sel;
  output [2:0] mode;
  wire [2:0] mode;
  output valid;
  wire valid;
  sky130_fd_sc_hd__nor2_1 _4_ (
    .A(cmd[0]),
    .B(cmd[2]),
    .Y(fused_sel[0])
  );
  sky130_fd_sc_hd__clkinv_1 _5_ (
    .A(cmd[2]),
    .Y(_1_)
  );
  sky130_fd_sc_hd__nand3b_1 _6_ (
    .A_N(cmd[0]),
    .B(_1_),
    .C(cmd[1]),
    .Y(_2_)
  );
  sky130_fd_sc_hd__clkinv_1 _7_ (
    .A(cmd[1]),
    .Y(_3_)
  );
  sky130_fd_sc_hd__nand3_1 _8_ (
    .A(_3_),
    .B(_1_),
    .C(cmd[0]),
    .Y(_0_)
  );
  sky130_fd_sc_hd__nand2_1 _9_ (
    .A(_2_),
    .B(_0_),
    .Y(fused_sel[1])
  );
  assign addr_a = cmd[18:3];
  assign addr_b = cmd[34:19];
  assign addr_out = cmd[66:51];
  assign dim_k = cmd[90:83];
  assign dim_m = cmd[74:67];
  assign dim_n = cmd[82:75];
  assign fused_sel[2] = 1'h0;
  assign mode = cmd[2:0];
  assign valid = cmd_valid;
endmodule
