/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module gelu_lut(clk, addr, data);
  wire [31:0] _00_;
  input [7:0] addr;
  wire [7:0] addr;
  input clk;
  wire clk;
  output [31:0] data;
  wire [31:0] data;
  reg [31:0] lut_mem [255:0];
  initial begin
    lut_mem[0] = 32'd4294901804;
    lut_mem[1] = 32'd4294901807;
    lut_mem[2] = 32'd4294901810;
    lut_mem[3] = 32'd4294901813;
    lut_mem[4] = 32'd4294901816;
    lut_mem[5] = 32'd4294901820;
    lut_mem[6] = 32'd4294901824;
    lut_mem[7] = 32'd4294901828;
    lut_mem[8] = 32'd4294901833;
    lut_mem[9] = 32'd4294901837;
    lut_mem[10] = 32'd4294901842;
    lut_mem[11] = 32'd4294901848;
    lut_mem[12] = 32'd4294901853;
    lut_mem[13] = 32'd4294901859;
    lut_mem[14] = 32'd4294901866;
    lut_mem[15] = 32'd4294901873;
    lut_mem[16] = 32'd4294901880;
    lut_mem[17] = 32'd4294901888;
    lut_mem[18] = 32'd4294901896;
    lut_mem[19] = 32'd4294901905;
    lut_mem[20] = 32'd4294901914;
    lut_mem[21] = 32'd4294901924;
    lut_mem[22] = 32'd4294901935;
    lut_mem[23] = 32'd4294901946;
    lut_mem[24] = 32'd4294901958;
    lut_mem[25] = 32'd4294901971;
    lut_mem[26] = 32'd4294901984;
    lut_mem[27] = 32'd4294901999;
    lut_mem[28] = 32'd4294902014;
    lut_mem[29] = 32'd4294902031;
    lut_mem[30] = 32'd4294902048;
    lut_mem[31] = 32'd4294902067;
    lut_mem[32] = 32'd4294902087;
    lut_mem[33] = 32'd4294902108;
    lut_mem[34] = 32'd4294902130;
    lut_mem[35] = 32'd4294902154;
    lut_mem[36] = 32'd4294902180;
    lut_mem[37] = 32'd4294902207;
    lut_mem[38] = 32'd4294902235;
    lut_mem[39] = 32'd4294902266;
    lut_mem[40] = 32'd4294902299;
    lut_mem[41] = 32'd4294902333;
    lut_mem[42] = 32'd4294902370;
    lut_mem[43] = 32'd4294902410;
    lut_mem[44] = 32'd4294902452;
    lut_mem[45] = 32'd4294902496;
    lut_mem[46] = 32'd4294902544;
    lut_mem[47] = 32'd4294902594;
    lut_mem[48] = 32'd4294902648;
    lut_mem[49] = 32'd4294902705;
    lut_mem[50] = 32'd4294902765;
    lut_mem[51] = 32'd4294902830;
    lut_mem[52] = 32'd4294902899;
    lut_mem[53] = 32'd4294902972;
    lut_mem[54] = 32'd4294903049;
    lut_mem[55] = 32'd4294903132;
    lut_mem[56] = 32'd4294903220;
    lut_mem[57] = 32'd4294903313;
    lut_mem[58] = 32'd4294903412;
    lut_mem[59] = 32'd4294903518;
    lut_mem[60] = 32'd4294903630;
    lut_mem[61] = 32'd4294903750;
    lut_mem[62] = 32'd4294903876;
    lut_mem[63] = 32'd4294904011;
    lut_mem[64] = 32'd4294904154;
    lut_mem[65] = 32'd4294904306;
    lut_mem[66] = 32'd4294904468;
    lut_mem[67] = 32'd4294904639;
    lut_mem[68] = 32'd4294904821;
    lut_mem[69] = 32'd4294905014;
    lut_mem[70] = 32'd4294905220;
    lut_mem[71] = 32'd4294905437;
    lut_mem[72] = 32'd4294905668;
    lut_mem[73] = 32'd4294905913;
    lut_mem[74] = 32'd4294906173;
    lut_mem[75] = 32'd4294906449;
    lut_mem[76] = 32'd4294906741;
    lut_mem[77] = 32'd4294907051;
    lut_mem[78] = 32'd4294907378;
    lut_mem[79] = 32'd4294907726;
    lut_mem[80] = 32'd4294908093;
    lut_mem[81] = 32'd4294908482;
    lut_mem[82] = 32'd4294908894;
    lut_mem[83] = 32'd4294909329;
    lut_mem[84] = 32'd4294909789;
    lut_mem[85] = 32'd4294910276;
    lut_mem[86] = 32'd4294910789;
    lut_mem[87] = 32'd4294911331;
    lut_mem[88] = 32'd4294911903;
    lut_mem[89] = 32'd4294912506;
    lut_mem[90] = 32'd4294913141;
    lut_mem[91] = 32'd4294913811;
    lut_mem[92] = 32'd4294914515;
    lut_mem[93] = 32'd4294915256;
    lut_mem[94] = 32'd4294916035;
    lut_mem[95] = 32'd4294916852;
    lut_mem[96] = 32'd4294917711;
    lut_mem[97] = 32'd4294918611;
    lut_mem[98] = 32'd4294919554;
    lut_mem[99] = 32'd4294920541;
    lut_mem[100] = 32'd4294921574;
    lut_mem[101] = 32'd4294922652;
    lut_mem[102] = 32'd4294923778;
    lut_mem[103] = 32'd4294924951;
    lut_mem[104] = 32'd4294926173;
    lut_mem[105] = 32'd4294927444;
    lut_mem[106] = 32'd4294928765;
    lut_mem[107] = 32'd4294930135;
    lut_mem[108] = 32'd4294931555;
    lut_mem[109] = 32'd4294933024;
    lut_mem[110] = 32'd4294934542;
    lut_mem[111] = 32'd4294936109;
    lut_mem[112] = 32'd4294937723;
    lut_mem[113] = 32'd4294939383;
    lut_mem[114] = 32'd4294941088;
    lut_mem[115] = 32'd4294942837;
    lut_mem[116] = 32'd4294944627;
    lut_mem[117] = 32'd4294946456;
    lut_mem[118] = 32'd4294948322;
    lut_mem[119] = 32'd4294950223;
    lut_mem[120] = 32'd4294952154;
    lut_mem[121] = 32'd4294954114;
    lut_mem[122] = 32'd4294956099;
    lut_mem[123] = 32'd4294958105;
    lut_mem[124] = 32'd4294960129;
    lut_mem[125] = 32'd4294962166;
    lut_mem[126] = 32'd4294964214;
    lut_mem[127] = 32'd4294966268;
    lut_mem[128] = 32'd1028;
    lut_mem[129] = 32'd3082;
    lut_mem[130] = 32'd5130;
    lut_mem[131] = 32'd7167;
    lut_mem[132] = 32'd9191;
    lut_mem[133] = 32'd11197;
    lut_mem[134] = 32'd13182;
    lut_mem[135] = 32'd15142;
    lut_mem[136] = 32'd17073;
    lut_mem[137] = 32'd18974;
    lut_mem[138] = 32'd20840;
    lut_mem[139] = 32'd22669;
    lut_mem[140] = 32'd24459;
    lut_mem[141] = 32'd26208;
    lut_mem[142] = 32'd27913;
    lut_mem[143] = 32'd29573;
    lut_mem[144] = 32'd31187;
    lut_mem[145] = 32'd32754;
    lut_mem[146] = 32'd34272;
    lut_mem[147] = 32'd35741;
    lut_mem[148] = 32'd37161;
    lut_mem[149] = 32'd38531;
    lut_mem[150] = 32'd39852;
    lut_mem[151] = 32'd41123;
    lut_mem[152] = 32'd42345;
    lut_mem[153] = 32'd43518;
    lut_mem[154] = 32'd44644;
    lut_mem[155] = 32'd45722;
    lut_mem[156] = 32'd46755;
    lut_mem[157] = 32'd47742;
    lut_mem[158] = 32'd48685;
    lut_mem[159] = 32'd49585;
    lut_mem[160] = 32'd50444;
    lut_mem[161] = 32'd51261;
    lut_mem[162] = 32'd52040;
    lut_mem[163] = 32'd52781;
    lut_mem[164] = 32'd53485;
    lut_mem[165] = 32'd54155;
    lut_mem[166] = 32'd54790;
    lut_mem[167] = 32'd55393;
    lut_mem[168] = 32'd55965;
    lut_mem[169] = 32'd56507;
    lut_mem[170] = 32'd57020;
    lut_mem[171] = 32'd57507;
    lut_mem[172] = 32'd57967;
    lut_mem[173] = 32'd58402;
    lut_mem[174] = 32'd58814;
    lut_mem[175] = 32'd59203;
    lut_mem[176] = 32'd59570;
    lut_mem[177] = 32'd59918;
    lut_mem[178] = 32'd60245;
    lut_mem[179] = 32'd60555;
    lut_mem[180] = 32'd60847;
    lut_mem[181] = 32'd61123;
    lut_mem[182] = 32'd61383;
    lut_mem[183] = 32'd61628;
    lut_mem[184] = 32'd61859;
    lut_mem[185] = 32'd62076;
    lut_mem[186] = 32'd62282;
    lut_mem[187] = 32'd62475;
    lut_mem[188] = 32'd62657;
    lut_mem[189] = 32'd62828;
    lut_mem[190] = 32'd62990;
    lut_mem[191] = 32'd63142;
    lut_mem[192] = 32'd63285;
    lut_mem[193] = 32'd63420;
    lut_mem[194] = 32'd63546;
    lut_mem[195] = 32'd63666;
    lut_mem[196] = 32'd63778;
    lut_mem[197] = 32'd63884;
    lut_mem[198] = 32'd63983;
    lut_mem[199] = 32'd64076;
    lut_mem[200] = 32'd64164;
    lut_mem[201] = 32'd64247;
    lut_mem[202] = 32'd64324;
    lut_mem[203] = 32'd64397;
    lut_mem[204] = 32'd64466;
    lut_mem[205] = 32'd64531;
    lut_mem[206] = 32'd64591;
    lut_mem[207] = 32'd64648;
    lut_mem[208] = 32'd64702;
    lut_mem[209] = 32'd64752;
    lut_mem[210] = 32'd64800;
    lut_mem[211] = 32'd64844;
    lut_mem[212] = 32'd64886;
    lut_mem[213] = 32'd64926;
    lut_mem[214] = 32'd64963;
    lut_mem[215] = 32'd64997;
    lut_mem[216] = 32'd65030;
    lut_mem[217] = 32'd65061;
    lut_mem[218] = 32'd65089;
    lut_mem[219] = 32'd65116;
    lut_mem[220] = 32'd65142;
    lut_mem[221] = 32'd65166;
    lut_mem[222] = 32'd65188;
    lut_mem[223] = 32'd65209;
    lut_mem[224] = 32'd65229;
    lut_mem[225] = 32'd65248;
    lut_mem[226] = 32'd65265;
    lut_mem[227] = 32'd65282;
    lut_mem[228] = 32'd65297;
    lut_mem[229] = 32'd65312;
    lut_mem[230] = 32'd65325;
    lut_mem[231] = 32'd65338;
    lut_mem[232] = 32'd65350;
    lut_mem[233] = 32'd65361;
    lut_mem[234] = 32'd65372;
    lut_mem[235] = 32'd65382;
    lut_mem[236] = 32'd65391;
    lut_mem[237] = 32'd65400;
    lut_mem[238] = 32'd65408;
    lut_mem[239] = 32'd65416;
    lut_mem[240] = 32'd65423;
    lut_mem[241] = 32'd65430;
    lut_mem[242] = 32'd65437;
    lut_mem[243] = 32'd65443;
    lut_mem[244] = 32'd65448;
    lut_mem[245] = 32'd65454;
    lut_mem[246] = 32'd65459;
    lut_mem[247] = 32'd65463;
    lut_mem[248] = 32'd65468;
    lut_mem[249] = 32'd65472;
    lut_mem[250] = 32'd65476;
    lut_mem[251] = 32'd65480;
    lut_mem[252] = 32'd65483;
    lut_mem[253] = 32'd65486;
    lut_mem[254] = 32'd65489;
    lut_mem[255] = 32'd65492;
  end
  assign _00_ = lut_mem[addr];
  sky130_fd_sc_hd__dfxtp_1 _01_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(data[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _02_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(data[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _03_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(data[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _04_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(data[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _05_ (
    .CLK(clk),
    .D(_00_[4]),
    .Q(data[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _06_ (
    .CLK(clk),
    .D(_00_[5]),
    .Q(data[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _07_ (
    .CLK(clk),
    .D(_00_[6]),
    .Q(data[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _08_ (
    .CLK(clk),
    .D(_00_[7]),
    .Q(data[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _09_ (
    .CLK(clk),
    .D(_00_[8]),
    .Q(data[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _10_ (
    .CLK(clk),
    .D(_00_[9]),
    .Q(data[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _11_ (
    .CLK(clk),
    .D(_00_[10]),
    .Q(data[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _12_ (
    .CLK(clk),
    .D(_00_[11]),
    .Q(data[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _13_ (
    .CLK(clk),
    .D(_00_[12]),
    .Q(data[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _14_ (
    .CLK(clk),
    .D(_00_[13]),
    .Q(data[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _15_ (
    .CLK(clk),
    .D(_00_[14]),
    .Q(data[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _16_ (
    .CLK(clk),
    .D(_00_[15]),
    .Q(data[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _17_ (
    .CLK(clk),
    .D(_00_[16]),
    .Q(data[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _18_ (
    .CLK(clk),
    .D(_00_[17]),
    .Q(data[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _19_ (
    .CLK(clk),
    .D(_00_[18]),
    .Q(data[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _20_ (
    .CLK(clk),
    .D(_00_[19]),
    .Q(data[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _21_ (
    .CLK(clk),
    .D(_00_[20]),
    .Q(data[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _22_ (
    .CLK(clk),
    .D(_00_[21]),
    .Q(data[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _23_ (
    .CLK(clk),
    .D(_00_[22]),
    .Q(data[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _24_ (
    .CLK(clk),
    .D(_00_[23]),
    .Q(data[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _25_ (
    .CLK(clk),
    .D(_00_[24]),
    .Q(data[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _26_ (
    .CLK(clk),
    .D(_00_[25]),
    .Q(data[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _27_ (
    .CLK(clk),
    .D(_00_[26]),
    .Q(data[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _28_ (
    .CLK(clk),
    .D(_00_[27]),
    .Q(data[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _29_ (
    .CLK(clk),
    .D(_00_[28]),
    .Q(data[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _30_ (
    .CLK(clk),
    .D(_00_[29]),
    .Q(data[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _31_ (
    .CLK(clk),
    .D(_00_[30]),
    .Q(data[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _32_ (
    .CLK(clk),
    .D(_00_[31]),
    .Q(data[31])
  );
endmodule
