
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point clear clear -type PI PI
add mapped point array_active array_active -type PI PI
add mapped point array_stall array_stall -type PI PI
add mapped point tile_complete tile_complete -type PI PI

//output ports
add mapped point active_cycles[31] active_cycles[31] -type PO PO
add mapped point active_cycles[30] active_cycles[30] -type PO PO
add mapped point active_cycles[29] active_cycles[29] -type PO PO
add mapped point active_cycles[28] active_cycles[28] -type PO PO
add mapped point active_cycles[27] active_cycles[27] -type PO PO
add mapped point active_cycles[26] active_cycles[26] -type PO PO
add mapped point active_cycles[25] active_cycles[25] -type PO PO
add mapped point active_cycles[24] active_cycles[24] -type PO PO
add mapped point active_cycles[23] active_cycles[23] -type PO PO
add mapped point active_cycles[22] active_cycles[22] -type PO PO
add mapped point active_cycles[21] active_cycles[21] -type PO PO
add mapped point active_cycles[20] active_cycles[20] -type PO PO
add mapped point active_cycles[19] active_cycles[19] -type PO PO
add mapped point active_cycles[18] active_cycles[18] -type PO PO
add mapped point active_cycles[17] active_cycles[17] -type PO PO
add mapped point active_cycles[16] active_cycles[16] -type PO PO
add mapped point active_cycles[15] active_cycles[15] -type PO PO
add mapped point active_cycles[14] active_cycles[14] -type PO PO
add mapped point active_cycles[13] active_cycles[13] -type PO PO
add mapped point active_cycles[12] active_cycles[12] -type PO PO
add mapped point active_cycles[11] active_cycles[11] -type PO PO
add mapped point active_cycles[10] active_cycles[10] -type PO PO
add mapped point active_cycles[9] active_cycles[9] -type PO PO
add mapped point active_cycles[8] active_cycles[8] -type PO PO
add mapped point active_cycles[7] active_cycles[7] -type PO PO
add mapped point active_cycles[6] active_cycles[6] -type PO PO
add mapped point active_cycles[5] active_cycles[5] -type PO PO
add mapped point active_cycles[4] active_cycles[4] -type PO PO
add mapped point active_cycles[3] active_cycles[3] -type PO PO
add mapped point active_cycles[2] active_cycles[2] -type PO PO
add mapped point active_cycles[1] active_cycles[1] -type PO PO
add mapped point active_cycles[0] active_cycles[0] -type PO PO
add mapped point stall_cycles[31] stall_cycles[31] -type PO PO
add mapped point stall_cycles[30] stall_cycles[30] -type PO PO
add mapped point stall_cycles[29] stall_cycles[29] -type PO PO
add mapped point stall_cycles[28] stall_cycles[28] -type PO PO
add mapped point stall_cycles[27] stall_cycles[27] -type PO PO
add mapped point stall_cycles[26] stall_cycles[26] -type PO PO
add mapped point stall_cycles[25] stall_cycles[25] -type PO PO
add mapped point stall_cycles[24] stall_cycles[24] -type PO PO
add mapped point stall_cycles[23] stall_cycles[23] -type PO PO
add mapped point stall_cycles[22] stall_cycles[22] -type PO PO
add mapped point stall_cycles[21] stall_cycles[21] -type PO PO
add mapped point stall_cycles[20] stall_cycles[20] -type PO PO
add mapped point stall_cycles[19] stall_cycles[19] -type PO PO
add mapped point stall_cycles[18] stall_cycles[18] -type PO PO
add mapped point stall_cycles[17] stall_cycles[17] -type PO PO
add mapped point stall_cycles[16] stall_cycles[16] -type PO PO
add mapped point stall_cycles[15] stall_cycles[15] -type PO PO
add mapped point stall_cycles[14] stall_cycles[14] -type PO PO
add mapped point stall_cycles[13] stall_cycles[13] -type PO PO
add mapped point stall_cycles[12] stall_cycles[12] -type PO PO
add mapped point stall_cycles[11] stall_cycles[11] -type PO PO
add mapped point stall_cycles[10] stall_cycles[10] -type PO PO
add mapped point stall_cycles[9] stall_cycles[9] -type PO PO
add mapped point stall_cycles[8] stall_cycles[8] -type PO PO
add mapped point stall_cycles[7] stall_cycles[7] -type PO PO
add mapped point stall_cycles[6] stall_cycles[6] -type PO PO
add mapped point stall_cycles[5] stall_cycles[5] -type PO PO
add mapped point stall_cycles[4] stall_cycles[4] -type PO PO
add mapped point stall_cycles[3] stall_cycles[3] -type PO PO
add mapped point stall_cycles[2] stall_cycles[2] -type PO PO
add mapped point stall_cycles[1] stall_cycles[1] -type PO PO
add mapped point stall_cycles[0] stall_cycles[0] -type PO PO
add mapped point total_cycles[31] total_cycles[31] -type PO PO
add mapped point total_cycles[30] total_cycles[30] -type PO PO
add mapped point total_cycles[29] total_cycles[29] -type PO PO
add mapped point total_cycles[28] total_cycles[28] -type PO PO
add mapped point total_cycles[27] total_cycles[27] -type PO PO
add mapped point total_cycles[26] total_cycles[26] -type PO PO
add mapped point total_cycles[25] total_cycles[25] -type PO PO
add mapped point total_cycles[24] total_cycles[24] -type PO PO
add mapped point total_cycles[23] total_cycles[23] -type PO PO
add mapped point total_cycles[22] total_cycles[22] -type PO PO
add mapped point total_cycles[21] total_cycles[21] -type PO PO
add mapped point total_cycles[20] total_cycles[20] -type PO PO
add mapped point total_cycles[19] total_cycles[19] -type PO PO
add mapped point total_cycles[18] total_cycles[18] -type PO PO
add mapped point total_cycles[17] total_cycles[17] -type PO PO
add mapped point total_cycles[16] total_cycles[16] -type PO PO
add mapped point total_cycles[15] total_cycles[15] -type PO PO
add mapped point total_cycles[14] total_cycles[14] -type PO PO
add mapped point total_cycles[13] total_cycles[13] -type PO PO
add mapped point total_cycles[12] total_cycles[12] -type PO PO
add mapped point total_cycles[11] total_cycles[11] -type PO PO
add mapped point total_cycles[10] total_cycles[10] -type PO PO
add mapped point total_cycles[9] total_cycles[9] -type PO PO
add mapped point total_cycles[8] total_cycles[8] -type PO PO
add mapped point total_cycles[7] total_cycles[7] -type PO PO
add mapped point total_cycles[6] total_cycles[6] -type PO PO
add mapped point total_cycles[5] total_cycles[5] -type PO PO
add mapped point total_cycles[4] total_cycles[4] -type PO PO
add mapped point total_cycles[3] total_cycles[3] -type PO PO
add mapped point total_cycles[2] total_cycles[2] -type PO PO
add mapped point total_cycles[1] total_cycles[1] -type PO PO
add mapped point total_cycles[0] total_cycles[0] -type PO PO
add mapped point tiles_completed[31] tiles_completed[31] -type PO PO
add mapped point tiles_completed[30] tiles_completed[30] -type PO PO
add mapped point tiles_completed[29] tiles_completed[29] -type PO PO
add mapped point tiles_completed[28] tiles_completed[28] -type PO PO
add mapped point tiles_completed[27] tiles_completed[27] -type PO PO
add mapped point tiles_completed[26] tiles_completed[26] -type PO PO
add mapped point tiles_completed[25] tiles_completed[25] -type PO PO
add mapped point tiles_completed[24] tiles_completed[24] -type PO PO
add mapped point tiles_completed[23] tiles_completed[23] -type PO PO
add mapped point tiles_completed[22] tiles_completed[22] -type PO PO
add mapped point tiles_completed[21] tiles_completed[21] -type PO PO
add mapped point tiles_completed[20] tiles_completed[20] -type PO PO
add mapped point tiles_completed[19] tiles_completed[19] -type PO PO
add mapped point tiles_completed[18] tiles_completed[18] -type PO PO
add mapped point tiles_completed[17] tiles_completed[17] -type PO PO
add mapped point tiles_completed[16] tiles_completed[16] -type PO PO
add mapped point tiles_completed[15] tiles_completed[15] -type PO PO
add mapped point tiles_completed[14] tiles_completed[14] -type PO PO
add mapped point tiles_completed[13] tiles_completed[13] -type PO PO
add mapped point tiles_completed[12] tiles_completed[12] -type PO PO
add mapped point tiles_completed[11] tiles_completed[11] -type PO PO
add mapped point tiles_completed[10] tiles_completed[10] -type PO PO
add mapped point tiles_completed[9] tiles_completed[9] -type PO PO
add mapped point tiles_completed[8] tiles_completed[8] -type PO PO
add mapped point tiles_completed[7] tiles_completed[7] -type PO PO
add mapped point tiles_completed[6] tiles_completed[6] -type PO PO
add mapped point tiles_completed[5] tiles_completed[5] -type PO PO
add mapped point tiles_completed[4] tiles_completed[4] -type PO PO
add mapped point tiles_completed[3] tiles_completed[3] -type PO PO
add mapped point tiles_completed[2] tiles_completed[2] -type PO PO
add mapped point tiles_completed[1] tiles_completed[1] -type PO PO
add mapped point tiles_completed[0] tiles_completed[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point active_cycles[0]/q active_cycles_reg[0]/Q  -type DFF DFF
add mapped point active_cycles[1]/q active_cycles_reg[1]/Q  -type DFF DFF
add mapped point active_cycles[2]/q active_cycles_reg[2]/Q  -type DFF DFF
add mapped point active_cycles[3]/q active_cycles_reg[3]/Q  -type DFF DFF
add mapped point active_cycles[4]/q active_cycles_reg[4]/Q  -type DFF DFF
add mapped point active_cycles[5]/q active_cycles_reg[5]/Q  -type DFF DFF
add mapped point active_cycles[6]/q active_cycles_reg[6]/Q  -type DFF DFF
add mapped point active_cycles[7]/q active_cycles_reg[7]/Q  -type DFF DFF
add mapped point active_cycles[8]/q active_cycles_reg[8]/Q  -type DFF DFF
add mapped point active_cycles[9]/q active_cycles_reg[9]/Q  -type DFF DFF
add mapped point active_cycles[10]/q active_cycles_reg[10]/Q  -type DFF DFF
add mapped point active_cycles[11]/q active_cycles_reg[11]/Q  -type DFF DFF
add mapped point active_cycles[12]/q active_cycles_reg[12]/Q  -type DFF DFF
add mapped point active_cycles[13]/q active_cycles_reg[13]/Q  -type DFF DFF
add mapped point active_cycles[14]/q active_cycles_reg[14]/Q  -type DFF DFF
add mapped point active_cycles[15]/q active_cycles_reg[15]/Q  -type DFF DFF
add mapped point active_cycles[16]/q active_cycles_reg[16]/Q  -type DFF DFF
add mapped point active_cycles[17]/q active_cycles_reg[17]/Q  -type DFF DFF
add mapped point active_cycles[18]/q active_cycles_reg[18]/Q  -type DFF DFF
add mapped point active_cycles[19]/q active_cycles_reg[19]/Q  -type DFF DFF
add mapped point active_cycles[20]/q active_cycles_reg[20]/Q  -type DFF DFF
add mapped point active_cycles[21]/q active_cycles_reg[21]/Q  -type DFF DFF
add mapped point active_cycles[22]/q active_cycles_reg[22]/Q  -type DFF DFF
add mapped point active_cycles[23]/q active_cycles_reg[23]/Q  -type DFF DFF
add mapped point active_cycles[24]/q active_cycles_reg[24]/Q  -type DFF DFF
add mapped point active_cycles[25]/q active_cycles_reg[25]/Q  -type DFF DFF
add mapped point active_cycles[26]/q active_cycles_reg[26]/Q  -type DFF DFF
add mapped point active_cycles[27]/q active_cycles_reg[27]/Q  -type DFF DFF
add mapped point active_cycles[28]/q active_cycles_reg[28]/Q  -type DFF DFF
add mapped point active_cycles[29]/q active_cycles_reg[29]/Q  -type DFF DFF
add mapped point active_cycles[30]/q active_cycles_reg[30]/Q  -type DFF DFF
add mapped point active_cycles[31]/q active_cycles_reg[31]/Q  -type DFF DFF
add mapped point stall_cycles[0]/q stall_cycles_reg[0]/Q  -type DFF DFF
add mapped point stall_cycles[1]/q stall_cycles_reg[1]/Q  -type DFF DFF
add mapped point stall_cycles[2]/q stall_cycles_reg[2]/Q  -type DFF DFF
add mapped point stall_cycles[3]/q stall_cycles_reg[3]/Q  -type DFF DFF
add mapped point stall_cycles[4]/q stall_cycles_reg[4]/Q  -type DFF DFF
add mapped point stall_cycles[5]/q stall_cycles_reg[5]/Q  -type DFF DFF
add mapped point stall_cycles[6]/q stall_cycles_reg[6]/Q  -type DFF DFF
add mapped point stall_cycles[7]/q stall_cycles_reg[7]/Q  -type DFF DFF
add mapped point stall_cycles[8]/q stall_cycles_reg[8]/Q  -type DFF DFF
add mapped point stall_cycles[9]/q stall_cycles_reg[9]/Q  -type DFF DFF
add mapped point stall_cycles[10]/q stall_cycles_reg[10]/Q  -type DFF DFF
add mapped point stall_cycles[11]/q stall_cycles_reg[11]/Q  -type DFF DFF
add mapped point stall_cycles[12]/q stall_cycles_reg[12]/Q  -type DFF DFF
add mapped point stall_cycles[13]/q stall_cycles_reg[13]/Q  -type DFF DFF
add mapped point stall_cycles[14]/q stall_cycles_reg[14]/Q  -type DFF DFF
add mapped point stall_cycles[15]/q stall_cycles_reg[15]/Q  -type DFF DFF
add mapped point stall_cycles[16]/q stall_cycles_reg[16]/Q  -type DFF DFF
add mapped point stall_cycles[17]/q stall_cycles_reg[17]/Q  -type DFF DFF
add mapped point stall_cycles[18]/q stall_cycles_reg[18]/Q  -type DFF DFF
add mapped point stall_cycles[19]/q stall_cycles_reg[19]/Q  -type DFF DFF
add mapped point stall_cycles[20]/q stall_cycles_reg[20]/Q  -type DFF DFF
add mapped point stall_cycles[21]/q stall_cycles_reg[21]/Q  -type DFF DFF
add mapped point stall_cycles[22]/q stall_cycles_reg[22]/Q  -type DFF DFF
add mapped point stall_cycles[23]/q stall_cycles_reg[23]/Q  -type DFF DFF
add mapped point stall_cycles[24]/q stall_cycles_reg[24]/Q  -type DFF DFF
add mapped point stall_cycles[25]/q stall_cycles_reg[25]/Q  -type DFF DFF
add mapped point stall_cycles[26]/q stall_cycles_reg[26]/Q  -type DFF DFF
add mapped point stall_cycles[27]/q stall_cycles_reg[27]/Q  -type DFF DFF
add mapped point stall_cycles[28]/q stall_cycles_reg[28]/Q  -type DFF DFF
add mapped point stall_cycles[29]/q stall_cycles_reg[29]/Q  -type DFF DFF
add mapped point stall_cycles[30]/q stall_cycles_reg[30]/Q  -type DFF DFF
add mapped point stall_cycles[31]/q stall_cycles_reg[31]/Q  -type DFF DFF
add mapped point tiles_completed[0]/q tiles_completed_reg[0]/Q  -type DFF DFF
add mapped point tiles_completed[1]/q tiles_completed_reg[1]/Q  -type DFF DFF
add mapped point tiles_completed[2]/q tiles_completed_reg[2]/Q  -type DFF DFF
add mapped point tiles_completed[3]/q tiles_completed_reg[3]/Q  -type DFF DFF
add mapped point tiles_completed[4]/q tiles_completed_reg[4]/Q  -type DFF DFF
add mapped point tiles_completed[5]/q tiles_completed_reg[5]/Q  -type DFF DFF
add mapped point tiles_completed[6]/q tiles_completed_reg[6]/Q  -type DFF DFF
add mapped point tiles_completed[7]/q tiles_completed_reg[7]/Q  -type DFF DFF
add mapped point tiles_completed[8]/q tiles_completed_reg[8]/Q  -type DFF DFF
add mapped point tiles_completed[9]/q tiles_completed_reg[9]/Q  -type DFF DFF
add mapped point tiles_completed[10]/q tiles_completed_reg[10]/Q  -type DFF DFF
add mapped point tiles_completed[11]/q tiles_completed_reg[11]/Q  -type DFF DFF
add mapped point tiles_completed[12]/q tiles_completed_reg[12]/Q  -type DFF DFF
add mapped point tiles_completed[13]/q tiles_completed_reg[13]/Q  -type DFF DFF
add mapped point tiles_completed[14]/q tiles_completed_reg[14]/Q  -type DFF DFF
add mapped point tiles_completed[15]/q tiles_completed_reg[15]/Q  -type DFF DFF
add mapped point tiles_completed[16]/q tiles_completed_reg[16]/Q  -type DFF DFF
add mapped point tiles_completed[17]/q tiles_completed_reg[17]/Q  -type DFF DFF
add mapped point tiles_completed[18]/q tiles_completed_reg[18]/Q  -type DFF DFF
add mapped point tiles_completed[19]/q tiles_completed_reg[19]/Q  -type DFF DFF
add mapped point tiles_completed[20]/q tiles_completed_reg[20]/Q  -type DFF DFF
add mapped point tiles_completed[21]/q tiles_completed_reg[21]/Q  -type DFF DFF
add mapped point tiles_completed[22]/q tiles_completed_reg[22]/Q  -type DFF DFF
add mapped point tiles_completed[23]/q tiles_completed_reg[23]/Q  -type DFF DFF
add mapped point tiles_completed[24]/q tiles_completed_reg[24]/Q  -type DFF DFF
add mapped point tiles_completed[25]/q tiles_completed_reg[25]/Q  -type DFF DFF
add mapped point tiles_completed[26]/q tiles_completed_reg[26]/Q  -type DFF DFF
add mapped point tiles_completed[27]/q tiles_completed_reg[27]/Q  -type DFF DFF
add mapped point tiles_completed[28]/q tiles_completed_reg[28]/Q  -type DFF DFF
add mapped point tiles_completed[29]/q tiles_completed_reg[29]/Q  -type DFF DFF
add mapped point tiles_completed[30]/q tiles_completed_reg[30]/Q  -type DFF DFF
add mapped point tiles_completed[31]/q tiles_completed_reg[31]/Q  -type DFF DFF
add mapped point total_cycles[0]/q total_cycles_reg[0]/Q  -type DFF DFF
add mapped point total_cycles[1]/q total_cycles_reg[1]/Q  -type DFF DFF
add mapped point total_cycles[2]/q total_cycles_reg[2]/Q  -type DFF DFF
add mapped point total_cycles[3]/q total_cycles_reg[3]/Q  -type DFF DFF
add mapped point total_cycles[4]/q total_cycles_reg[4]/Q  -type DFF DFF
add mapped point total_cycles[5]/q total_cycles_reg[5]/Q  -type DFF DFF
add mapped point total_cycles[6]/q total_cycles_reg[6]/Q  -type DFF DFF
add mapped point total_cycles[7]/q total_cycles_reg[7]/Q  -type DFF DFF
add mapped point total_cycles[8]/q total_cycles_reg[8]/Q  -type DFF DFF
add mapped point total_cycles[9]/q total_cycles_reg[9]/Q  -type DFF DFF
add mapped point total_cycles[10]/q total_cycles_reg[10]/Q  -type DFF DFF
add mapped point total_cycles[11]/q total_cycles_reg[11]/Q  -type DFF DFF
add mapped point total_cycles[12]/q total_cycles_reg[12]/Q  -type DFF DFF
add mapped point total_cycles[13]/q total_cycles_reg[13]/Q  -type DFF DFF
add mapped point total_cycles[14]/q total_cycles_reg[14]/Q  -type DFF DFF
add mapped point total_cycles[15]/q total_cycles_reg[15]/Q  -type DFF DFF
add mapped point total_cycles[16]/q total_cycles_reg[16]/Q  -type DFF DFF
add mapped point total_cycles[17]/q total_cycles_reg[17]/Q  -type DFF DFF
add mapped point total_cycles[18]/q total_cycles_reg[18]/Q  -type DFF DFF
add mapped point total_cycles[19]/q total_cycles_reg[19]/Q  -type DFF DFF
add mapped point total_cycles[20]/q total_cycles_reg[20]/Q  -type DFF DFF
add mapped point total_cycles[21]/q total_cycles_reg[21]/Q  -type DFF DFF
add mapped point total_cycles[22]/q total_cycles_reg[22]/Q  -type DFF DFF
add mapped point total_cycles[23]/q total_cycles_reg[23]/Q  -type DFF DFF
add mapped point total_cycles[24]/q total_cycles_reg[24]/Q  -type DFF DFF
add mapped point total_cycles[25]/q total_cycles_reg[25]/Q  -type DFF DFF
add mapped point total_cycles[26]/q total_cycles_reg[26]/Q  -type DFF DFF
add mapped point total_cycles[27]/q total_cycles_reg[27]/Q  -type DFF DFF
add mapped point total_cycles[28]/q total_cycles_reg[28]/Q  -type DFF DFF
add mapped point total_cycles[29]/q total_cycles_reg[29]/Q  -type DFF DFF
add mapped point total_cycles[30]/q total_cycles_reg[30]/Q  -type DFF DFF
add mapped point total_cycles[31]/q total_cycles_reg[31]/Q  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
