
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point en en -type PI PI
add mapped point x_in[31] x_in[31] -type PI PI
add mapped point x_in[30] x_in[30] -type PI PI
add mapped point x_in[29] x_in[29] -type PI PI
add mapped point x_in[28] x_in[28] -type PI PI
add mapped point x_in[27] x_in[27] -type PI PI
add mapped point x_in[26] x_in[26] -type PI PI
add mapped point x_in[25] x_in[25] -type PI PI
add mapped point x_in[24] x_in[24] -type PI PI
add mapped point x_in[23] x_in[23] -type PI PI
add mapped point x_in[22] x_in[22] -type PI PI
add mapped point x_in[21] x_in[21] -type PI PI
add mapped point x_in[20] x_in[20] -type PI PI
add mapped point x_in[19] x_in[19] -type PI PI
add mapped point x_in[18] x_in[18] -type PI PI
add mapped point x_in[17] x_in[17] -type PI PI
add mapped point x_in[16] x_in[16] -type PI PI
add mapped point x_in[15] x_in[15] -type PI PI
add mapped point x_in[14] x_in[14] -type PI PI
add mapped point x_in[13] x_in[13] -type PI PI
add mapped point x_in[12] x_in[12] -type PI PI
add mapped point x_in[11] x_in[11] -type PI PI
add mapped point x_in[10] x_in[10] -type PI PI
add mapped point x_in[9] x_in[9] -type PI PI
add mapped point x_in[8] x_in[8] -type PI PI
add mapped point x_in[7] x_in[7] -type PI PI
add mapped point x_in[6] x_in[6] -type PI PI
add mapped point x_in[5] x_in[5] -type PI PI
add mapped point x_in[4] x_in[4] -type PI PI
add mapped point x_in[3] x_in[3] -type PI PI
add mapped point x_in[2] x_in[2] -type PI PI
add mapped point x_in[1] x_in[1] -type PI PI
add mapped point x_in[0] x_in[0] -type PI PI
add mapped point in_valid in_valid -type PI PI

//output ports
add mapped point y_out[31] y_out[31] -type PO PO
add mapped point y_out[30] y_out[30] -type PO PO
add mapped point y_out[29] y_out[29] -type PO PO
add mapped point y_out[28] y_out[28] -type PO PO
add mapped point y_out[27] y_out[27] -type PO PO
add mapped point y_out[26] y_out[26] -type PO PO
add mapped point y_out[25] y_out[25] -type PO PO
add mapped point y_out[24] y_out[24] -type PO PO
add mapped point y_out[23] y_out[23] -type PO PO
add mapped point y_out[22] y_out[22] -type PO PO
add mapped point y_out[21] y_out[21] -type PO PO
add mapped point y_out[20] y_out[20] -type PO PO
add mapped point y_out[19] y_out[19] -type PO PO
add mapped point y_out[18] y_out[18] -type PO PO
add mapped point y_out[17] y_out[17] -type PO PO
add mapped point y_out[16] y_out[16] -type PO PO
add mapped point y_out[15] y_out[15] -type PO PO
add mapped point y_out[14] y_out[14] -type PO PO
add mapped point y_out[13] y_out[13] -type PO PO
add mapped point y_out[12] y_out[12] -type PO PO
add mapped point y_out[11] y_out[11] -type PO PO
add mapped point y_out[10] y_out[10] -type PO PO
add mapped point y_out[9] y_out[9] -type PO PO
add mapped point y_out[8] y_out[8] -type PO PO
add mapped point y_out[7] y_out[7] -type PO PO
add mapped point y_out[6] y_out[6] -type PO PO
add mapped point y_out[5] y_out[5] -type PO PO
add mapped point y_out[4] y_out[4] -type PO PO
add mapped point y_out[3] y_out[3] -type PO PO
add mapped point y_out[2] y_out[2] -type PO PO
add mapped point y_out[1] y_out[1] -type PO PO
add mapped point y_out[0] y_out[0] -type PO PO
add mapped point out_valid out_valid -type PO PO

//inout ports




//Sequential Pins
add mapped point out_valid/q out_valid_reg/Q  -type DFF DFF
add mapped point s1_valid/q s1_valid_reg/Q  -type DFF DFF
add mapped point s1_x3[0]/q s1_x3_reg[0]/Q  -type DFF DFF
add mapped point s1_x3[1]/q s1_x3_reg[1]/Q  -type DFF DFF
add mapped point s1_x3[2]/q s1_x3_reg[2]/Q  -type DFF DFF
add mapped point s1_x3[3]/q s1_x3_reg[3]/Q  -type DFF DFF
add mapped point s1_x3[4]/q s1_x3_reg[4]/Q  -type DFF DFF
add mapped point s1_x3[5]/q s1_x3_reg[5]/Q  -type DFF DFF
add mapped point s1_x3[6]/q s1_x3_reg[6]/Q  -type DFF DFF
add mapped point s1_x3[7]/q s1_x3_reg[7]/Q  -type DFF DFF
add mapped point s1_x3[8]/q s1_x3_reg[8]/Q  -type DFF DFF
add mapped point s1_x3[9]/q s1_x3_reg[9]/Q  -type DFF DFF
add mapped point s1_x3[10]/q s1_x3_reg[10]/Q  -type DFF DFF
add mapped point s1_x3[11]/q s1_x3_reg[11]/Q  -type DFF DFF
add mapped point s1_x3[12]/q s1_x3_reg[12]/Q  -type DFF DFF
add mapped point s1_x3[13]/q s1_x3_reg[13]/Q  -type DFF DFF
add mapped point s1_x3[14]/q s1_x3_reg[14]/Q  -type DFF DFF
add mapped point s1_x3[15]/q s1_x3_reg[15]/Q  -type DFF DFF
add mapped point s1_x3[16]/q s1_x3_reg[16]/Q  -type DFF DFF
add mapped point s1_x3[17]/q s1_x3_reg[17]/Q  -type DFF DFF
add mapped point s1_x3[18]/q s1_x3_reg[18]/Q  -type DFF DFF
add mapped point s1_x3[19]/q s1_x3_reg[19]/Q  -type DFF DFF
add mapped point s1_x3[20]/q s1_x3_reg[20]/Q  -type DFF DFF
add mapped point s1_x3[21]/q s1_x3_reg[21]/Q  -type DFF DFF
add mapped point s1_x3[22]/q s1_x3_reg[22]/Q  -type DFF DFF
add mapped point s1_x3[23]/q s1_x3_reg[23]/Q  -type DFF DFF
add mapped point s1_x3[24]/q s1_x3_reg[24]/Q  -type DFF DFF
add mapped point s1_x3[25]/q s1_x3_reg[25]/Q  -type DFF DFF
add mapped point s1_x3[26]/q s1_x3_reg[26]/Q  -type DFF DFF
add mapped point s1_x3[27]/q s1_x3_reg[27]/Q  -type DFF DFF
add mapped point s1_x3[28]/q s1_x3_reg[28]/Q  -type DFF DFF
add mapped point s1_x3[29]/q s1_x3_reg[29]/Q  -type DFF DFF
add mapped point s1_x3[30]/q s1_x3_reg[30]/Q  -type DFF DFF
add mapped point s1_x3[31]/q s1_x3_reg[31]/Q  -type DFF DFF
add mapped point s1_x[0]/q s1_x_reg[0]/Q  -type DFF DFF
add mapped point s1_x[1]/q s1_x_reg[1]/Q  -type DFF DFF
add mapped point s1_x[2]/q s1_x_reg[2]/Q  -type DFF DFF
add mapped point s1_x[3]/q s1_x_reg[3]/Q  -type DFF DFF
add mapped point s1_x[4]/q s1_x_reg[4]/Q  -type DFF DFF
add mapped point s1_x[5]/q s1_x_reg[5]/Q  -type DFF DFF
add mapped point s1_x[6]/q s1_x_reg[6]/Q  -type DFF DFF
add mapped point s1_x[7]/q s1_x_reg[7]/Q  -type DFF DFF
add mapped point s1_x[8]/q s1_x_reg[8]/Q  -type DFF DFF
add mapped point s1_x[9]/q s1_x_reg[9]/Q  -type DFF DFF
add mapped point s1_x[10]/q s1_x_reg[10]/Q  -type DFF DFF
add mapped point s1_x[11]/q s1_x_reg[11]/Q  -type DFF DFF
add mapped point s1_x[12]/q s1_x_reg[12]/Q  -type DFF DFF
add mapped point s1_x[13]/q s1_x_reg[13]/Q  -type DFF DFF
add mapped point s1_x[14]/q s1_x_reg[14]/Q  -type DFF DFF
add mapped point s1_x[15]/q s1_x_reg[15]/Q  -type DFF DFF
add mapped point s1_x[16]/q s1_x_reg[16]/Q  -type DFF DFF
add mapped point s1_x[17]/q s1_x_reg[17]/Q  -type DFF DFF
add mapped point s1_x[18]/q s1_x_reg[18]/Q  -type DFF DFF
add mapped point s1_x[19]/q s1_x_reg[19]/Q  -type DFF DFF
add mapped point s1_x[20]/q s1_x_reg[20]/Q  -type DFF DFF
add mapped point s1_x[21]/q s1_x_reg[21]/Q  -type DFF DFF
add mapped point s1_x[22]/q s1_x_reg[22]/Q  -type DFF DFF
add mapped point s1_x[23]/q s1_x_reg[23]/Q  -type DFF DFF
add mapped point s1_x[24]/q s1_x_reg[24]/Q  -type DFF DFF
add mapped point s1_x[25]/q s1_x_reg[25]/Q  -type DFF DFF
add mapped point s1_x[26]/q s1_x_reg[26]/Q  -type DFF DFF
add mapped point s1_x[27]/q s1_x_reg[27]/Q  -type DFF DFF
add mapped point s1_x[28]/q s1_x_reg[28]/Q  -type DFF DFF
add mapped point s1_x[29]/q s1_x_reg[29]/Q  -type DFF DFF
add mapped point s1_x[30]/q s1_x_reg[30]/Q  -type DFF DFF
add mapped point s1_xp[0]/q s1_xp_reg[0]/Q  -type DFF DFF
add mapped point s1_xp[1]/q s1_xp_reg[1]/Q  -type DFF DFF
add mapped point s1_xp[2]/q s1_xp_reg[2]/Q  -type DFF DFF
add mapped point s1_xp[3]/q s1_xp_reg[3]/Q  -type DFF DFF
add mapped point s1_xp[4]/q s1_xp_reg[4]/Q  -type DFF DFF
add mapped point s1_xp[5]/q s1_xp_reg[5]/Q  -type DFF DFF
add mapped point s1_xp[6]/q s1_xp_reg[6]/Q  -type DFF DFF
add mapped point s1_xp[7]/q s1_xp_reg[7]/Q  -type DFF DFF
add mapped point s1_xp[8]/q s1_xp_reg[8]/Q  -type DFF DFF
add mapped point s1_xp[9]/q s1_xp_reg[9]/Q  -type DFF DFF
add mapped point s1_xp[10]/q s1_xp_reg[10]/Q  -type DFF DFF
add mapped point s1_xp[11]/q s1_xp_reg[11]/Q  -type DFF DFF
add mapped point s1_xp[12]/q s1_xp_reg[12]/Q  -type DFF DFF
add mapped point s1_xp[13]/q s1_xp_reg[13]/Q  -type DFF DFF
add mapped point s1_xp[14]/q s1_xp_reg[14]/Q  -type DFF DFF
add mapped point s1_xp[15]/q s1_xp_reg[15]/Q  -type DFF DFF
add mapped point s1_xp[16]/q s1_xp_reg[16]/Q  -type DFF DFF
add mapped point s1_xp[17]/q s1_xp_reg[17]/Q  -type DFF DFF
add mapped point s1_xp[18]/q s1_xp_reg[18]/Q  -type DFF DFF
add mapped point s1_xp[19]/q s1_xp_reg[19]/Q  -type DFF DFF
add mapped point s1_xp[20]/q s1_xp_reg[20]/Q  -type DFF DFF
add mapped point s1_xp[21]/q s1_xp_reg[21]/Q  -type DFF DFF
add mapped point s2_valid/q s2_valid_reg/Q  -type DFF DFF
add mapped point s2_x[0]/q s2_x_reg[0]/Q  -type DFF DFF
add mapped point s2_x[1]/q s2_x_reg[1]/Q  -type DFF DFF
add mapped point s2_x[2]/q s2_x_reg[2]/Q  -type DFF DFF
add mapped point s2_x[3]/q s2_x_reg[3]/Q  -type DFF DFF
add mapped point s2_x[4]/q s2_x_reg[4]/Q  -type DFF DFF
add mapped point s2_x[5]/q s2_x_reg[5]/Q  -type DFF DFF
add mapped point s2_x[6]/q s2_x_reg[6]/Q  -type DFF DFF
add mapped point s2_x[7]/q s2_x_reg[7]/Q  -type DFF DFF
add mapped point s2_x[8]/q s2_x_reg[8]/Q  -type DFF DFF
add mapped point s2_x[9]/q s2_x_reg[9]/Q  -type DFF DFF
add mapped point s2_x[10]/q s2_x_reg[10]/Q  -type DFF DFF
add mapped point s2_x[11]/q s2_x_reg[11]/Q  -type DFF DFF
add mapped point s2_x[12]/q s2_x_reg[12]/Q  -type DFF DFF
add mapped point s2_x[13]/q s2_x_reg[13]/Q  -type DFF DFF
add mapped point s2_x[14]/q s2_x_reg[14]/Q  -type DFF DFF
add mapped point s2_x[15]/q s2_x_reg[15]/Q  -type DFF DFF
add mapped point s2_x[16]/q s2_x_reg[16]/Q  -type DFF DFF
add mapped point s2_x[17]/q s2_x_reg[17]/Q  -type DFF DFF
add mapped point s2_x[18]/q s2_x_reg[18]/Q  -type DFF DFF
add mapped point s2_x[19]/q s2_x_reg[19]/Q  -type DFF DFF
add mapped point s2_x[20]/q s2_x_reg[20]/Q  -type DFF DFF
add mapped point s2_x[21]/q s2_x_reg[21]/Q  -type DFF DFF
add mapped point s2_x[22]/q s2_x_reg[22]/Q  -type DFF DFF
add mapped point s2_x[23]/q s2_x_reg[23]/Q  -type DFF DFF
add mapped point s2_x[24]/q s2_x_reg[24]/Q  -type DFF DFF
add mapped point s2_x[25]/q s2_x_reg[25]/Q  -type DFF DFF
add mapped point s2_x[26]/q s2_x_reg[26]/Q  -type DFF DFF
add mapped point s2_x[27]/q s2_x_reg[27]/Q  -type DFF DFF
add mapped point s2_x[28]/q s2_x_reg[28]/Q  -type DFF DFF
add mapped point s2_x[29]/q s2_x_reg[29]/Q  -type DFF DFF
add mapped point s2_x[30]/q s2_x_reg[30]/Q  -type DFF DFF
add mapped point s2_x[31]/q s2_x_reg[31]/Q  -type DFF DFF
add mapped point s2_z[0]/q s2_z_reg[0]/Q  -type DFF DFF
add mapped point s2_z[1]/q s2_z_reg[1]/Q  -type DFF DFF
add mapped point s2_z[2]/q s2_z_reg[2]/Q  -type DFF DFF
add mapped point s2_z[3]/q s2_z_reg[3]/Q  -type DFF DFF
add mapped point s2_z[4]/q s2_z_reg[4]/Q  -type DFF DFF
add mapped point s2_z[5]/q s2_z_reg[5]/Q  -type DFF DFF
add mapped point s2_z[6]/q s2_z_reg[6]/Q  -type DFF DFF
add mapped point s2_z[7]/q s2_z_reg[7]/Q  -type DFF DFF
add mapped point s2_z[8]/q s2_z_reg[8]/Q  -type DFF DFF
add mapped point s2_z[9]/q s2_z_reg[9]/Q  -type DFF DFF
add mapped point s2_z[10]/q s2_z_reg[10]/Q  -type DFF DFF
add mapped point s2_z[11]/q s2_z_reg[11]/Q  -type DFF DFF
add mapped point s2_z[12]/q s2_z_reg[12]/Q  -type DFF DFF
add mapped point s2_z[13]/q s2_z_reg[13]/Q  -type DFF DFF
add mapped point s2_z[14]/q s2_z_reg[14]/Q  -type DFF DFF
add mapped point s2_z[15]/q s2_z_reg[15]/Q  -type DFF DFF
add mapped point s2_z[16]/q s2_z_reg[16]/Q  -type DFF DFF
add mapped point s2_z[17]/q s2_z_reg[17]/Q  -type DFF DFF
add mapped point s2_z[18]/q s2_z_reg[18]/Q  -type DFF DFF
add mapped point s2_z[19]/q s2_z_reg[19]/Q  -type DFF DFF
add mapped point s2_z[20]/q s2_z_reg[20]/Q  -type DFF DFF
add mapped point s2_z[21]/q s2_z_reg[21]/Q  -type DFF DFF
add mapped point s2_z[22]/q s2_z_reg[22]/Q  -type DFF DFF
add mapped point s2_z[23]/q s2_z_reg[23]/Q  -type DFF DFF
add mapped point s2_z[24]/q s2_z_reg[24]/Q  -type DFF DFF
add mapped point s2_z[25]/q s2_z_reg[25]/Q  -type DFF DFF
add mapped point s2_z[26]/q s2_z_reg[26]/Q  -type DFF DFF
add mapped point s2_z[27]/q s2_z_reg[27]/Q  -type DFF DFF
add mapped point s2_z[28]/q s2_z_reg[28]/Q  -type DFF DFF
add mapped point s2_z[29]/q s2_z_reg[29]/Q  -type DFF DFF
add mapped point s2_z[30]/q s2_z_reg[30]/Q  -type DFF DFF
add mapped point s2_z[31]/q s2_z_reg[31]/Q  -type DFF DFF
add mapped point s3_saturate_neg/q s3_saturate_neg_reg/Q  -type DFF DFF
add mapped point s3_saturate_pos/q s3_saturate_pos_reg/Q  -type DFF DFF
add mapped point s3_valid/q s3_valid_reg/Q  -type DFF DFF
add mapped point s3_x[0]/q s3_x_reg[0]/Q  -type DFF DFF
add mapped point s3_x[1]/q s3_x_reg[1]/Q  -type DFF DFF
add mapped point s3_x[2]/q s3_x_reg[2]/Q  -type DFF DFF
add mapped point s3_x[3]/q s3_x_reg[3]/Q  -type DFF DFF
add mapped point s3_x[4]/q s3_x_reg[4]/Q  -type DFF DFF
add mapped point s3_x[5]/q s3_x_reg[5]/Q  -type DFF DFF
add mapped point s3_x[6]/q s3_x_reg[6]/Q  -type DFF DFF
add mapped point s3_x[7]/q s3_x_reg[7]/Q  -type DFF DFF
add mapped point s3_x[8]/q s3_x_reg[8]/Q  -type DFF DFF
add mapped point s3_x[9]/q s3_x_reg[9]/Q  -type DFF DFF
add mapped point s3_x[10]/q s3_x_reg[10]/Q  -type DFF DFF
add mapped point s3_x[11]/q s3_x_reg[11]/Q  -type DFF DFF
add mapped point s3_x[12]/q s3_x_reg[12]/Q  -type DFF DFF
add mapped point s3_x[13]/q s3_x_reg[13]/Q  -type DFF DFF
add mapped point s3_x[14]/q s3_x_reg[14]/Q  -type DFF DFF
add mapped point s3_x[15]/q s3_x_reg[15]/Q  -type DFF DFF
add mapped point s3_x[16]/q s3_x_reg[16]/Q  -type DFF DFF
add mapped point s3_x[17]/q s3_x_reg[17]/Q  -type DFF DFF
add mapped point s3_x[18]/q s3_x_reg[18]/Q  -type DFF DFF
add mapped point s3_x[19]/q s3_x_reg[19]/Q  -type DFF DFF
add mapped point s3_x[20]/q s3_x_reg[20]/Q  -type DFF DFF
add mapped point s3_x[21]/q s3_x_reg[21]/Q  -type DFF DFF
add mapped point s3_x[22]/q s3_x_reg[22]/Q  -type DFF DFF
add mapped point s3_x[23]/q s3_x_reg[23]/Q  -type DFF DFF
add mapped point s3_x[24]/q s3_x_reg[24]/Q  -type DFF DFF
add mapped point s3_x[25]/q s3_x_reg[25]/Q  -type DFF DFF
add mapped point s3_x[26]/q s3_x_reg[26]/Q  -type DFF DFF
add mapped point s3_x[27]/q s3_x_reg[27]/Q  -type DFF DFF
add mapped point s3_x[28]/q s3_x_reg[28]/Q  -type DFF DFF
add mapped point s3_x[29]/q s3_x_reg[29]/Q  -type DFF DFF
add mapped point s3_x[30]/q s3_x_reg[30]/Q  -type DFF DFF
add mapped point s3_x[31]/q s3_x_reg[31]/Q  -type DFF DFF
add mapped point s3_z2[0]/q s3_z2_reg[0]/Q  -type DFF DFF
add mapped point s3_z2[1]/q s3_z2_reg[1]/Q  -type DFF DFF
add mapped point s3_z2[2]/q s3_z2_reg[2]/Q  -type DFF DFF
add mapped point s3_z2[3]/q s3_z2_reg[3]/Q  -type DFF DFF
add mapped point s3_z2[4]/q s3_z2_reg[4]/Q  -type DFF DFF
add mapped point s3_z2[5]/q s3_z2_reg[5]/Q  -type DFF DFF
add mapped point s3_z2[6]/q s3_z2_reg[6]/Q  -type DFF DFF
add mapped point s3_z2[7]/q s3_z2_reg[7]/Q  -type DFF DFF
add mapped point s3_z2[8]/q s3_z2_reg[8]/Q  -type DFF DFF
add mapped point s3_z2[9]/q s3_z2_reg[9]/Q  -type DFF DFF
add mapped point s3_z2[10]/q s3_z2_reg[10]/Q  -type DFF DFF
add mapped point s3_z2[11]/q s3_z2_reg[11]/Q  -type DFF DFF
add mapped point s3_z2[12]/q s3_z2_reg[12]/Q  -type DFF DFF
add mapped point s3_z2[13]/q s3_z2_reg[13]/Q  -type DFF DFF
add mapped point s3_z2[14]/q s3_z2_reg[14]/Q  -type DFF DFF
add mapped point s3_z2[15]/q s3_z2_reg[15]/Q  -type DFF DFF
add mapped point s3_z2[16]/q s3_z2_reg[16]/Q  -type DFF DFF
add mapped point s3_z2[17]/q s3_z2_reg[17]/Q  -type DFF DFF
add mapped point s3_z2[18]/q s3_z2_reg[18]/Q  -type DFF DFF
add mapped point s3_z2[19]/q s3_z2_reg[19]/Q  -type DFF DFF
add mapped point s3_z2[20]/q s3_z2_reg[20]/Q  -type DFF DFF
add mapped point s3_z2[21]/q s3_z2_reg[21]/Q  -type DFF DFF
add mapped point s3_z2[22]/q s3_z2_reg[22]/Q  -type DFF DFF
add mapped point s3_z2[23]/q s3_z2_reg[23]/Q  -type DFF DFF
add mapped point s3_z2[24]/q s3_z2_reg[24]/Q  -type DFF DFF
add mapped point s3_z2[25]/q s3_z2_reg[25]/Q  -type DFF DFF
add mapped point s3_z2[26]/q s3_z2_reg[26]/Q  -type DFF DFF
add mapped point s3_z2[27]/q s3_z2_reg[27]/Q  -type DFF DFF
add mapped point s3_z2[28]/q s3_z2_reg[28]/Q  -type DFF DFF
add mapped point s3_z2[29]/q s3_z2_reg[29]/Q  -type DFF DFF
add mapped point s3_z2[30]/q s3_z2_reg[30]/Q  -type DFF DFF
add mapped point s3_z2[31]/q s3_z2_reg[31]/Q  -type DFF DFF
add mapped point s3_z[0]/q s3_z_reg[0]/Q  -type DFF DFF
add mapped point s3_z[1]/q s3_z_reg[1]/Q  -type DFF DFF
add mapped point s3_z[2]/q s3_z_reg[2]/Q  -type DFF DFF
add mapped point s3_z[3]/q s3_z_reg[3]/Q  -type DFF DFF
add mapped point s3_z[4]/q s3_z_reg[4]/Q  -type DFF DFF
add mapped point s3_z[5]/q s3_z_reg[5]/Q  -type DFF DFF
add mapped point s3_z[6]/q s3_z_reg[6]/Q  -type DFF DFF
add mapped point s3_z[7]/q s3_z_reg[7]/Q  -type DFF DFF
add mapped point s3_z[8]/q s3_z_reg[8]/Q  -type DFF DFF
add mapped point s3_z[9]/q s3_z_reg[9]/Q  -type DFF DFF
add mapped point s3_z[10]/q s3_z_reg[10]/Q  -type DFF DFF
add mapped point s3_z[11]/q s3_z_reg[11]/Q  -type DFF DFF
add mapped point s3_z[12]/q s3_z_reg[12]/Q  -type DFF DFF
add mapped point s3_z[13]/q s3_z_reg[13]/Q  -type DFF DFF
add mapped point s3_z[14]/q s3_z_reg[14]/Q  -type DFF DFF
add mapped point s3_z[15]/q s3_z_reg[15]/Q  -type DFF DFF
add mapped point s3_z[16]/q s3_z_reg[16]/Q  -type DFF DFF
add mapped point s3_z[17]/q s3_z_reg[17]/Q  -type DFF DFF
add mapped point s3_z[18]/q s3_z_reg[18]/Q  -type DFF DFF
add mapped point s3_z[19]/q s3_z_reg[19]/Q  -type DFF DFF
add mapped point s4_den[0]/q s4_den_reg[0]/Q  -type DFF DFF
add mapped point s4_den[1]/q s4_den_reg[1]/Q  -type DFF DFF
add mapped point s4_den[2]/q s4_den_reg[2]/Q  -type DFF DFF
add mapped point s4_den[3]/q s4_den_reg[3]/Q  -type DFF DFF
add mapped point s4_den[4]/q s4_den_reg[4]/Q  -type DFF DFF
add mapped point s4_den[5]/q s4_den_reg[5]/Q  -type DFF DFF
add mapped point s4_den[6]/q s4_den_reg[6]/Q  -type DFF DFF
add mapped point s4_den[7]/q s4_den_reg[7]/Q  -type DFF DFF
add mapped point s4_den[8]/q s4_den_reg[8]/Q  -type DFF DFF
add mapped point s4_den[9]/q s4_den_reg[9]/Q  -type DFF DFF
add mapped point s4_den[10]/q s4_den_reg[10]/Q  -type DFF DFF
add mapped point s4_den[11]/q s4_den_reg[11]/Q  -type DFF DFF
add mapped point s4_den[12]/q s4_den_reg[12]/Q  -type DFF DFF
add mapped point s4_den[13]/q s4_den_reg[13]/Q  -type DFF DFF
add mapped point s4_den[14]/q s4_den_reg[14]/Q  -type DFF DFF
add mapped point s4_den[15]/q s4_den_reg[15]/Q  -type DFF DFF
add mapped point s4_den[16]/q s4_den_reg[16]/Q  -type DFF DFF
add mapped point s4_den[17]/q s4_den_reg[17]/Q  -type DFF DFF
add mapped point s4_den[18]/q s4_den_reg[18]/Q  -type DFF DFF
add mapped point s4_den[19]/q s4_den_reg[19]/Q  -type DFF DFF
add mapped point s4_den[20]/q s4_den_reg[20]/Q  -type DFF DFF
add mapped point s4_den[21]/q s4_den_reg[21]/Q  -type DFF DFF
add mapped point s4_den[22]/q s4_den_reg[22]/Q  -type DFF DFF
add mapped point s4_den[23]/q s4_den_reg[23]/Q  -type DFF DFF
add mapped point s4_den[24]/q s4_den_reg[24]/Q  -type DFF DFF
add mapped point s4_den[25]/q s4_den_reg[25]/Q  -type DFF DFF
add mapped point s4_den[26]/q s4_den_reg[26]/Q  -type DFF DFF
add mapped point s4_den[27]/q s4_den_reg[27]/Q  -type DFF DFF
add mapped point s4_den[28]/q s4_den_reg[28]/Q  -type DFF DFF
add mapped point s4_den[29]/q s4_den_reg[29]/Q  -type DFF DFF
add mapped point s4_den[30]/q s4_den_reg[30]/Q  -type DFF DFF
add mapped point s4_den[31]/q s4_den_reg[31]/Q  -type DFF DFF
add mapped point s4_num[0]/q s4_num_reg[0]/Q  -type DFF DFF
add mapped point s4_num[1]/q s4_num_reg[1]/Q  -type DFF DFF
add mapped point s4_num[2]/q s4_num_reg[2]/Q  -type DFF DFF
add mapped point s4_num[3]/q s4_num_reg[3]/Q  -type DFF DFF
add mapped point s4_num[4]/q s4_num_reg[4]/Q  -type DFF DFF
add mapped point s4_num[5]/q s4_num_reg[5]/Q  -type DFF DFF
add mapped point s4_num[6]/q s4_num_reg[6]/Q  -type DFF DFF
add mapped point s4_num[7]/q s4_num_reg[7]/Q  -type DFF DFF
add mapped point s4_num[8]/q s4_num_reg[8]/Q  -type DFF DFF
add mapped point s4_num[9]/q s4_num_reg[9]/Q  -type DFF DFF
add mapped point s4_num[10]/q s4_num_reg[10]/Q  -type DFF DFF
add mapped point s4_num[11]/q s4_num_reg[11]/Q  -type DFF DFF
add mapped point s4_num[12]/q s4_num_reg[12]/Q  -type DFF DFF
add mapped point s4_num[13]/q s4_num_reg[13]/Q  -type DFF DFF
add mapped point s4_num[14]/q s4_num_reg[14]/Q  -type DFF DFF
add mapped point s4_num[15]/q s4_num_reg[15]/Q  -type DFF DFF
add mapped point s4_num[16]/q s4_num_reg[16]/Q  -type DFF DFF
add mapped point s4_num[17]/q s4_num_reg[17]/Q  -type DFF DFF
add mapped point s4_num[18]/q s4_num_reg[18]/Q  -type DFF DFF
add mapped point s4_num[19]/q s4_num_reg[19]/Q  -type DFF DFF
add mapped point s4_num[20]/q s4_num_reg[20]/Q  -type DFF DFF
add mapped point s4_num[21]/q s4_num_reg[21]/Q  -type DFF DFF
add mapped point s4_num[22]/q s4_num_reg[22]/Q  -type DFF DFF
add mapped point s4_num[23]/q s4_num_reg[23]/Q  -type DFF DFF
add mapped point s4_num[24]/q s4_num_reg[24]/Q  -type DFF DFF
add mapped point s4_num[25]/q s4_num_reg[25]/Q  -type DFF DFF
add mapped point s4_num[26]/q s4_num_reg[26]/Q  -type DFF DFF
add mapped point s4_num[27]/q s4_num_reg[27]/Q  -type DFF DFF
add mapped point s4_num[28]/q s4_num_reg[28]/Q  -type DFF DFF
add mapped point s4_num[29]/q s4_num_reg[29]/Q  -type DFF DFF
add mapped point s4_num[30]/q s4_num_reg[30]/Q  -type DFF DFF
add mapped point s4_num[31]/q s4_num_reg[31]/Q  -type DFF DFF
add mapped point s4_sat_neg/q s4_sat_neg_reg/Q  -type DFF DFF
add mapped point s4_sat_pos/q s4_sat_pos_reg/Q  -type DFF DFF
add mapped point s4_valid/q s4_valid_reg/Q  -type DFF DFF
add mapped point s4_x[0]/q s4_x_reg[0]/Q  -type DFF DFF
add mapped point s4_x[1]/q s4_x_reg[1]/Q  -type DFF DFF
add mapped point s4_x[2]/q s4_x_reg[2]/Q  -type DFF DFF
add mapped point s4_x[3]/q s4_x_reg[3]/Q  -type DFF DFF
add mapped point s4_x[4]/q s4_x_reg[4]/Q  -type DFF DFF
add mapped point s4_x[5]/q s4_x_reg[5]/Q  -type DFF DFF
add mapped point s4_x[6]/q s4_x_reg[6]/Q  -type DFF DFF
add mapped point s4_x[7]/q s4_x_reg[7]/Q  -type DFF DFF
add mapped point s4_x[8]/q s4_x_reg[8]/Q  -type DFF DFF
add mapped point s4_x[9]/q s4_x_reg[9]/Q  -type DFF DFF
add mapped point s4_x[10]/q s4_x_reg[10]/Q  -type DFF DFF
add mapped point s4_x[11]/q s4_x_reg[11]/Q  -type DFF DFF
add mapped point s4_x[12]/q s4_x_reg[12]/Q  -type DFF DFF
add mapped point s4_x[13]/q s4_x_reg[13]/Q  -type DFF DFF
add mapped point s4_x[14]/q s4_x_reg[14]/Q  -type DFF DFF
add mapped point s4_x[15]/q s4_x_reg[15]/Q  -type DFF DFF
add mapped point s4_x[16]/q s4_x_reg[16]/Q  -type DFF DFF
add mapped point s4_x[17]/q s4_x_reg[17]/Q  -type DFF DFF
add mapped point s4_x[18]/q s4_x_reg[18]/Q  -type DFF DFF
add mapped point s4_x[19]/q s4_x_reg[19]/Q  -type DFF DFF
add mapped point s4_x[20]/q s4_x_reg[20]/Q  -type DFF DFF
add mapped point s4_x[21]/q s4_x_reg[21]/Q  -type DFF DFF
add mapped point s4_x[22]/q s4_x_reg[22]/Q  -type DFF DFF
add mapped point s4_x[23]/q s4_x_reg[23]/Q  -type DFF DFF
add mapped point s4_x[24]/q s4_x_reg[24]/Q  -type DFF DFF
add mapped point s4_x[25]/q s4_x_reg[25]/Q  -type DFF DFF
add mapped point s4_x[26]/q s4_x_reg[26]/Q  -type DFF DFF
add mapped point s4_x[27]/q s4_x_reg[27]/Q  -type DFF DFF
add mapped point s4_x[28]/q s4_x_reg[28]/Q  -type DFF DFF
add mapped point s4_x[29]/q s4_x_reg[29]/Q  -type DFF DFF
add mapped point s4_x[30]/q s4_x_reg[30]/Q  -type DFF DFF
add mapped point s4_x[31]/q s4_x_reg[31]/Q  -type DFF DFF
add mapped point s5_tanh[0]/q s5_tanh_reg[0]/Q  -type DFF DFF
add mapped point s5_tanh[1]/q s5_tanh_reg[1]/Q  -type DFF DFF
add mapped point s5_tanh[2]/q s5_tanh_reg[2]/Q  -type DFF DFF
add mapped point s5_tanh[3]/q s5_tanh_reg[3]/Q  -type DFF DFF
add mapped point s5_tanh[4]/q s5_tanh_reg[4]/Q  -type DFF DFF
add mapped point s5_tanh[5]/q s5_tanh_reg[5]/Q  -type DFF DFF
add mapped point s5_tanh[6]/q s5_tanh_reg[6]/Q  -type DFF DFF
add mapped point s5_tanh[7]/q s5_tanh_reg[7]/Q  -type DFF DFF
add mapped point s5_tanh[8]/q s5_tanh_reg[8]/Q  -type DFF DFF
add mapped point s5_tanh[9]/q s5_tanh_reg[9]/Q  -type DFF DFF
add mapped point s5_tanh[10]/q s5_tanh_reg[10]/Q  -type DFF DFF
add mapped point s5_tanh[11]/q s5_tanh_reg[11]/Q  -type DFF DFF
add mapped point s5_tanh[12]/q s5_tanh_reg[12]/Q  -type DFF DFF
add mapped point s5_tanh[13]/q s5_tanh_reg[13]/Q  -type DFF DFF
add mapped point s5_tanh[14]/q s5_tanh_reg[14]/Q  -type DFF DFF
add mapped point s5_tanh[15]/q s5_tanh_reg[15]/Q  -type DFF DFF
add mapped point s5_tanh[16]/q s5_tanh_reg[16]/Q  -type DFF DFF
add mapped point s5_tanh[17]/q s5_tanh_reg[17]/Q  -type DFF DFF
add mapped point s5_tanh[18]/q s5_tanh_reg[18]/Q  -type DFF DFF
add mapped point s5_tanh[19]/q s5_tanh_reg[19]/Q  -type DFF DFF
add mapped point s5_tanh[20]/q s5_tanh_reg[20]/Q  -type DFF DFF
add mapped point s5_tanh[21]/q s5_tanh_reg[21]/Q  -type DFF DFF
add mapped point s5_tanh[22]/q s5_tanh_reg[22]/Q  -type DFF DFF
add mapped point s5_tanh[23]/q s5_tanh_reg[23]/Q  -type DFF DFF
add mapped point s5_tanh[24]/q s5_tanh_reg[24]/Q  -type DFF DFF
add mapped point s5_tanh[25]/q s5_tanh_reg[25]/Q  -type DFF DFF
add mapped point s5_tanh[26]/q s5_tanh_reg[26]/Q  -type DFF DFF
add mapped point s5_tanh[27]/q s5_tanh_reg[27]/Q  -type DFF DFF
add mapped point s5_tanh[28]/q s5_tanh_reg[28]/Q  -type DFF DFF
add mapped point s5_tanh[29]/q s5_tanh_reg[29]/Q  -type DFF DFF
add mapped point s5_tanh[30]/q s5_tanh_reg[30]/Q  -type DFF DFF
add mapped point s5_tanh[31]/q s5_tanh_reg[31]/Q  -type DFF DFF
add mapped point s5_valid/q s5_valid_reg/Q  -type DFF DFF
add mapped point s5_x[0]/q s5_x_reg[0]/Q  -type DFF DFF
add mapped point s5_x[1]/q s5_x_reg[1]/Q  -type DFF DFF
add mapped point s5_x[2]/q s5_x_reg[2]/Q  -type DFF DFF
add mapped point s5_x[3]/q s5_x_reg[3]/Q  -type DFF DFF
add mapped point s5_x[4]/q s5_x_reg[4]/Q  -type DFF DFF
add mapped point s5_x[5]/q s5_x_reg[5]/Q  -type DFF DFF
add mapped point s5_x[6]/q s5_x_reg[6]/Q  -type DFF DFF
add mapped point s5_x[7]/q s5_x_reg[7]/Q  -type DFF DFF
add mapped point s5_x[8]/q s5_x_reg[8]/Q  -type DFF DFF
add mapped point s5_x[9]/q s5_x_reg[9]/Q  -type DFF DFF
add mapped point s5_x[10]/q s5_x_reg[10]/Q  -type DFF DFF
add mapped point s5_x[11]/q s5_x_reg[11]/Q  -type DFF DFF
add mapped point s5_x[12]/q s5_x_reg[12]/Q  -type DFF DFF
add mapped point s5_x[13]/q s5_x_reg[13]/Q  -type DFF DFF
add mapped point s5_x[14]/q s5_x_reg[14]/Q  -type DFF DFF
add mapped point s5_x[15]/q s5_x_reg[15]/Q  -type DFF DFF
add mapped point s5_x[16]/q s5_x_reg[16]/Q  -type DFF DFF
add mapped point s5_x[17]/q s5_x_reg[17]/Q  -type DFF DFF
add mapped point s5_x[18]/q s5_x_reg[18]/Q  -type DFF DFF
add mapped point s5_x[19]/q s5_x_reg[19]/Q  -type DFF DFF
add mapped point s5_x[20]/q s5_x_reg[20]/Q  -type DFF DFF
add mapped point s5_x[21]/q s5_x_reg[21]/Q  -type DFF DFF
add mapped point s5_x[22]/q s5_x_reg[22]/Q  -type DFF DFF
add mapped point s5_x[23]/q s5_x_reg[23]/Q  -type DFF DFF
add mapped point s5_x[24]/q s5_x_reg[24]/Q  -type DFF DFF
add mapped point s5_x[25]/q s5_x_reg[25]/Q  -type DFF DFF
add mapped point s5_x[26]/q s5_x_reg[26]/Q  -type DFF DFF
add mapped point s5_x[27]/q s5_x_reg[27]/Q  -type DFF DFF
add mapped point s5_x[28]/q s5_x_reg[28]/Q  -type DFF DFF
add mapped point s5_x[29]/q s5_x_reg[29]/Q  -type DFF DFF
add mapped point s5_x[30]/q s5_x_reg[30]/Q  -type DFF DFF
add mapped point s5_x[31]/q s5_x_reg[31]/Q  -type DFF DFF
add mapped point y_out[0]/q y_out_reg[0]/Q  -type DFF DFF
add mapped point y_out[1]/q y_out_reg[1]/Q  -type DFF DFF
add mapped point y_out[2]/q y_out_reg[2]/Q  -type DFF DFF
add mapped point y_out[3]/q y_out_reg[3]/Q  -type DFF DFF
add mapped point y_out[4]/q y_out_reg[4]/Q  -type DFF DFF
add mapped point y_out[5]/q y_out_reg[5]/Q  -type DFF DFF
add mapped point y_out[6]/q y_out_reg[6]/Q  -type DFF DFF
add mapped point y_out[7]/q y_out_reg[7]/Q  -type DFF DFF
add mapped point y_out[8]/q y_out_reg[8]/Q  -type DFF DFF
add mapped point y_out[9]/q y_out_reg[9]/Q  -type DFF DFF
add mapped point y_out[10]/q y_out_reg[10]/Q  -type DFF DFF
add mapped point y_out[11]/q y_out_reg[11]/Q  -type DFF DFF
add mapped point y_out[12]/q y_out_reg[12]/Q  -type DFF DFF
add mapped point y_out[13]/q y_out_reg[13]/Q  -type DFF DFF
add mapped point y_out[14]/q y_out_reg[14]/Q  -type DFF DFF
add mapped point y_out[15]/q y_out_reg[15]/Q  -type DFF DFF
add mapped point y_out[16]/q y_out_reg[16]/Q  -type DFF DFF
add mapped point y_out[17]/q y_out_reg[17]/Q  -type DFF DFF
add mapped point y_out[18]/q y_out_reg[18]/Q  -type DFF DFF
add mapped point y_out[19]/q y_out_reg[19]/Q  -type DFF DFF
add mapped point y_out[20]/q y_out_reg[20]/Q  -type DFF DFF
add mapped point y_out[21]/q y_out_reg[21]/Q  -type DFF DFF
add mapped point y_out[22]/q y_out_reg[22]/Q  -type DFF DFF
add mapped point y_out[23]/q y_out_reg[23]/Q  -type DFF DFF
add mapped point y_out[24]/q y_out_reg[24]/Q  -type DFF DFF
add mapped point y_out[25]/q y_out_reg[25]/Q  -type DFF DFF
add mapped point y_out[26]/q y_out_reg[26]/Q  -type DFF DFF
add mapped point y_out[27]/q y_out_reg[27]/Q  -type DFF DFF
add mapped point y_out[28]/q y_out_reg[28]/Q  -type DFF DFF
add mapped point y_out[29]/q y_out_reg[29]/Q  -type DFF DFF
add mapped point y_out[30]/q y_out_reg[30]/Q  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
