/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module exp_lut(clk, addr, data);
  wire [31:0] _00_;
  input [7:0] addr;
  wire [7:0] addr;
  input clk;
  wire clk;
  output [31:0] data;
  wire [31:0] data;
  reg [31:0] lut_mem [255:0];
  initial begin
    lut_mem[0] = 32'd22;
    lut_mem[1] = 32'd23;
    lut_mem[2] = 32'd23;
    lut_mem[3] = 32'd24;
    lut_mem[4] = 32'd25;
    lut_mem[5] = 32'd26;
    lut_mem[6] = 32'd27;
    lut_mem[7] = 32'd27;
    lut_mem[8] = 32'd28;
    lut_mem[9] = 32'd29;
    lut_mem[10] = 32'd30;
    lut_mem[11] = 32'd31;
    lut_mem[12] = 32'd32;
    lut_mem[13] = 32'd33;
    lut_mem[14] = 32'd34;
    lut_mem[15] = 32'd35;
    lut_mem[16] = 32'd36;
    lut_mem[17] = 32'd37;
    lut_mem[18] = 32'd39;
    lut_mem[19] = 32'd40;
    lut_mem[20] = 32'd41;
    lut_mem[21] = 32'd42;
    lut_mem[22] = 32'd44;
    lut_mem[23] = 32'd45;
    lut_mem[24] = 32'd47;
    lut_mem[25] = 32'd48;
    lut_mem[26] = 32'd50;
    lut_mem[27] = 32'd51;
    lut_mem[28] = 32'd53;
    lut_mem[29] = 32'd55;
    lut_mem[30] = 32'd56;
    lut_mem[31] = 32'd58;
    lut_mem[32] = 32'd60;
    lut_mem[33] = 32'd62;
    lut_mem[34] = 32'd64;
    lut_mem[35] = 32'd66;
    lut_mem[36] = 32'd68;
    lut_mem[37] = 32'd70;
    lut_mem[38] = 32'd72;
    lut_mem[39] = 32'd75;
    lut_mem[40] = 32'd77;
    lut_mem[41] = 32'd80;
    lut_mem[42] = 32'd82;
    lut_mem[43] = 32'd85;
    lut_mem[44] = 32'd87;
    lut_mem[45] = 32'd90;
    lut_mem[46] = 32'd93;
    lut_mem[47] = 32'd96;
    lut_mem[48] = 32'd99;
    lut_mem[49] = 32'd102;
    lut_mem[50] = 32'd106;
    lut_mem[51] = 32'd109;
    lut_mem[52] = 32'd112;
    lut_mem[53] = 32'd116;
    lut_mem[54] = 32'd120;
    lut_mem[55] = 32'd123;
    lut_mem[56] = 32'd127;
    lut_mem[57] = 32'd131;
    lut_mem[58] = 32'd136;
    lut_mem[59] = 32'd140;
    lut_mem[60] = 32'd144;
    lut_mem[61] = 32'd149;
    lut_mem[62] = 32'd154;
    lut_mem[63] = 32'd159;
    lut_mem[64] = 32'd164;
    lut_mem[65] = 32'd169;
    lut_mem[66] = 32'd174;
    lut_mem[67] = 32'd180;
    lut_mem[68] = 32'd186;
    lut_mem[69] = 32'd192;
    lut_mem[70] = 32'd198;
    lut_mem[71] = 32'd204;
    lut_mem[72] = 32'd210;
    lut_mem[73] = 32'd217;
    lut_mem[74] = 32'd224;
    lut_mem[75] = 32'd231;
    lut_mem[76] = 32'd239;
    lut_mem[77] = 32'd246;
    lut_mem[78] = 32'd254;
    lut_mem[79] = 32'd262;
    lut_mem[80] = 32'd270;
    lut_mem[81] = 32'd279;
    lut_mem[82] = 32'd288;
    lut_mem[83] = 32'd297;
    lut_mem[84] = 32'd307;
    lut_mem[85] = 32'd316;
    lut_mem[86] = 32'd326;
    lut_mem[87] = 32'd337;
    lut_mem[88] = 32'd348;
    lut_mem[89] = 32'd359;
    lut_mem[90] = 32'd370;
    lut_mem[91] = 32'd382;
    lut_mem[92] = 32'd394;
    lut_mem[93] = 32'd407;
    lut_mem[94] = 32'd420;
    lut_mem[95] = 32'd433;
    lut_mem[96] = 32'd447;
    lut_mem[97] = 32'd461;
    lut_mem[98] = 32'd476;
    lut_mem[99] = 32'd491;
    lut_mem[100] = 32'd507;
    lut_mem[101] = 32'd523;
    lut_mem[102] = 32'd539;
    lut_mem[103] = 32'd557;
    lut_mem[104] = 32'd574;
    lut_mem[105] = 32'd593;
    lut_mem[106] = 32'd611;
    lut_mem[107] = 32'd631;
    lut_mem[108] = 32'd651;
    lut_mem[109] = 32'd672;
    lut_mem[110] = 32'd693;
    lut_mem[111] = 32'd715;
    lut_mem[112] = 32'd738;
    lut_mem[113] = 32'd762;
    lut_mem[114] = 32'd786;
    lut_mem[115] = 32'd811;
    lut_mem[116] = 32'd837;
    lut_mem[117] = 32'd863;
    lut_mem[118] = 32'd891;
    lut_mem[119] = 32'd919;
    lut_mem[120] = 32'd949;
    lut_mem[121] = 32'd979;
    lut_mem[122] = 32'd1010;
    lut_mem[123] = 32'd1042;
    lut_mem[124] = 32'd1076;
    lut_mem[125] = 32'd1110;
    lut_mem[126] = 32'd1145;
    lut_mem[127] = 32'd1182;
    lut_mem[128] = 32'd1219;
    lut_mem[129] = 32'd1258;
    lut_mem[130] = 32'd1298;
    lut_mem[131] = 32'd1340;
    lut_mem[132] = 32'd1382;
    lut_mem[133] = 32'd1426;
    lut_mem[134] = 32'd1472;
    lut_mem[135] = 32'd1519;
    lut_mem[136] = 32'd1567;
    lut_mem[137] = 32'd1617;
    lut_mem[138] = 32'd1669;
    lut_mem[139] = 32'd1722;
    lut_mem[140] = 32'd1777;
    lut_mem[141] = 32'd1833;
    lut_mem[142] = 32'd1892;
    lut_mem[143] = 32'd1952;
    lut_mem[144] = 32'd2014;
    lut_mem[145] = 32'd2078;
    lut_mem[146] = 32'd2145;
    lut_mem[147] = 32'd2213;
    lut_mem[148] = 32'd2284;
    lut_mem[149] = 32'd2356;
    lut_mem[150] = 32'd2431;
    lut_mem[151] = 32'd2509;
    lut_mem[152] = 32'd2589;
    lut_mem[153] = 32'd2671;
    lut_mem[154] = 32'd2757;
    lut_mem[155] = 32'd2844;
    lut_mem[156] = 32'd2935;
    lut_mem[157] = 32'd3029;
    lut_mem[158] = 32'd3125;
    lut_mem[159] = 32'd3225;
    lut_mem[160] = 32'd3327;
    lut_mem[161] = 32'd3433;
    lut_mem[162] = 32'd3543;
    lut_mem[163] = 32'd3656;
    lut_mem[164] = 32'd3772;
    lut_mem[165] = 32'd3893;
    lut_mem[166] = 32'd4017;
    lut_mem[167] = 32'd4145;
    lut_mem[168] = 32'd4277;
    lut_mem[169] = 32'd4413;
    lut_mem[170] = 32'd4554;
    lut_mem[171] = 32'd4699;
    lut_mem[172] = 32'd4849;
    lut_mem[173] = 32'd5003;
    lut_mem[174] = 32'd5163;
    lut_mem[175] = 32'd5327;
    lut_mem[176] = 32'd5497;
    lut_mem[177] = 32'd5672;
    lut_mem[178] = 32'd5853;
    lut_mem[179] = 32'd6039;
    lut_mem[180] = 32'd6232;
    lut_mem[181] = 32'd6430;
    lut_mem[182] = 32'd6635;
    lut_mem[183] = 32'd6847;
    lut_mem[184] = 32'd7065;
    lut_mem[185] = 32'd7290;
    lut_mem[186] = 32'd7522;
    lut_mem[187] = 32'd7762;
    lut_mem[188] = 32'd8010;
    lut_mem[189] = 32'd8265;
    lut_mem[190] = 32'd8528;
    lut_mem[191] = 32'd8800;
    lut_mem[192] = 32'd9080;
    lut_mem[193] = 32'd9370;
    lut_mem[194] = 32'd9669;
    lut_mem[195] = 32'd9977;
    lut_mem[196] = 32'd10295;
    lut_mem[197] = 32'd10623;
    lut_mem[198] = 32'd10961;
    lut_mem[199] = 32'd11311;
    lut_mem[200] = 32'd11671;
    lut_mem[201] = 32'd12043;
    lut_mem[202] = 32'd12427;
    lut_mem[203] = 32'd12823;
    lut_mem[204] = 32'd13231;
    lut_mem[205] = 32'd13653;
    lut_mem[206] = 32'd14088;
    lut_mem[207] = 32'd14537;
    lut_mem[208] = 32'd15001;
    lut_mem[209] = 32'd15479;
    lut_mem[210] = 32'd15972;
    lut_mem[211] = 32'd16481;
    lut_mem[212] = 32'd17006;
    lut_mem[213] = 32'd17548;
    lut_mem[214] = 32'd18107;
    lut_mem[215] = 32'd18685;
    lut_mem[216] = 32'd19280;
    lut_mem[217] = 32'd19894;
    lut_mem[218] = 32'd20529;
    lut_mem[219] = 32'd21183;
    lut_mem[220] = 32'd21858;
    lut_mem[221] = 32'd22554;
    lut_mem[222] = 32'd23273;
    lut_mem[223] = 32'd24015;
    lut_mem[224] = 32'd24780;
    lut_mem[225] = 32'd25570;
    lut_mem[226] = 32'd26385;
    lut_mem[227] = 32'd27226;
    lut_mem[228] = 32'd28094;
    lut_mem[229] = 32'd28989;
    lut_mem[230] = 32'd29913;
    lut_mem[231] = 32'd30866;
    lut_mem[232] = 32'd31850;
    lut_mem[233] = 32'd32865;
    lut_mem[234] = 32'd33912;
    lut_mem[235] = 32'd34993;
    lut_mem[236] = 32'd36108;
    lut_mem[237] = 32'd37259;
    lut_mem[238] = 32'd38446;
    lut_mem[239] = 32'd39672;
    lut_mem[240] = 32'd40936;
    lut_mem[241] = 32'd42241;
    lut_mem[242] = 32'd43587;
    lut_mem[243] = 32'd44976;
    lut_mem[244] = 32'd46409;
    lut_mem[245] = 32'd47888;
    lut_mem[246] = 32'd49415;
    lut_mem[247] = 32'd50989;
    lut_mem[248] = 32'd52615;
    lut_mem[249] = 32'd54291;
    lut_mem[250] = 32'd56022;
    lut_mem[251] = 32'd57807;
    lut_mem[252] = 32'd59649;
    lut_mem[253] = 32'd61550;
    lut_mem[254] = 32'd63512;
    lut_mem[255] = 32'd65536;
  end
  assign _00_ = lut_mem[addr];
  sky130_fd_sc_hd__dfxtp_1 _01_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(data[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _02_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(data[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _03_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(data[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _04_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(data[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _05_ (
    .CLK(clk),
    .D(_00_[4]),
    .Q(data[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _06_ (
    .CLK(clk),
    .D(_00_[5]),
    .Q(data[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _07_ (
    .CLK(clk),
    .D(_00_[6]),
    .Q(data[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _08_ (
    .CLK(clk),
    .D(_00_[7]),
    .Q(data[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _09_ (
    .CLK(clk),
    .D(_00_[8]),
    .Q(data[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _10_ (
    .CLK(clk),
    .D(_00_[9]),
    .Q(data[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _11_ (
    .CLK(clk),
    .D(_00_[10]),
    .Q(data[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _12_ (
    .CLK(clk),
    .D(_00_[11]),
    .Q(data[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _13_ (
    .CLK(clk),
    .D(_00_[12]),
    .Q(data[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _14_ (
    .CLK(clk),
    .D(_00_[13]),
    .Q(data[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _15_ (
    .CLK(clk),
    .D(_00_[14]),
    .Q(data[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _16_ (
    .CLK(clk),
    .D(_00_[15]),
    .Q(data[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _17_ (
    .CLK(clk),
    .D(_00_[16]),
    .Q(data[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _18_ (
    .CLK(clk),
    .D(_00_[17]),
    .Q(data[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _19_ (
    .CLK(clk),
    .D(_00_[18]),
    .Q(data[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _20_ (
    .CLK(clk),
    .D(_00_[19]),
    .Q(data[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _21_ (
    .CLK(clk),
    .D(_00_[20]),
    .Q(data[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _22_ (
    .CLK(clk),
    .D(_00_[21]),
    .Q(data[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _23_ (
    .CLK(clk),
    .D(_00_[22]),
    .Q(data[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _24_ (
    .CLK(clk),
    .D(_00_[23]),
    .Q(data[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _25_ (
    .CLK(clk),
    .D(_00_[24]),
    .Q(data[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _26_ (
    .CLK(clk),
    .D(_00_[25]),
    .Q(data[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _27_ (
    .CLK(clk),
    .D(_00_[26]),
    .Q(data[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _28_ (
    .CLK(clk),
    .D(_00_[27]),
    .Q(data[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _29_ (
    .CLK(clk),
    .D(_00_[28]),
    .Q(data[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _30_ (
    .CLK(clk),
    .D(_00_[29]),
    .Q(data[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _31_ (
    .CLK(clk),
    .D(_00_[30]),
    .Q(data[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _32_ (
    .CLK(clk),
    .D(_00_[31]),
    .Q(data[31])
  );
endmodule
