
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point cmd.seq_len[7] cmd[seq_len][7] -type PI PI
add mapped point cmd.seq_len[6] cmd[seq_len][6] -type PI PI
add mapped point cmd.seq_len[5] cmd[seq_len][5] -type PI PI
add mapped point cmd.seq_len[4] cmd[seq_len][4] -type PI PI
add mapped point cmd.seq_len[3] cmd[seq_len][3] -type PI PI
add mapped point cmd.seq_len[2] cmd[seq_len][2] -type PI PI
add mapped point cmd.seq_len[1] cmd[seq_len][1] -type PI PI
add mapped point cmd.seq_len[0] cmd[seq_len][0] -type PI PI
add mapped point cmd.tile_k[7] cmd[tile_k][7] -type PI PI
add mapped point cmd.tile_k[6] cmd[tile_k][6] -type PI PI
add mapped point cmd.tile_k[5] cmd[tile_k][5] -type PI PI
add mapped point cmd.tile_k[4] cmd[tile_k][4] -type PI PI
add mapped point cmd.tile_k[3] cmd[tile_k][3] -type PI PI
add mapped point cmd.tile_k[2] cmd[tile_k][2] -type PI PI
add mapped point cmd.tile_k[1] cmd[tile_k][1] -type PI PI
add mapped point cmd.tile_k[0] cmd[tile_k][0] -type PI PI
add mapped point cmd.tile_n[7] cmd[tile_n][7] -type PI PI
add mapped point cmd.tile_n[6] cmd[tile_n][6] -type PI PI
add mapped point cmd.tile_n[5] cmd[tile_n][5] -type PI PI
add mapped point cmd.tile_n[4] cmd[tile_n][4] -type PI PI
add mapped point cmd.tile_n[3] cmd[tile_n][3] -type PI PI
add mapped point cmd.tile_n[2] cmd[tile_n][2] -type PI PI
add mapped point cmd.tile_n[1] cmd[tile_n][1] -type PI PI
add mapped point cmd.tile_n[0] cmd[tile_n][0] -type PI PI
add mapped point cmd.tile_m[7] cmd[tile_m][7] -type PI PI
add mapped point cmd.tile_m[6] cmd[tile_m][6] -type PI PI
add mapped point cmd.tile_m[5] cmd[tile_m][5] -type PI PI
add mapped point cmd.tile_m[4] cmd[tile_m][4] -type PI PI
add mapped point cmd.tile_m[3] cmd[tile_m][3] -type PI PI
add mapped point cmd.tile_m[2] cmd[tile_m][2] -type PI PI
add mapped point cmd.tile_m[1] cmd[tile_m][1] -type PI PI
add mapped point cmd.tile_m[0] cmd[tile_m][0] -type PI PI
add mapped point cmd.addr_out[15] cmd[addr_out][15] -type PI PI
add mapped point cmd.addr_out[14] cmd[addr_out][14] -type PI PI
add mapped point cmd.addr_out[13] cmd[addr_out][13] -type PI PI
add mapped point cmd.addr_out[12] cmd[addr_out][12] -type PI PI
add mapped point cmd.addr_out[11] cmd[addr_out][11] -type PI PI
add mapped point cmd.addr_out[10] cmd[addr_out][10] -type PI PI
add mapped point cmd.addr_out[9] cmd[addr_out][9] -type PI PI
add mapped point cmd.addr_out[8] cmd[addr_out][8] -type PI PI
add mapped point cmd.addr_out[7] cmd[addr_out][7] -type PI PI
add mapped point cmd.addr_out[6] cmd[addr_out][6] -type PI PI
add mapped point cmd.addr_out[5] cmd[addr_out][5] -type PI PI
add mapped point cmd.addr_out[4] cmd[addr_out][4] -type PI PI
add mapped point cmd.addr_out[3] cmd[addr_out][3] -type PI PI
add mapped point cmd.addr_out[2] cmd[addr_out][2] -type PI PI
add mapped point cmd.addr_out[1] cmd[addr_out][1] -type PI PI
add mapped point cmd.addr_out[0] cmd[addr_out][0] -type PI PI
add mapped point cmd.addr_aux[15] cmd[addr_aux][15] -type PI PI
add mapped point cmd.addr_aux[14] cmd[addr_aux][14] -type PI PI
add mapped point cmd.addr_aux[13] cmd[addr_aux][13] -type PI PI
add mapped point cmd.addr_aux[12] cmd[addr_aux][12] -type PI PI
add mapped point cmd.addr_aux[11] cmd[addr_aux][11] -type PI PI
add mapped point cmd.addr_aux[10] cmd[addr_aux][10] -type PI PI
add mapped point cmd.addr_aux[9] cmd[addr_aux][9] -type PI PI
add mapped point cmd.addr_aux[8] cmd[addr_aux][8] -type PI PI
add mapped point cmd.addr_aux[7] cmd[addr_aux][7] -type PI PI
add mapped point cmd.addr_aux[6] cmd[addr_aux][6] -type PI PI
add mapped point cmd.addr_aux[5] cmd[addr_aux][5] -type PI PI
add mapped point cmd.addr_aux[4] cmd[addr_aux][4] -type PI PI
add mapped point cmd.addr_aux[3] cmd[addr_aux][3] -type PI PI
add mapped point cmd.addr_aux[2] cmd[addr_aux][2] -type PI PI
add mapped point cmd.addr_aux[1] cmd[addr_aux][1] -type PI PI
add mapped point cmd.addr_aux[0] cmd[addr_aux][0] -type PI PI
add mapped point cmd.addr_b[15] cmd[addr_b][15] -type PI PI
add mapped point cmd.addr_b[14] cmd[addr_b][14] -type PI PI
add mapped point cmd.addr_b[13] cmd[addr_b][13] -type PI PI
add mapped point cmd.addr_b[12] cmd[addr_b][12] -type PI PI
add mapped point cmd.addr_b[11] cmd[addr_b][11] -type PI PI
add mapped point cmd.addr_b[10] cmd[addr_b][10] -type PI PI
add mapped point cmd.addr_b[9] cmd[addr_b][9] -type PI PI
add mapped point cmd.addr_b[8] cmd[addr_b][8] -type PI PI
add mapped point cmd.addr_b[7] cmd[addr_b][7] -type PI PI
add mapped point cmd.addr_b[6] cmd[addr_b][6] -type PI PI
add mapped point cmd.addr_b[5] cmd[addr_b][5] -type PI PI
add mapped point cmd.addr_b[4] cmd[addr_b][4] -type PI PI
add mapped point cmd.addr_b[3] cmd[addr_b][3] -type PI PI
add mapped point cmd.addr_b[2] cmd[addr_b][2] -type PI PI
add mapped point cmd.addr_b[1] cmd[addr_b][1] -type PI PI
add mapped point cmd.addr_b[0] cmd[addr_b][0] -type PI PI
add mapped point cmd.addr_a[15] cmd[addr_a][15] -type PI PI
add mapped point cmd.addr_a[14] cmd[addr_a][14] -type PI PI
add mapped point cmd.addr_a[13] cmd[addr_a][13] -type PI PI
add mapped point cmd.addr_a[12] cmd[addr_a][12] -type PI PI
add mapped point cmd.addr_a[11] cmd[addr_a][11] -type PI PI
add mapped point cmd.addr_a[10] cmd[addr_a][10] -type PI PI
add mapped point cmd.addr_a[9] cmd[addr_a][9] -type PI PI
add mapped point cmd.addr_a[8] cmd[addr_a][8] -type PI PI
add mapped point cmd.addr_a[7] cmd[addr_a][7] -type PI PI
add mapped point cmd.addr_a[6] cmd[addr_a][6] -type PI PI
add mapped point cmd.addr_a[5] cmd[addr_a][5] -type PI PI
add mapped point cmd.addr_a[4] cmd[addr_a][4] -type PI PI
add mapped point cmd.addr_a[3] cmd[addr_a][3] -type PI PI
add mapped point cmd.addr_a[2] cmd[addr_a][2] -type PI PI
add mapped point cmd.addr_a[1] cmd[addr_a][1] -type PI PI
add mapped point cmd.addr_a[0] cmd[addr_a][0] -type PI PI
add mapped point cmd.mode[2] cmd[mode][2] -type PI PI
add mapped point cmd.mode[1] cmd[mode][1] -type PI PI
add mapped point cmd.mode[0] cmd[mode][0] -type PI PI
add mapped point cmd_valid cmd_valid -type PI PI
add mapped point sram_rdata[31] sram_rdata[31] -type PI PI
add mapped point sram_rdata[30] sram_rdata[30] -type PI PI
add mapped point sram_rdata[29] sram_rdata[29] -type PI PI
add mapped point sram_rdata[28] sram_rdata[28] -type PI PI
add mapped point sram_rdata[27] sram_rdata[27] -type PI PI
add mapped point sram_rdata[26] sram_rdata[26] -type PI PI
add mapped point sram_rdata[25] sram_rdata[25] -type PI PI
add mapped point sram_rdata[24] sram_rdata[24] -type PI PI
add mapped point sram_rdata[23] sram_rdata[23] -type PI PI
add mapped point sram_rdata[22] sram_rdata[22] -type PI PI
add mapped point sram_rdata[21] sram_rdata[21] -type PI PI
add mapped point sram_rdata[20] sram_rdata[20] -type PI PI
add mapped point sram_rdata[19] sram_rdata[19] -type PI PI
add mapped point sram_rdata[18] sram_rdata[18] -type PI PI
add mapped point sram_rdata[17] sram_rdata[17] -type PI PI
add mapped point sram_rdata[16] sram_rdata[16] -type PI PI
add mapped point sram_rdata[15] sram_rdata[15] -type PI PI
add mapped point sram_rdata[14] sram_rdata[14] -type PI PI
add mapped point sram_rdata[13] sram_rdata[13] -type PI PI
add mapped point sram_rdata[12] sram_rdata[12] -type PI PI
add mapped point sram_rdata[11] sram_rdata[11] -type PI PI
add mapped point sram_rdata[10] sram_rdata[10] -type PI PI
add mapped point sram_rdata[9] sram_rdata[9] -type PI PI
add mapped point sram_rdata[8] sram_rdata[8] -type PI PI
add mapped point sram_rdata[7] sram_rdata[7] -type PI PI
add mapped point sram_rdata[6] sram_rdata[6] -type PI PI
add mapped point sram_rdata[5] sram_rdata[5] -type PI PI
add mapped point sram_rdata[4] sram_rdata[4] -type PI PI
add mapped point sram_rdata[3] sram_rdata[3] -type PI PI
add mapped point sram_rdata[2] sram_rdata[2] -type PI PI
add mapped point sram_rdata[1] sram_rdata[1] -type PI PI
add mapped point sram_rdata[0] sram_rdata[0] -type PI PI
add mapped point sram_rvalid sram_rvalid -type PI PI
add mapped point out_rd_data[31] out_rd_data[31] -type PI PI
add mapped point out_rd_data[30] out_rd_data[30] -type PI PI
add mapped point out_rd_data[29] out_rd_data[29] -type PI PI
add mapped point out_rd_data[28] out_rd_data[28] -type PI PI
add mapped point out_rd_data[27] out_rd_data[27] -type PI PI
add mapped point out_rd_data[26] out_rd_data[26] -type PI PI
add mapped point out_rd_data[25] out_rd_data[25] -type PI PI
add mapped point out_rd_data[24] out_rd_data[24] -type PI PI
add mapped point out_rd_data[23] out_rd_data[23] -type PI PI
add mapped point out_rd_data[22] out_rd_data[22] -type PI PI
add mapped point out_rd_data[21] out_rd_data[21] -type PI PI
add mapped point out_rd_data[20] out_rd_data[20] -type PI PI
add mapped point out_rd_data[19] out_rd_data[19] -type PI PI
add mapped point out_rd_data[18] out_rd_data[18] -type PI PI
add mapped point out_rd_data[17] out_rd_data[17] -type PI PI
add mapped point out_rd_data[16] out_rd_data[16] -type PI PI
add mapped point out_rd_data[15] out_rd_data[15] -type PI PI
add mapped point out_rd_data[14] out_rd_data[14] -type PI PI
add mapped point out_rd_data[13] out_rd_data[13] -type PI PI
add mapped point out_rd_data[12] out_rd_data[12] -type PI PI
add mapped point out_rd_data[11] out_rd_data[11] -type PI PI
add mapped point out_rd_data[10] out_rd_data[10] -type PI PI
add mapped point out_rd_data[9] out_rd_data[9] -type PI PI
add mapped point out_rd_data[8] out_rd_data[8] -type PI PI
add mapped point out_rd_data[7] out_rd_data[7] -type PI PI
add mapped point out_rd_data[6] out_rd_data[6] -type PI PI
add mapped point out_rd_data[5] out_rd_data[5] -type PI PI
add mapped point out_rd_data[4] out_rd_data[4] -type PI PI
add mapped point out_rd_data[3] out_rd_data[3] -type PI PI
add mapped point out_rd_data[2] out_rd_data[2] -type PI PI
add mapped point out_rd_data[1] out_rd_data[1] -type PI PI
add mapped point out_rd_data[0] out_rd_data[0] -type PI PI
add mapped point pipeline_done pipeline_done -type PI PI

//output ports
add mapped point cmd_ready cmd_ready -type PO PO
add mapped point cmd_tile_m[7] cmd_tile_m[7] -type PO PO
add mapped point cmd_tile_m[6] cmd_tile_m[6] -type PO PO
add mapped point cmd_tile_m[5] cmd_tile_m[5] -type PO PO
add mapped point cmd_tile_m[4] cmd_tile_m[4] -type PO PO
add mapped point cmd_tile_m[3] cmd_tile_m[3] -type PO PO
add mapped point cmd_tile_m[2] cmd_tile_m[2] -type PO PO
add mapped point cmd_tile_m[1] cmd_tile_m[1] -type PO PO
add mapped point cmd_tile_m[0] cmd_tile_m[0] -type PO PO
add mapped point cmd_tile_n[7] cmd_tile_n[7] -type PO PO
add mapped point cmd_tile_n[6] cmd_tile_n[6] -type PO PO
add mapped point cmd_tile_n[5] cmd_tile_n[5] -type PO PO
add mapped point cmd_tile_n[4] cmd_tile_n[4] -type PO PO
add mapped point cmd_tile_n[3] cmd_tile_n[3] -type PO PO
add mapped point cmd_tile_n[2] cmd_tile_n[2] -type PO PO
add mapped point cmd_tile_n[1] cmd_tile_n[1] -type PO PO
add mapped point cmd_tile_n[0] cmd_tile_n[0] -type PO PO
add mapped point cmd_tile_k[7] cmd_tile_k[7] -type PO PO
add mapped point cmd_tile_k[6] cmd_tile_k[6] -type PO PO
add mapped point cmd_tile_k[5] cmd_tile_k[5] -type PO PO
add mapped point cmd_tile_k[4] cmd_tile_k[4] -type PO PO
add mapped point cmd_tile_k[3] cmd_tile_k[3] -type PO PO
add mapped point cmd_tile_k[2] cmd_tile_k[2] -type PO PO
add mapped point cmd_tile_k[1] cmd_tile_k[1] -type PO PO
add mapped point cmd_tile_k[0] cmd_tile_k[0] -type PO PO
add mapped point fused_sel[2] fused_sel[2] -type PO PO
add mapped point fused_sel[1] fused_sel[1] -type PO PO
add mapped point fused_sel[0] fused_sel[0] -type PO PO
add mapped point sram_req sram_req -type PO PO
add mapped point sram_we sram_we -type PO PO
add mapped point sram_addr[15] sram_addr[15] -type PO PO
add mapped point sram_addr[14] sram_addr[14] -type PO PO
add mapped point sram_addr[13] sram_addr[13] -type PO PO
add mapped point sram_addr[12] sram_addr[12] -type PO PO
add mapped point sram_addr[11] sram_addr[11] -type PO PO
add mapped point sram_addr[10] sram_addr[10] -type PO PO
add mapped point sram_addr[9] sram_addr[9] -type PO PO
add mapped point sram_addr[8] sram_addr[8] -type PO PO
add mapped point sram_addr[7] sram_addr[7] -type PO PO
add mapped point sram_addr[6] sram_addr[6] -type PO PO
add mapped point sram_addr[5] sram_addr[5] -type PO PO
add mapped point sram_addr[4] sram_addr[4] -type PO PO
add mapped point sram_addr[3] sram_addr[3] -type PO PO
add mapped point sram_addr[2] sram_addr[2] -type PO PO
add mapped point sram_addr[1] sram_addr[1] -type PO PO
add mapped point sram_addr[0] sram_addr[0] -type PO PO
add mapped point sram_wdata[31] sram_wdata[31] -type PO PO
add mapped point sram_wdata[30] sram_wdata[30] -type PO PO
add mapped point sram_wdata[29] sram_wdata[29] -type PO PO
add mapped point sram_wdata[28] sram_wdata[28] -type PO PO
add mapped point sram_wdata[27] sram_wdata[27] -type PO PO
add mapped point sram_wdata[26] sram_wdata[26] -type PO PO
add mapped point sram_wdata[25] sram_wdata[25] -type PO PO
add mapped point sram_wdata[24] sram_wdata[24] -type PO PO
add mapped point sram_wdata[23] sram_wdata[23] -type PO PO
add mapped point sram_wdata[22] sram_wdata[22] -type PO PO
add mapped point sram_wdata[21] sram_wdata[21] -type PO PO
add mapped point sram_wdata[20] sram_wdata[20] -type PO PO
add mapped point sram_wdata[19] sram_wdata[19] -type PO PO
add mapped point sram_wdata[18] sram_wdata[18] -type PO PO
add mapped point sram_wdata[17] sram_wdata[17] -type PO PO
add mapped point sram_wdata[16] sram_wdata[16] -type PO PO
add mapped point sram_wdata[15] sram_wdata[15] -type PO PO
add mapped point sram_wdata[14] sram_wdata[14] -type PO PO
add mapped point sram_wdata[13] sram_wdata[13] -type PO PO
add mapped point sram_wdata[12] sram_wdata[12] -type PO PO
add mapped point sram_wdata[11] sram_wdata[11] -type PO PO
add mapped point sram_wdata[10] sram_wdata[10] -type PO PO
add mapped point sram_wdata[9] sram_wdata[9] -type PO PO
add mapped point sram_wdata[8] sram_wdata[8] -type PO PO
add mapped point sram_wdata[7] sram_wdata[7] -type PO PO
add mapped point sram_wdata[6] sram_wdata[6] -type PO PO
add mapped point sram_wdata[5] sram_wdata[5] -type PO PO
add mapped point sram_wdata[4] sram_wdata[4] -type PO PO
add mapped point sram_wdata[3] sram_wdata[3] -type PO PO
add mapped point sram_wdata[2] sram_wdata[2] -type PO PO
add mapped point sram_wdata[1] sram_wdata[1] -type PO PO
add mapped point sram_wdata[0] sram_wdata[0] -type PO PO
add mapped point buf_a_wr_en buf_a_wr_en -type PO PO
add mapped point buf_b_wr_en buf_b_wr_en -type PO PO
add mapped point buf_aux_wr_en buf_aux_wr_en -type PO PO
add mapped point buf_wr_idx[11] buf_wr_idx[11] -type PO PO
add mapped point buf_wr_idx[10] buf_wr_idx[10] -type PO PO
add mapped point buf_wr_idx[9] buf_wr_idx[9] -type PO PO
add mapped point buf_wr_idx[8] buf_wr_idx[8] -type PO PO
add mapped point buf_wr_idx[7] buf_wr_idx[7] -type PO PO
add mapped point buf_wr_idx[6] buf_wr_idx[6] -type PO PO
add mapped point buf_wr_idx[5] buf_wr_idx[5] -type PO PO
add mapped point buf_wr_idx[4] buf_wr_idx[4] -type PO PO
add mapped point buf_wr_idx[3] buf_wr_idx[3] -type PO PO
add mapped point buf_wr_idx[2] buf_wr_idx[2] -type PO PO
add mapped point buf_wr_idx[1] buf_wr_idx[1] -type PO PO
add mapped point buf_wr_idx[0] buf_wr_idx[0] -type PO PO
add mapped point buf_wr_data[31] buf_wr_data[31] -type PO PO
add mapped point buf_wr_data[30] buf_wr_data[30] -type PO PO
add mapped point buf_wr_data[29] buf_wr_data[29] -type PO PO
add mapped point buf_wr_data[28] buf_wr_data[28] -type PO PO
add mapped point buf_wr_data[27] buf_wr_data[27] -type PO PO
add mapped point buf_wr_data[26] buf_wr_data[26] -type PO PO
add mapped point buf_wr_data[25] buf_wr_data[25] -type PO PO
add mapped point buf_wr_data[24] buf_wr_data[24] -type PO PO
add mapped point buf_wr_data[23] buf_wr_data[23] -type PO PO
add mapped point buf_wr_data[22] buf_wr_data[22] -type PO PO
add mapped point buf_wr_data[21] buf_wr_data[21] -type PO PO
add mapped point buf_wr_data[20] buf_wr_data[20] -type PO PO
add mapped point buf_wr_data[19] buf_wr_data[19] -type PO PO
add mapped point buf_wr_data[18] buf_wr_data[18] -type PO PO
add mapped point buf_wr_data[17] buf_wr_data[17] -type PO PO
add mapped point buf_wr_data[16] buf_wr_data[16] -type PO PO
add mapped point buf_wr_data[15] buf_wr_data[15] -type PO PO
add mapped point buf_wr_data[14] buf_wr_data[14] -type PO PO
add mapped point buf_wr_data[13] buf_wr_data[13] -type PO PO
add mapped point buf_wr_data[12] buf_wr_data[12] -type PO PO
add mapped point buf_wr_data[11] buf_wr_data[11] -type PO PO
add mapped point buf_wr_data[10] buf_wr_data[10] -type PO PO
add mapped point buf_wr_data[9] buf_wr_data[9] -type PO PO
add mapped point buf_wr_data[8] buf_wr_data[8] -type PO PO
add mapped point buf_wr_data[7] buf_wr_data[7] -type PO PO
add mapped point buf_wr_data[6] buf_wr_data[6] -type PO PO
add mapped point buf_wr_data[5] buf_wr_data[5] -type PO PO
add mapped point buf_wr_data[4] buf_wr_data[4] -type PO PO
add mapped point buf_wr_data[3] buf_wr_data[3] -type PO PO
add mapped point buf_wr_data[2] buf_wr_data[2] -type PO PO
add mapped point buf_wr_data[1] buf_wr_data[1] -type PO PO
add mapped point buf_wr_data[0] buf_wr_data[0] -type PO PO
add mapped point out_rd_idx[11] out_rd_idx[11] -type PO PO
add mapped point out_rd_idx[10] out_rd_idx[10] -type PO PO
add mapped point out_rd_idx[9] out_rd_idx[9] -type PO PO
add mapped point out_rd_idx[8] out_rd_idx[8] -type PO PO
add mapped point out_rd_idx[7] out_rd_idx[7] -type PO PO
add mapped point out_rd_idx[6] out_rd_idx[6] -type PO PO
add mapped point out_rd_idx[5] out_rd_idx[5] -type PO PO
add mapped point out_rd_idx[4] out_rd_idx[4] -type PO PO
add mapped point out_rd_idx[3] out_rd_idx[3] -type PO PO
add mapped point out_rd_idx[2] out_rd_idx[2] -type PO PO
add mapped point out_rd_idx[1] out_rd_idx[1] -type PO PO
add mapped point out_rd_idx[0] out_rd_idx[0] -type PO PO
add mapped point pipeline_start pipeline_start -type PO PO
add mapped point busy busy -type PO PO
add mapped point done done -type PO PO

//inout ports




//Sequential Pins
add mapped point cmd_reg.addr_a[0]/q cmd_reg_reg[addr_a][0]/Q  -type DFF DFF
add mapped point cmd_reg.addr_a[1]/q cmd_reg_reg[addr_a][1]/Q  -type DFF DFF
add mapped point cmd_reg.addr_a[2]/q cmd_reg_reg[addr_a][2]/Q  -type DFF DFF
add mapped point cmd_reg.addr_a[3]/q cmd_reg_reg[addr_a][3]/Q  -type DFF DFF
add mapped point cmd_reg.addr_a[4]/q cmd_reg_reg[addr_a][4]/Q  -type DFF DFF
add mapped point cmd_reg.addr_a[5]/q cmd_reg_reg[addr_a][5]/Q  -type DFF DFF
add mapped point cmd_reg.addr_a[6]/q cmd_reg_reg[addr_a][6]/Q  -type DFF DFF
add mapped point cmd_reg.addr_a[7]/q cmd_reg_reg[addr_a][7]/Q  -type DFF DFF
add mapped point cmd_reg.addr_a[8]/q cmd_reg_reg[addr_a][8]/Q  -type DFF DFF
add mapped point cmd_reg.addr_a[9]/q cmd_reg_reg[addr_a][9]/Q  -type DFF DFF
add mapped point cmd_reg.addr_a[10]/q cmd_reg_reg[addr_a][10]/Q  -type DFF DFF
add mapped point cmd_reg.addr_a[11]/q cmd_reg_reg[addr_a][11]/Q  -type DFF DFF
add mapped point cmd_reg.addr_a[12]/q cmd_reg_reg[addr_a][12]/Q  -type DFF DFF
add mapped point cmd_reg.addr_a[13]/q cmd_reg_reg[addr_a][13]/Q  -type DFF DFF
add mapped point cmd_reg.addr_a[14]/q cmd_reg_reg[addr_a][14]/Q  -type DFF DFF
add mapped point cmd_reg.addr_a[15]/q cmd_reg_reg[addr_a][15]/Q  -type DFF DFF
add mapped point cmd_reg.addr_aux[0]/q cmd_reg_reg[addr_aux][0]/Q  -type DFF DFF
add mapped point cmd_reg.addr_aux[1]/q cmd_reg_reg[addr_aux][1]/Q  -type DFF DFF
add mapped point cmd_reg.addr_aux[2]/q cmd_reg_reg[addr_aux][2]/Q  -type DFF DFF
add mapped point cmd_reg.addr_aux[3]/q cmd_reg_reg[addr_aux][3]/Q  -type DFF DFF
add mapped point cmd_reg.addr_aux[4]/q cmd_reg_reg[addr_aux][4]/Q  -type DFF DFF
add mapped point cmd_reg.addr_aux[5]/q cmd_reg_reg[addr_aux][5]/Q  -type DFF DFF
add mapped point cmd_reg.addr_aux[6]/q cmd_reg_reg[addr_aux][6]/Q  -type DFF DFF
add mapped point cmd_reg.addr_aux[7]/q cmd_reg_reg[addr_aux][7]/Q  -type DFF DFF
add mapped point cmd_reg.addr_aux[8]/q cmd_reg_reg[addr_aux][8]/Q  -type DFF DFF
add mapped point cmd_reg.addr_aux[9]/q cmd_reg_reg[addr_aux][9]/Q  -type DFF DFF
add mapped point cmd_reg.addr_aux[10]/q cmd_reg_reg[addr_aux][10]/Q  -type DFF DFF
add mapped point cmd_reg.addr_aux[11]/q cmd_reg_reg[addr_aux][11]/Q  -type DFF DFF
add mapped point cmd_reg.addr_aux[12]/q cmd_reg_reg[addr_aux][12]/Q  -type DFF DFF
add mapped point cmd_reg.addr_aux[13]/q cmd_reg_reg[addr_aux][13]/Q  -type DFF DFF
add mapped point cmd_reg.addr_aux[14]/q cmd_reg_reg[addr_aux][14]/Q  -type DFF DFF
add mapped point cmd_reg.addr_aux[15]/q cmd_reg_reg[addr_aux][15]/Q  -type DFF DFF
add mapped point cmd_reg.addr_b[0]/q cmd_reg_reg[addr_b][0]/Q  -type DFF DFF
add mapped point cmd_reg.addr_b[1]/q cmd_reg_reg[addr_b][1]/Q  -type DFF DFF
add mapped point cmd_reg.addr_b[2]/q cmd_reg_reg[addr_b][2]/Q  -type DFF DFF
add mapped point cmd_reg.addr_b[3]/q cmd_reg_reg[addr_b][3]/Q  -type DFF DFF
add mapped point cmd_reg.addr_b[4]/q cmd_reg_reg[addr_b][4]/Q  -type DFF DFF
add mapped point cmd_reg.addr_b[5]/q cmd_reg_reg[addr_b][5]/Q  -type DFF DFF
add mapped point cmd_reg.addr_b[6]/q cmd_reg_reg[addr_b][6]/Q  -type DFF DFF
add mapped point cmd_reg.addr_b[7]/q cmd_reg_reg[addr_b][7]/Q  -type DFF DFF
add mapped point cmd_reg.addr_b[8]/q cmd_reg_reg[addr_b][8]/Q  -type DFF DFF
add mapped point cmd_reg.addr_b[9]/q cmd_reg_reg[addr_b][9]/Q  -type DFF DFF
add mapped point cmd_reg.addr_b[10]/q cmd_reg_reg[addr_b][10]/Q  -type DFF DFF
add mapped point cmd_reg.addr_b[11]/q cmd_reg_reg[addr_b][11]/Q  -type DFF DFF
add mapped point cmd_reg.addr_b[12]/q cmd_reg_reg[addr_b][12]/Q  -type DFF DFF
add mapped point cmd_reg.addr_b[13]/q cmd_reg_reg[addr_b][13]/Q  -type DFF DFF
add mapped point cmd_reg.addr_b[14]/q cmd_reg_reg[addr_b][14]/Q  -type DFF DFF
add mapped point cmd_reg.addr_b[15]/q cmd_reg_reg[addr_b][15]/Q  -type DFF DFF
add mapped point cmd_reg.addr_out[0]/q cmd_reg_reg[addr_out][0]/Q  -type DFF DFF
add mapped point cmd_reg.addr_out[1]/q cmd_reg_reg[addr_out][1]/Q  -type DFF DFF
add mapped point cmd_reg.addr_out[2]/q cmd_reg_reg[addr_out][2]/Q  -type DFF DFF
add mapped point cmd_reg.addr_out[3]/q cmd_reg_reg[addr_out][3]/Q  -type DFF DFF
add mapped point cmd_reg.addr_out[4]/q cmd_reg_reg[addr_out][4]/Q  -type DFF DFF
add mapped point cmd_reg.addr_out[5]/q cmd_reg_reg[addr_out][5]/Q  -type DFF DFF
add mapped point cmd_reg.addr_out[6]/q cmd_reg_reg[addr_out][6]/Q  -type DFF DFF
add mapped point cmd_reg.addr_out[7]/q cmd_reg_reg[addr_out][7]/Q  -type DFF DFF
add mapped point cmd_reg.addr_out[8]/q cmd_reg_reg[addr_out][8]/Q  -type DFF DFF
add mapped point cmd_reg.addr_out[9]/q cmd_reg_reg[addr_out][9]/Q  -type DFF DFF
add mapped point cmd_reg.addr_out[10]/q cmd_reg_reg[addr_out][10]/Q  -type DFF DFF
add mapped point cmd_reg.addr_out[11]/q cmd_reg_reg[addr_out][11]/Q  -type DFF DFF
add mapped point cmd_reg.addr_out[12]/q cmd_reg_reg[addr_out][12]/Q  -type DFF DFF
add mapped point cmd_reg.addr_out[13]/q cmd_reg_reg[addr_out][13]/Q  -type DFF DFF
add mapped point cmd_reg.addr_out[14]/q cmd_reg_reg[addr_out][14]/Q  -type DFF DFF
add mapped point cmd_reg.addr_out[15]/q cmd_reg_reg[addr_out][15]/Q  -type DFF DFF
add mapped point cmd_reg.mode[0]/q cmd_reg_reg[mode][0]/Q  -type DFF DFF
add mapped point cmd_reg.mode[1]/q cmd_reg_reg[mode][1]/Q  -type DFF DFF
add mapped point cmd_reg.mode[2]/q cmd_reg_reg[mode][2]/Q  -type DFF DFF
add mapped point cmd_reg.tile_k[0]/q cmd_reg_reg[tile_k][0]/Q  -type DFF DFF
add mapped point cmd_reg.tile_k[1]/q cmd_reg_reg[tile_k][1]/Q  -type DFF DFF
add mapped point cmd_reg.tile_k[2]/q cmd_reg_reg[tile_k][2]/Q  -type DFF DFF
add mapped point cmd_reg.tile_k[3]/q cmd_reg_reg[tile_k][3]/Q  -type DFF DFF
add mapped point cmd_reg.tile_k[4]/q cmd_reg_reg[tile_k][4]/Q  -type DFF DFF
add mapped point cmd_reg.tile_k[5]/q cmd_reg_reg[tile_k][5]/Q  -type DFF DFF
add mapped point cmd_reg.tile_k[6]/q cmd_reg_reg[tile_k][6]/Q  -type DFF DFF
add mapped point cmd_reg.tile_k[7]/q cmd_reg_reg[tile_k][7]/Q  -type DFF DFF
add mapped point cmd_reg.tile_m[0]/q cmd_reg_reg[tile_m][0]/Q  -type DFF DFF
add mapped point cmd_reg.tile_m[1]/q cmd_reg_reg[tile_m][1]/Q  -type DFF DFF
add mapped point cmd_reg.tile_m[2]/q cmd_reg_reg[tile_m][2]/Q  -type DFF DFF
add mapped point cmd_reg.tile_m[3]/q cmd_reg_reg[tile_m][3]/Q  -type DFF DFF
add mapped point cmd_reg.tile_m[4]/q cmd_reg_reg[tile_m][4]/Q  -type DFF DFF
add mapped point cmd_reg.tile_m[5]/q cmd_reg_reg[tile_m][5]/Q  -type DFF DFF
add mapped point cmd_reg.tile_m[6]/q cmd_reg_reg[tile_m][6]/Q  -type DFF DFF
add mapped point cmd_reg.tile_m[7]/q cmd_reg_reg[tile_m][7]/Q  -type DFF DFF
add mapped point cmd_reg.tile_n[0]/q cmd_reg_reg[tile_n][0]/Q  -type DFF DFF
add mapped point cmd_reg.tile_n[1]/q cmd_reg_reg[tile_n][1]/Q  -type DFF DFF
add mapped point cmd_reg.tile_n[2]/q cmd_reg_reg[tile_n][2]/Q  -type DFF DFF
add mapped point cmd_reg.tile_n[3]/q cmd_reg_reg[tile_n][3]/Q  -type DFF DFF
add mapped point cmd_reg.tile_n[4]/q cmd_reg_reg[tile_n][4]/Q  -type DFF DFF
add mapped point cmd_reg.tile_n[5]/q cmd_reg_reg[tile_n][5]/Q  -type DFF DFF
add mapped point cmd_reg.tile_n[6]/q cmd_reg_reg[tile_n][6]/Q  -type DFF DFF
add mapped point cmd_reg.tile_n[7]/q cmd_reg_reg[tile_n][7]/Q  -type DFF DFF
add mapped point load_cnt[0]/q load_cnt_reg[0]/Q  -type DFF DFF
add mapped point load_cnt[1]/q load_cnt_reg[1]/Q  -type DFF DFF
add mapped point load_cnt[2]/q load_cnt_reg[2]/Q  -type DFF DFF
add mapped point load_cnt[3]/q load_cnt_reg[3]/Q  -type DFF DFF
add mapped point load_cnt[4]/q load_cnt_reg[4]/Q  -type DFF DFF
add mapped point load_cnt[5]/q load_cnt_reg[5]/Q  -type DFF DFF
add mapped point load_cnt[6]/q load_cnt_reg[6]/Q  -type DFF DFF
add mapped point load_cnt[7]/q load_cnt_reg[7]/Q  -type DFF DFF
add mapped point load_cnt[8]/q load_cnt_reg[8]/Q  -type DFF DFF
add mapped point load_cnt[9]/q load_cnt_reg[9]/Q  -type DFF DFF
add mapped point load_cnt[10]/q load_cnt_reg[10]/Q  -type DFF DFF
add mapped point load_cnt[11]/q load_cnt_reg[11]/Q  -type DFF DFF
add mapped point load_col[0]/q load_col_reg[0]/Q  -type DFF DFF
add mapped point load_col[1]/q load_col_reg[1]/Q  -type DFF DFF
add mapped point load_col[2]/q load_col_reg[2]/Q  -type DFF DFF
add mapped point load_col[3]/q load_col_reg[3]/Q  -type DFF DFF
add mapped point load_col[4]/q load_col_reg[4]/Q  -type DFF DFF
add mapped point load_col[5]/q load_col_reg[5]/Q  -type DFF DFF
add mapped point load_col[6]/q load_col_reg[6]/Q  -type DFF DFF
add mapped point load_col[7]/q load_col_reg[7]/Q  -type DFF DFF
add mapped point load_row[0]/q load_row_reg[0]/Q  -type DFF DFF
add mapped point load_row[1]/q load_row_reg[1]/Q  -type DFF DFF
add mapped point load_row[2]/q load_row_reg[2]/Q  -type DFF DFF
add mapped point load_row[3]/q load_row_reg[3]/Q  -type DFF DFF
add mapped point load_row[4]/q load_row_reg[4]/Q  -type DFF DFF
add mapped point load_row[5]/q load_row_reg[5]/Q  -type DFF DFF
add mapped point state[0]/q state_reg[0]/Q  -type DFF DFF
add mapped point state[1]/q state_reg[1]/Q  -type DFF DFF
add mapped point state[2]/q state_reg[2]/Q  -type DFF DFF
add mapped point wr_col[0]/q wr_col_reg[0]/Q  -type DFF DFF
add mapped point wr_col[1]/q wr_col_reg[1]/Q  -type DFF DFF
add mapped point wr_col[2]/q wr_col_reg[2]/Q  -type DFF DFF
add mapped point wr_col[3]/q wr_col_reg[3]/Q  -type DFF DFF
add mapped point wr_col[4]/q wr_col_reg[4]/Q  -type DFF DFF
add mapped point wr_col[5]/q wr_col_reg[5]/Q  -type DFF DFF
add mapped point wr_col[6]/q wr_col_reg[6]/Q  -type DFF DFF
add mapped point wr_col[7]/q wr_col_reg[7]/Q  -type DFF DFF
add mapped point wr_row[0]/q wr_row_reg[0]/Q  -type DFF DFF
add mapped point wr_row[1]/q wr_row_reg[1]/Q  -type DFF DFF
add mapped point wr_row[2]/q wr_row_reg[2]/Q  -type DFF DFF
add mapped point wr_row[3]/q wr_row_reg[3]/Q  -type DFF DFF
add mapped point wr_row[4]/q wr_row_reg[4]/Q  -type DFF DFF
add mapped point wr_row[5]/q wr_row_reg[5]/Q  -type DFF DFF
add mapped point write_cnt[0]/q write_cnt_reg[0]/Q  -type DFF DFF
add mapped point write_cnt[1]/q write_cnt_reg[1]/Q  -type DFF DFF
add mapped point write_cnt[2]/q write_cnt_reg[2]/Q  -type DFF DFF
add mapped point write_cnt[3]/q write_cnt_reg[3]/Q  -type DFF DFF
add mapped point write_cnt[4]/q write_cnt_reg[4]/Q  -type DFF DFF
add mapped point write_cnt[5]/q write_cnt_reg[5]/Q  -type DFF DFF
add mapped point write_cnt[6]/q write_cnt_reg[6]/Q  -type DFF DFF
add mapped point write_cnt[7]/q write_cnt_reg[7]/Q  -type DFF DFF
add mapped point write_cnt[8]/q write_cnt_reg[8]/Q  -type DFF DFF
add mapped point write_cnt[9]/q write_cnt_reg[9]/Q  -type DFF DFF
add mapped point write_cnt[10]/q write_cnt_reg[10]/Q  -type DFF DFF
add mapped point write_cnt[11]/q write_cnt_reg[11]/Q  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
