/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module skid_buffer(clk, rst_n, in_data, in_valid, in_ready, out_data, out_valid, out_ready);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  input clk;
  wire clk;
  input [31:0] in_data;
  wire [31:0] in_data;
  output in_ready;
  wire in_ready;
  input in_valid;
  wire in_valid;
  output [31:0] out_data;
  wire [31:0] out_data;
  input out_ready;
  wire out_ready;
  output out_valid;
  wire out_valid;
  input rst_n;
  wire rst_n;
  wire [31:0] skid_data;
  wire skid_valid;
  sky130_fd_sc_hd__clkinv_1 _264_ (
    .A(skid_data[0]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand3b_1 _265_ (
    .A_N(skid_valid),
    .B(out_valid),
    .C(in_valid),
    .Y(_067_)
  );
  sky130_fd_sc_hd__o21bai_1 _266_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_066_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__clkinv_1 _267_ (
    .A(skid_valid),
    .Y(in_ready)
  );
  sky130_fd_sc_hd__and2b_2 _268_ (
    .A_N(out_ready),
    .B(out_valid),
    .X(_069_)
  );
  sky130_fd_sc_hd__nand4_1 _269_ (
    .A(_069_),
    .B(in_data[0]),
    .C(in_ready),
    .D(in_valid),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(_068_),
    .B(_070_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _271_ (
    .A(skid_data[1]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__o21bai_1 _272_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand4_1 _273_ (
    .A(_069_),
    .B(in_data[1]),
    .C(in_ready),
    .D(in_valid),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _274_ (
    .A(_072_),
    .B(_073_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _275_ (
    .A(skid_data[2]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o21bai_1 _276_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand4_1 _277_ (
    .A(_069_),
    .B(in_data[2]),
    .C(in_ready),
    .D(in_valid),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _278_ (
    .A(_075_),
    .B(_076_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _279_ (
    .A(skid_data[3]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__o21bai_1 _280_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_077_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand4_1 _281_ (
    .A(_069_),
    .B(in_data[3]),
    .C(in_ready),
    .D(in_valid),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2_1 _282_ (
    .A(_078_),
    .B(_079_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _283_ (
    .A(skid_data[4]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__o21bai_1 _284_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_080_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand4_1 _285_ (
    .A(_069_),
    .B(in_data[4]),
    .C(in_ready),
    .D(in_valid),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand2_1 _286_ (
    .A(_081_),
    .B(_082_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _287_ (
    .A(skid_data[5]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__o21bai_1 _288_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand4_1 _289_ (
    .A(_069_),
    .B(in_data[5]),
    .C(in_ready),
    .D(in_valid),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _290_ (
    .A(_084_),
    .B(_085_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _291_ (
    .A(skid_data[6]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__o21bai_1 _292_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_086_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand4_1 _293_ (
    .A(_069_),
    .B(in_data[6]),
    .C(in_ready),
    .D(in_valid),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _294_ (
    .A(_087_),
    .B(_088_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _295_ (
    .A(skid_data[7]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__o21bai_1 _296_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand4_1 _297_ (
    .A(_069_),
    .B(in_data[7]),
    .C(in_ready),
    .D(in_valid),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand2_1 _298_ (
    .A(_090_),
    .B(_091_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _299_ (
    .A(skid_data[8]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__o21bai_1 _300_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand4_1 _301_ (
    .A(_069_),
    .B(in_data[8]),
    .C(in_ready),
    .D(in_valid),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand2_1 _302_ (
    .A(_093_),
    .B(_094_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _303_ (
    .A(skid_data[9]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__o21bai_1 _304_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand4_1 _305_ (
    .A(_069_),
    .B(in_data[9]),
    .C(in_ready),
    .D(in_valid),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2_1 _306_ (
    .A(_096_),
    .B(_097_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _307_ (
    .A(skid_data[10]),
    .Y(_098_)
  );
  sky130_fd_sc_hd__o21bai_1 _308_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand4_1 _309_ (
    .A(_069_),
    .B(in_data[10]),
    .C(in_ready),
    .D(in_valid),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _310_ (
    .A(_099_),
    .B(_100_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _311_ (
    .A(skid_data[11]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__o21bai_1 _312_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand4_1 _313_ (
    .A(_069_),
    .B(in_data[11]),
    .C(in_ready),
    .D(in_valid),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _314_ (
    .A(_102_),
    .B(_103_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _315_ (
    .A(skid_data[12]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o21bai_1 _316_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_104_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand4_1 _317_ (
    .A(_069_),
    .B(in_data[12]),
    .C(in_ready),
    .D(in_valid),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _318_ (
    .A(_105_),
    .B(_106_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _319_ (
    .A(skid_data[13]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__o21bai_1 _320_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nand4_1 _321_ (
    .A(_069_),
    .B(in_data[13]),
    .C(in_ready),
    .D(in_valid),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _322_ (
    .A(_108_),
    .B(_109_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _323_ (
    .A(skid_data[14]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__o21bai_1 _324_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_110_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nand4_1 _325_ (
    .A(_069_),
    .B(in_data[14]),
    .C(in_ready),
    .D(in_valid),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand2_1 _326_ (
    .A(_111_),
    .B(_112_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _327_ (
    .A(skid_data[15]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__o21bai_1 _328_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nand4_1 _329_ (
    .A(_069_),
    .B(in_data[15]),
    .C(in_ready),
    .D(in_valid),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nand2_1 _330_ (
    .A(_114_),
    .B(_115_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _331_ (
    .A(skid_data[16]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__o21bai_1 _332_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_116_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand4_1 _333_ (
    .A(_069_),
    .B(in_data[16]),
    .C(in_ready),
    .D(in_valid),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nand2_1 _334_ (
    .A(_117_),
    .B(_118_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__clkinv_1 _335_ (
    .A(skid_data[17]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__o21bai_1 _336_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand4_1 _337_ (
    .A(_069_),
    .B(in_data[17]),
    .C(in_ready),
    .D(in_valid),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand2_1 _338_ (
    .A(_120_),
    .B(_121_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__clkinv_1 _339_ (
    .A(skid_data[18]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__o21bai_1 _340_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_122_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand4_1 _341_ (
    .A(_069_),
    .B(in_data[18]),
    .C(in_ready),
    .D(in_valid),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nand2_1 _342_ (
    .A(_123_),
    .B(_124_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__clkinv_1 _343_ (
    .A(skid_data[19]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__o21bai_1 _344_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand4_1 _345_ (
    .A(_069_),
    .B(in_data[19]),
    .C(in_ready),
    .D(in_valid),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nand2_1 _346_ (
    .A(_126_),
    .B(_127_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _347_ (
    .A(skid_data[20]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__o21bai_1 _348_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand4_1 _349_ (
    .A(_069_),
    .B(in_data[20]),
    .C(in_ready),
    .D(in_valid),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand2_1 _350_ (
    .A(_129_),
    .B(_130_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _351_ (
    .A(skid_data[21]),
    .Y(_131_)
  );
  sky130_fd_sc_hd__o21bai_1 _352_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand4_1 _353_ (
    .A(_069_),
    .B(in_data[21]),
    .C(in_ready),
    .D(in_valid),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nand2_1 _354_ (
    .A(_132_),
    .B(_133_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__clkinv_1 _355_ (
    .A(skid_data[22]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__o21bai_1 _356_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nand4_1 _357_ (
    .A(_069_),
    .B(in_data[22]),
    .C(in_ready),
    .D(in_valid),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nand2_1 _358_ (
    .A(_135_),
    .B(_136_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__clkinv_1 _359_ (
    .A(skid_data[23]),
    .Y(_137_)
  );
  sky130_fd_sc_hd__o21bai_1 _360_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_137_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand4_1 _361_ (
    .A(_069_),
    .B(in_data[23]),
    .C(in_ready),
    .D(in_valid),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nand2_1 _362_ (
    .A(_138_),
    .B(_139_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__clkinv_1 _363_ (
    .A(skid_data[24]),
    .Y(_140_)
  );
  sky130_fd_sc_hd__o21bai_1 _364_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nand4_1 _365_ (
    .A(_069_),
    .B(in_data[24]),
    .C(in_ready),
    .D(in_valid),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand2_1 _366_ (
    .A(_141_),
    .B(_142_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _367_ (
    .A(skid_data[25]),
    .Y(_143_)
  );
  sky130_fd_sc_hd__o21bai_1 _368_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand4_1 _369_ (
    .A(_069_),
    .B(in_data[25]),
    .C(in_ready),
    .D(in_valid),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nand2_1 _370_ (
    .A(_144_),
    .B(_145_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__clkinv_1 _371_ (
    .A(skid_data[26]),
    .Y(_146_)
  );
  sky130_fd_sc_hd__o21bai_1 _372_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nand4_1 _373_ (
    .A(_069_),
    .B(in_data[26]),
    .C(in_ready),
    .D(in_valid),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nand2_1 _374_ (
    .A(_147_),
    .B(_148_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__clkinv_1 _375_ (
    .A(skid_data[27]),
    .Y(_149_)
  );
  sky130_fd_sc_hd__o21bai_1 _376_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nand4_1 _377_ (
    .A(_069_),
    .B(in_data[27]),
    .C(in_ready),
    .D(in_valid),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nand2_1 _378_ (
    .A(_150_),
    .B(_151_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _379_ (
    .A(skid_data[28]),
    .Y(_152_)
  );
  sky130_fd_sc_hd__o21bai_1 _380_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_152_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nand4_1 _381_ (
    .A(_069_),
    .B(in_data[28]),
    .C(in_ready),
    .D(in_valid),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nand2_1 _382_ (
    .A(_153_),
    .B(_154_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__clkinv_1 _383_ (
    .A(skid_data[29]),
    .Y(_155_)
  );
  sky130_fd_sc_hd__o21bai_1 _384_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_155_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nand4_1 _385_ (
    .A(_069_),
    .B(in_data[29]),
    .C(in_ready),
    .D(in_valid),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand2_1 _386_ (
    .A(_156_),
    .B(_157_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__clkinv_1 _387_ (
    .A(skid_data[30]),
    .Y(_158_)
  );
  sky130_fd_sc_hd__o21bai_1 _388_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_158_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nand4_1 _389_ (
    .A(_069_),
    .B(in_data[30]),
    .C(in_ready),
    .D(in_valid),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nand2_1 _390_ (
    .A(_159_),
    .B(_160_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__clkinv_1 _391_ (
    .A(skid_data[31]),
    .Y(_161_)
  );
  sky130_fd_sc_hd__o21bai_1 _392_ (
    .A1(out_ready),
    .A2(_067_),
    .B1_N(_161_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand4_1 _393_ (
    .A(_069_),
    .B(in_data[31]),
    .C(in_ready),
    .D(in_valid),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nand2_1 _394_ (
    .A(_162_),
    .B(_163_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__clkinv_1 _395_ (
    .A(out_ready),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand2_1 _396_ (
    .A(_164_),
    .B(out_valid),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nand2_1 _397_ (
    .A(in_ready),
    .B(in_data[0]),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nand2_1 _398_ (
    .A(skid_data[0]),
    .B(skid_valid),
    .Y(_167_)
  );
  sky130_fd_sc_hd__clkinv_1 _399_ (
    .A(out_valid),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nor3_1 _400_ (
    .A(out_data[0]),
    .B(out_ready),
    .C(_168_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__a31oi_1 _401_ (
    .A1(_165_),
    .A2(_166_),
    .A3(_167_),
    .B1(_169_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _402_ (
    .A(in_ready),
    .B(in_data[1]),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nand2_1 _403_ (
    .A(skid_data[1]),
    .B(skid_valid),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nor3_1 _404_ (
    .A(out_data[1]),
    .B(out_ready),
    .C(_168_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a31oi_1 _405_ (
    .A1(_165_),
    .A2(_170_),
    .A3(_171_),
    .B1(_172_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _406_ (
    .A(in_ready),
    .B(in_data[2]),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nand2_1 _407_ (
    .A(skid_data[2]),
    .B(skid_valid),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nor3_1 _408_ (
    .A(out_data[2]),
    .B(out_ready),
    .C(_168_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__a31oi_1 _409_ (
    .A1(_165_),
    .A2(_173_),
    .A3(_174_),
    .B1(_175_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2_1 _410_ (
    .A(in_ready),
    .B(in_data[3]),
    .Y(_176_)
  );
  sky130_fd_sc_hd__nand2_1 _411_ (
    .A(skid_data[3]),
    .B(skid_valid),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nor3_1 _412_ (
    .A(out_data[3]),
    .B(out_ready),
    .C(_168_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__a31oi_1 _413_ (
    .A1(_165_),
    .A2(_176_),
    .A3(_177_),
    .B1(_178_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _414_ (
    .A(in_ready),
    .B(in_data[4]),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nand2_1 _415_ (
    .A(skid_data[4]),
    .B(skid_valid),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nor3_1 _416_ (
    .A(out_data[4]),
    .B(out_ready),
    .C(_168_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__a31oi_1 _417_ (
    .A1(_165_),
    .A2(_179_),
    .A3(_180_),
    .B1(_181_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _418_ (
    .A(in_ready),
    .B(in_data[5]),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nand2_1 _419_ (
    .A(skid_data[5]),
    .B(skid_valid),
    .Y(_183_)
  );
  sky130_fd_sc_hd__nor3_1 _420_ (
    .A(out_data[5]),
    .B(out_ready),
    .C(_168_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__a31oi_1 _421_ (
    .A1(_165_),
    .A2(_182_),
    .A3(_183_),
    .B1(_184_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _422_ (
    .A(in_ready),
    .B(in_data[6]),
    .Y(_185_)
  );
  sky130_fd_sc_hd__nand2_1 _423_ (
    .A(skid_data[6]),
    .B(skid_valid),
    .Y(_186_)
  );
  sky130_fd_sc_hd__nor3_1 _424_ (
    .A(out_data[6]),
    .B(out_ready),
    .C(_168_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__a31oi_1 _425_ (
    .A1(_165_),
    .A2(_185_),
    .A3(_186_),
    .B1(_187_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand2_1 _426_ (
    .A(in_ready),
    .B(in_data[7]),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nand2_1 _427_ (
    .A(skid_data[7]),
    .B(skid_valid),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nor3_1 _428_ (
    .A(out_data[7]),
    .B(out_ready),
    .C(_168_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__a31oi_1 _429_ (
    .A1(_165_),
    .A2(_188_),
    .A3(_189_),
    .B1(_190_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _430_ (
    .A(in_ready),
    .B(in_data[8]),
    .Y(_191_)
  );
  sky130_fd_sc_hd__nand2_1 _431_ (
    .A(skid_data[8]),
    .B(skid_valid),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nor3_1 _432_ (
    .A(out_data[8]),
    .B(out_ready),
    .C(_168_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__a31oi_1 _433_ (
    .A1(_165_),
    .A2(_191_),
    .A3(_192_),
    .B1(_193_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _434_ (
    .A(in_ready),
    .B(in_data[9]),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nand2_1 _435_ (
    .A(skid_data[9]),
    .B(skid_valid),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nor3_1 _436_ (
    .A(out_data[9]),
    .B(out_ready),
    .C(_168_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__a31oi_1 _437_ (
    .A1(_165_),
    .A2(_194_),
    .A3(_195_),
    .B1(_196_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand2_1 _438_ (
    .A(in_ready),
    .B(in_data[10]),
    .Y(_197_)
  );
  sky130_fd_sc_hd__nand2_1 _439_ (
    .A(skid_data[10]),
    .B(skid_valid),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nor3_1 _440_ (
    .A(out_data[10]),
    .B(out_ready),
    .C(_168_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__a31oi_1 _441_ (
    .A1(_165_),
    .A2(_197_),
    .A3(_198_),
    .B1(_199_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand2_1 _442_ (
    .A(in_ready),
    .B(in_data[11]),
    .Y(_200_)
  );
  sky130_fd_sc_hd__nand2_1 _443_ (
    .A(skid_data[11]),
    .B(skid_valid),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nor3_1 _444_ (
    .A(out_data[11]),
    .B(out_ready),
    .C(_168_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__a31oi_1 _445_ (
    .A1(_165_),
    .A2(_200_),
    .A3(_201_),
    .B1(_202_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _446_ (
    .A(in_ready),
    .B(in_data[12]),
    .Y(_203_)
  );
  sky130_fd_sc_hd__nand2_1 _447_ (
    .A(skid_data[12]),
    .B(skid_valid),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nor3_1 _448_ (
    .A(out_data[12]),
    .B(out_ready),
    .C(_168_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__a31oi_1 _449_ (
    .A1(_165_),
    .A2(_203_),
    .A3(_204_),
    .B1(_205_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _450_ (
    .A(in_ready),
    .B(in_data[13]),
    .Y(_206_)
  );
  sky130_fd_sc_hd__nand2_1 _451_ (
    .A(skid_data[13]),
    .B(skid_valid),
    .Y(_207_)
  );
  sky130_fd_sc_hd__nor3_1 _452_ (
    .A(out_data[13]),
    .B(out_ready),
    .C(_168_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__a31oi_1 _453_ (
    .A1(_165_),
    .A2(_206_),
    .A3(_207_),
    .B1(_208_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _454_ (
    .A(in_ready),
    .B(in_data[14]),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nand2_1 _455_ (
    .A(skid_data[14]),
    .B(skid_valid),
    .Y(_210_)
  );
  sky130_fd_sc_hd__nor3_1 _456_ (
    .A(out_data[14]),
    .B(out_ready),
    .C(_168_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__a31oi_1 _457_ (
    .A1(_165_),
    .A2(_209_),
    .A3(_210_),
    .B1(_211_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _458_ (
    .A(in_ready),
    .B(in_data[15]),
    .Y(_212_)
  );
  sky130_fd_sc_hd__nand2_1 _459_ (
    .A(skid_data[15]),
    .B(skid_valid),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nor3_1 _460_ (
    .A(out_data[15]),
    .B(out_ready),
    .C(_168_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__a31oi_1 _461_ (
    .A1(_165_),
    .A2(_212_),
    .A3(_213_),
    .B1(_214_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _462_ (
    .A(in_ready),
    .B(in_data[16]),
    .Y(_215_)
  );
  sky130_fd_sc_hd__nand2_1 _463_ (
    .A(skid_data[16]),
    .B(skid_valid),
    .Y(_216_)
  );
  sky130_fd_sc_hd__nor3_1 _464_ (
    .A(out_data[16]),
    .B(out_ready),
    .C(_168_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__a31oi_1 _465_ (
    .A1(_165_),
    .A2(_215_),
    .A3(_216_),
    .B1(_217_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _466_ (
    .A(in_ready),
    .B(in_data[17]),
    .Y(_218_)
  );
  sky130_fd_sc_hd__nand2_1 _467_ (
    .A(skid_data[17]),
    .B(skid_valid),
    .Y(_219_)
  );
  sky130_fd_sc_hd__nor3_1 _468_ (
    .A(out_data[17]),
    .B(out_ready),
    .C(_168_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__a31oi_1 _469_ (
    .A1(_165_),
    .A2(_218_),
    .A3(_219_),
    .B1(_220_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _470_ (
    .A(in_ready),
    .B(in_data[18]),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nand2_1 _471_ (
    .A(skid_data[18]),
    .B(skid_valid),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nor3_1 _472_ (
    .A(out_data[18]),
    .B(out_ready),
    .C(_168_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__a31oi_1 _473_ (
    .A1(_165_),
    .A2(_221_),
    .A3(_222_),
    .B1(_223_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand2_1 _474_ (
    .A(in_ready),
    .B(in_data[19]),
    .Y(_224_)
  );
  sky130_fd_sc_hd__nand2_1 _475_ (
    .A(skid_data[19]),
    .B(skid_valid),
    .Y(_225_)
  );
  sky130_fd_sc_hd__nor3_1 _476_ (
    .A(out_data[19]),
    .B(out_ready),
    .C(_168_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__a31oi_1 _477_ (
    .A1(_165_),
    .A2(_224_),
    .A3(_225_),
    .B1(_226_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand2_1 _478_ (
    .A(in_ready),
    .B(in_data[20]),
    .Y(_227_)
  );
  sky130_fd_sc_hd__nand2_1 _479_ (
    .A(skid_data[20]),
    .B(skid_valid),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nor3_1 _480_ (
    .A(out_data[20]),
    .B(out_ready),
    .C(_168_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__a31oi_1 _481_ (
    .A1(_165_),
    .A2(_227_),
    .A3(_228_),
    .B1(_229_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _482_ (
    .A(in_ready),
    .B(in_data[21]),
    .Y(_230_)
  );
  sky130_fd_sc_hd__nand2_1 _483_ (
    .A(skid_data[21]),
    .B(skid_valid),
    .Y(_231_)
  );
  sky130_fd_sc_hd__nor3_1 _484_ (
    .A(out_data[21]),
    .B(out_ready),
    .C(_168_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__a31oi_1 _485_ (
    .A1(_165_),
    .A2(_230_),
    .A3(_231_),
    .B1(_232_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _486_ (
    .A(in_ready),
    .B(in_data[22]),
    .Y(_233_)
  );
  sky130_fd_sc_hd__nand2_1 _487_ (
    .A(skid_data[22]),
    .B(skid_valid),
    .Y(_234_)
  );
  sky130_fd_sc_hd__nor3_1 _488_ (
    .A(out_data[22]),
    .B(out_ready),
    .C(_168_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__a31oi_1 _489_ (
    .A1(_165_),
    .A2(_233_),
    .A3(_234_),
    .B1(_235_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _490_ (
    .A(in_ready),
    .B(in_data[23]),
    .Y(_236_)
  );
  sky130_fd_sc_hd__nand2_1 _491_ (
    .A(skid_data[23]),
    .B(skid_valid),
    .Y(_237_)
  );
  sky130_fd_sc_hd__nor3_1 _492_ (
    .A(out_data[23]),
    .B(out_ready),
    .C(_168_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__a31oi_1 _493_ (
    .A1(_165_),
    .A2(_236_),
    .A3(_237_),
    .B1(_238_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _494_ (
    .A(in_ready),
    .B(in_data[24]),
    .Y(_239_)
  );
  sky130_fd_sc_hd__nand2_1 _495_ (
    .A(skid_data[24]),
    .B(skid_valid),
    .Y(_240_)
  );
  sky130_fd_sc_hd__nor3_1 _496_ (
    .A(out_data[24]),
    .B(out_ready),
    .C(_168_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__a31oi_1 _497_ (
    .A1(_165_),
    .A2(_239_),
    .A3(_240_),
    .B1(_241_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _498_ (
    .A(in_ready),
    .B(in_data[25]),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nand2_1 _499_ (
    .A(skid_data[25]),
    .B(skid_valid),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nor3_1 _500_ (
    .A(out_data[25]),
    .B(out_ready),
    .C(_168_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__a31oi_1 _501_ (
    .A1(_165_),
    .A2(_242_),
    .A3(_243_),
    .B1(_244_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _502_ (
    .A(in_ready),
    .B(in_data[26]),
    .Y(_245_)
  );
  sky130_fd_sc_hd__nand2_1 _503_ (
    .A(skid_data[26]),
    .B(skid_valid),
    .Y(_246_)
  );
  sky130_fd_sc_hd__nor3_1 _504_ (
    .A(out_data[26]),
    .B(out_ready),
    .C(_168_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__a31oi_1 _505_ (
    .A1(_165_),
    .A2(_245_),
    .A3(_246_),
    .B1(_247_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _506_ (
    .A(in_ready),
    .B(in_data[27]),
    .Y(_248_)
  );
  sky130_fd_sc_hd__nand2_1 _507_ (
    .A(skid_data[27]),
    .B(skid_valid),
    .Y(_249_)
  );
  sky130_fd_sc_hd__nor3_1 _508_ (
    .A(out_data[27]),
    .B(out_ready),
    .C(_168_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__a31oi_1 _509_ (
    .A1(_165_),
    .A2(_248_),
    .A3(_249_),
    .B1(_250_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _510_ (
    .A(in_ready),
    .B(in_data[28]),
    .Y(_251_)
  );
  sky130_fd_sc_hd__nand2_1 _511_ (
    .A(skid_data[28]),
    .B(skid_valid),
    .Y(_252_)
  );
  sky130_fd_sc_hd__nor3_1 _512_ (
    .A(out_data[28]),
    .B(out_ready),
    .C(_168_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__a31oi_1 _513_ (
    .A1(_165_),
    .A2(_251_),
    .A3(_252_),
    .B1(_253_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _514_ (
    .A(in_ready),
    .B(in_data[29]),
    .Y(_254_)
  );
  sky130_fd_sc_hd__nand2_1 _515_ (
    .A(skid_data[29]),
    .B(skid_valid),
    .Y(_255_)
  );
  sky130_fd_sc_hd__nor3_1 _516_ (
    .A(out_data[29]),
    .B(out_ready),
    .C(_168_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__a31oi_1 _517_ (
    .A1(_165_),
    .A2(_254_),
    .A3(_255_),
    .B1(_256_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _518_ (
    .A(in_ready),
    .B(in_data[30]),
    .Y(_257_)
  );
  sky130_fd_sc_hd__nand2_1 _519_ (
    .A(skid_data[30]),
    .B(skid_valid),
    .Y(_258_)
  );
  sky130_fd_sc_hd__nor3_1 _520_ (
    .A(out_data[30]),
    .B(out_ready),
    .C(_168_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__a31oi_1 _521_ (
    .A1(_165_),
    .A2(_257_),
    .A3(_258_),
    .B1(_259_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _522_ (
    .A(in_ready),
    .B(in_data[31]),
    .Y(_260_)
  );
  sky130_fd_sc_hd__nand2_1 _523_ (
    .A(skid_data[31]),
    .B(skid_valid),
    .Y(_261_)
  );
  sky130_fd_sc_hd__nor3_1 _524_ (
    .A(out_data[31]),
    .B(out_ready),
    .C(_168_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__a31oi_1 _525_ (
    .A1(_165_),
    .A2(_260_),
    .A3(_261_),
    .B1(_262_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__clkinv_1 _526_ (
    .A(in_valid),
    .Y(_263_)
  );
  sky130_fd_sc_hd__nand3_1 _527_ (
    .A(_165_),
    .B(in_ready),
    .C(_263_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__a21oi_1 _528_ (
    .A1(in_ready),
    .A2(_263_),
    .B1(_165_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__dfrtp_1 _529_ (
    .CLK(clk),
    .D(_000_),
    .Q(skid_data[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _530_ (
    .CLK(clk),
    .D(_001_),
    .Q(skid_data[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _531_ (
    .CLK(clk),
    .D(_002_),
    .Q(skid_data[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _532_ (
    .CLK(clk),
    .D(_003_),
    .Q(skid_data[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _533_ (
    .CLK(clk),
    .D(_004_),
    .Q(skid_data[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _534_ (
    .CLK(clk),
    .D(_005_),
    .Q(skid_data[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _535_ (
    .CLK(clk),
    .D(_006_),
    .Q(skid_data[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _536_ (
    .CLK(clk),
    .D(_007_),
    .Q(skid_data[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _537_ (
    .CLK(clk),
    .D(_008_),
    .Q(skid_data[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _538_ (
    .CLK(clk),
    .D(_009_),
    .Q(skid_data[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _539_ (
    .CLK(clk),
    .D(_010_),
    .Q(skid_data[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _540_ (
    .CLK(clk),
    .D(_011_),
    .Q(skid_data[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _541_ (
    .CLK(clk),
    .D(_012_),
    .Q(skid_data[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _542_ (
    .CLK(clk),
    .D(_013_),
    .Q(skid_data[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _543_ (
    .CLK(clk),
    .D(_014_),
    .Q(skid_data[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _544_ (
    .CLK(clk),
    .D(_015_),
    .Q(skid_data[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _545_ (
    .CLK(clk),
    .D(_016_),
    .Q(skid_data[16]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _546_ (
    .CLK(clk),
    .D(_017_),
    .Q(skid_data[17]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _547_ (
    .CLK(clk),
    .D(_018_),
    .Q(skid_data[18]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _548_ (
    .CLK(clk),
    .D(_019_),
    .Q(skid_data[19]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _549_ (
    .CLK(clk),
    .D(_020_),
    .Q(skid_data[20]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _550_ (
    .CLK(clk),
    .D(_021_),
    .Q(skid_data[21]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _551_ (
    .CLK(clk),
    .D(_022_),
    .Q(skid_data[22]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _552_ (
    .CLK(clk),
    .D(_023_),
    .Q(skid_data[23]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _553_ (
    .CLK(clk),
    .D(_024_),
    .Q(skid_data[24]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _554_ (
    .CLK(clk),
    .D(_025_),
    .Q(skid_data[25]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _555_ (
    .CLK(clk),
    .D(_026_),
    .Q(skid_data[26]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _556_ (
    .CLK(clk),
    .D(_027_),
    .Q(skid_data[27]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _557_ (
    .CLK(clk),
    .D(_028_),
    .Q(skid_data[28]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _558_ (
    .CLK(clk),
    .D(_029_),
    .Q(skid_data[29]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _559_ (
    .CLK(clk),
    .D(_030_),
    .Q(skid_data[30]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _560_ (
    .CLK(clk),
    .D(_031_),
    .Q(skid_data[31]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _561_ (
    .CLK(clk),
    .D(_032_),
    .Q(out_data[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _562_ (
    .CLK(clk),
    .D(_033_),
    .Q(out_data[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _563_ (
    .CLK(clk),
    .D(_034_),
    .Q(out_data[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _564_ (
    .CLK(clk),
    .D(_035_),
    .Q(out_data[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _565_ (
    .CLK(clk),
    .D(_036_),
    .Q(out_data[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _566_ (
    .CLK(clk),
    .D(_037_),
    .Q(out_data[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _567_ (
    .CLK(clk),
    .D(_038_),
    .Q(out_data[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _568_ (
    .CLK(clk),
    .D(_039_),
    .Q(out_data[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _569_ (
    .CLK(clk),
    .D(_040_),
    .Q(out_data[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _570_ (
    .CLK(clk),
    .D(_041_),
    .Q(out_data[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _571_ (
    .CLK(clk),
    .D(_042_),
    .Q(out_data[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _572_ (
    .CLK(clk),
    .D(_043_),
    .Q(out_data[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _573_ (
    .CLK(clk),
    .D(_044_),
    .Q(out_data[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _574_ (
    .CLK(clk),
    .D(_045_),
    .Q(out_data[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _575_ (
    .CLK(clk),
    .D(_046_),
    .Q(out_data[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _576_ (
    .CLK(clk),
    .D(_047_),
    .Q(out_data[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _577_ (
    .CLK(clk),
    .D(_048_),
    .Q(out_data[16]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _578_ (
    .CLK(clk),
    .D(_049_),
    .Q(out_data[17]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _579_ (
    .CLK(clk),
    .D(_050_),
    .Q(out_data[18]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _580_ (
    .CLK(clk),
    .D(_051_),
    .Q(out_data[19]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _581_ (
    .CLK(clk),
    .D(_052_),
    .Q(out_data[20]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _582_ (
    .CLK(clk),
    .D(_053_),
    .Q(out_data[21]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _583_ (
    .CLK(clk),
    .D(_054_),
    .Q(out_data[22]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _584_ (
    .CLK(clk),
    .D(_055_),
    .Q(out_data[23]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _585_ (
    .CLK(clk),
    .D(_056_),
    .Q(out_data[24]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _586_ (
    .CLK(clk),
    .D(_057_),
    .Q(out_data[25]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _587_ (
    .CLK(clk),
    .D(_058_),
    .Q(out_data[26]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _588_ (
    .CLK(clk),
    .D(_059_),
    .Q(out_data[27]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _589_ (
    .CLK(clk),
    .D(_060_),
    .Q(out_data[28]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _590_ (
    .CLK(clk),
    .D(_061_),
    .Q(out_data[29]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _591_ (
    .CLK(clk),
    .D(_062_),
    .Q(out_data[30]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _592_ (
    .CLK(clk),
    .D(_063_),
    .Q(out_data[31]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _593_ (
    .CLK(clk),
    .D(_064_),
    .Q(out_valid),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _594_ (
    .CLK(clk),
    .D(_065_),
    .Q(skid_valid),
    .RESET_B(rst_n)
  );
endmodule
