/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module dma_engine(clk, rst_n, host_wr_valid, host_wr_addr, host_wr_data, host_wr_ready, host_rd_req, host_rd_addr, host_rd_data, host_rd_valid, sram_req, sram_we, sram_addr, sram_wdata, sram_rdata, sram_rvalid);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  input clk;
  wire clk;
  input [15:0] host_rd_addr;
  wire [15:0] host_rd_addr;
  output [31:0] host_rd_data;
  wire [31:0] host_rd_data;
  input host_rd_req;
  wire host_rd_req;
  output host_rd_valid;
  wire host_rd_valid;
  input [15:0] host_wr_addr;
  wire [15:0] host_wr_addr;
  input [31:0] host_wr_data;
  wire [31:0] host_wr_data;
  output host_wr_ready;
  wire host_wr_ready;
  input host_wr_valid;
  wire host_wr_valid;
  input rst_n;
  wire rst_n;
  output [15:0] sram_addr;
  wire [15:0] sram_addr;
  input [31:0] sram_rdata;
  wire [31:0] sram_rdata;
  output sram_req;
  wire sram_req;
  input sram_rvalid;
  wire sram_rvalid;
  output [31:0] sram_wdata;
  wire [31:0] sram_wdata;
  output sram_we;
  wire sram_we;
  sky130_fd_sc_hd__clkinv_1 _163_ (
    .A(host_wr_valid),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _164_ (
    .A(_049_),
    .B(sram_wdata[0]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand2_1 _165_ (
    .A(host_wr_data[0]),
    .B(host_wr_valid),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand2_1 _166_ (
    .A(_050_),
    .B(_051_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _167_ (
    .A(_049_),
    .B(sram_wdata[1]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _168_ (
    .A(host_wr_valid),
    .B(host_wr_data[1]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _169_ (
    .A(_052_),
    .B(_053_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _170_ (
    .A(_049_),
    .B(sram_wdata[2]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _171_ (
    .A(host_wr_valid),
    .B(host_wr_data[2]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _172_ (
    .A(_054_),
    .B(_055_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _173_ (
    .A(_049_),
    .B(sram_wdata[3]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _174_ (
    .A(host_wr_valid),
    .B(host_wr_data[3]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _175_ (
    .A(_056_),
    .B(_057_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _176_ (
    .A(_049_),
    .B(sram_wdata[4]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _177_ (
    .A(host_wr_valid),
    .B(host_wr_data[4]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _178_ (
    .A(_058_),
    .B(_059_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _179_ (
    .A(_049_),
    .B(sram_wdata[5]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _180_ (
    .A(host_wr_valid),
    .B(host_wr_data[5]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _181_ (
    .A(_060_),
    .B(_061_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _182_ (
    .A(_049_),
    .B(sram_wdata[6]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _183_ (
    .A(host_wr_valid),
    .B(host_wr_data[6]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _184_ (
    .A(_062_),
    .B(_063_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _185_ (
    .A(_049_),
    .B(sram_wdata[7]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _186_ (
    .A(host_wr_valid),
    .B(host_wr_data[7]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _187_ (
    .A(_064_),
    .B(_065_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _188_ (
    .A(_049_),
    .B(sram_wdata[8]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _189_ (
    .A(host_wr_valid),
    .B(host_wr_data[8]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _190_ (
    .A(_066_),
    .B(_067_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _191_ (
    .A(_049_),
    .B(sram_wdata[9]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _192_ (
    .A(host_wr_valid),
    .B(host_wr_data[9]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _193_ (
    .A(_068_),
    .B(_069_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _194_ (
    .A(_049_),
    .B(sram_wdata[10]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _195_ (
    .A(host_wr_valid),
    .B(host_wr_data[10]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _196_ (
    .A(_070_),
    .B(_071_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _197_ (
    .A(_049_),
    .B(sram_wdata[11]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _198_ (
    .A(host_wr_valid),
    .B(host_wr_data[11]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(_072_),
    .B(_073_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _200_ (
    .A(_049_),
    .B(sram_wdata[12]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand2_1 _201_ (
    .A(host_wr_valid),
    .B(host_wr_data[12]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand2_1 _202_ (
    .A(_074_),
    .B(_075_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _203_ (
    .A(_049_),
    .B(sram_wdata[13]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _204_ (
    .A(host_wr_valid),
    .B(host_wr_data[13]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand2_1 _205_ (
    .A(_076_),
    .B(_077_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _206_ (
    .A(_049_),
    .B(sram_wdata[14]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _207_ (
    .A(host_wr_valid),
    .B(host_wr_data[14]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2_1 _208_ (
    .A(_078_),
    .B(_079_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _209_ (
    .A(_049_),
    .B(sram_wdata[15]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand2_1 _210_ (
    .A(host_wr_valid),
    .B(host_wr_data[15]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand2_1 _211_ (
    .A(_080_),
    .B(_081_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _212_ (
    .A(_049_),
    .B(sram_wdata[16]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand2_1 _213_ (
    .A(host_wr_valid),
    .B(host_wr_data[16]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2_1 _214_ (
    .A(_082_),
    .B(_083_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _215_ (
    .A(_049_),
    .B(sram_wdata[17]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2_1 _216_ (
    .A(host_wr_valid),
    .B(host_wr_data[17]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _217_ (
    .A(_084_),
    .B(_085_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _218_ (
    .A(_049_),
    .B(sram_wdata[18]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand2_1 _219_ (
    .A(host_wr_valid),
    .B(host_wr_data[18]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand2_1 _220_ (
    .A(_086_),
    .B(_087_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _221_ (
    .A(_049_),
    .B(sram_wdata[19]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _222_ (
    .A(host_wr_valid),
    .B(host_wr_data[19]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand2_1 _223_ (
    .A(_088_),
    .B(_089_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _224_ (
    .A(_049_),
    .B(sram_wdata[20]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand2_1 _225_ (
    .A(host_wr_valid),
    .B(host_wr_data[20]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand2_1 _226_ (
    .A(_090_),
    .B(_091_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _227_ (
    .A(_049_),
    .B(sram_wdata[21]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _228_ (
    .A(host_wr_valid),
    .B(host_wr_data[21]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2_1 _229_ (
    .A(_092_),
    .B(_093_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _230_ (
    .A(_049_),
    .B(sram_wdata[22]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand2_1 _231_ (
    .A(host_wr_valid),
    .B(host_wr_data[22]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand2_1 _232_ (
    .A(_094_),
    .B(_095_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(_049_),
    .B(sram_wdata[23]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand2_1 _234_ (
    .A(host_wr_valid),
    .B(host_wr_data[23]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2_1 _235_ (
    .A(_096_),
    .B(_097_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(_049_),
    .B(sram_wdata[24]),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _237_ (
    .A(host_wr_valid),
    .B(host_wr_data[24]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _238_ (
    .A(_098_),
    .B(_099_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(_049_),
    .B(sram_wdata[25]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _240_ (
    .A(host_wr_valid),
    .B(host_wr_data[25]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand2_1 _241_ (
    .A(_100_),
    .B(_101_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _242_ (
    .A(_049_),
    .B(sram_wdata[26]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand2_1 _243_ (
    .A(host_wr_valid),
    .B(host_wr_data[26]),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _244_ (
    .A(_102_),
    .B(_103_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _245_ (
    .A(_049_),
    .B(sram_wdata[27]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand2_1 _246_ (
    .A(host_wr_valid),
    .B(host_wr_data[27]),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _247_ (
    .A(_104_),
    .B(_105_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _248_ (
    .A(_049_),
    .B(sram_wdata[28]),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _249_ (
    .A(host_wr_valid),
    .B(host_wr_data[28]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _250_ (
    .A(_106_),
    .B(_107_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _251_ (
    .A(_049_),
    .B(sram_wdata[29]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nand2_1 _252_ (
    .A(host_wr_valid),
    .B(host_wr_data[29]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _253_ (
    .A(_108_),
    .B(_109_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _254_ (
    .A(_049_),
    .B(sram_wdata[30]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nand2_1 _255_ (
    .A(host_wr_valid),
    .B(host_wr_data[30]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nand2_1 _256_ (
    .A(_110_),
    .B(_111_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _257_ (
    .A(_049_),
    .B(sram_wdata[31]),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand2_1 _258_ (
    .A(host_wr_valid),
    .B(host_wr_data[31]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _259_ (
    .A(_112_),
    .B(_113_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__clkinv_1 _260_ (
    .A(host_rd_req),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nand3_1 _261_ (
    .A(_049_),
    .B(_114_),
    .C(sram_addr[0]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nand2_1 _262_ (
    .A(host_wr_valid),
    .B(host_wr_addr[0]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nand3b_1 _263_ (
    .A_N(host_wr_valid),
    .B(host_rd_req),
    .C(host_rd_addr[0]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand3_1 _264_ (
    .A(_115_),
    .B(_116_),
    .C(_117_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand3_1 _265_ (
    .A(_049_),
    .B(_114_),
    .C(sram_addr[1]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nand2_1 _266_ (
    .A(host_wr_valid),
    .B(host_wr_addr[1]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand3b_1 _267_ (
    .A_N(host_wr_valid),
    .B(host_rd_req),
    .C(host_rd_addr[1]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand3_1 _268_ (
    .A(_118_),
    .B(_119_),
    .C(_120_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand3_1 _269_ (
    .A(_049_),
    .B(_114_),
    .C(sram_addr[2]),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(host_wr_valid),
    .B(host_wr_addr[2]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nand3b_1 _271_ (
    .A_N(host_wr_valid),
    .B(host_rd_req),
    .C(host_rd_addr[2]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand3_1 _272_ (
    .A(_121_),
    .B(_122_),
    .C(_123_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand3_1 _273_ (
    .A(_049_),
    .B(_114_),
    .C(sram_addr[3]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nand2_1 _274_ (
    .A(host_wr_valid),
    .B(host_wr_addr[3]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand3b_1 _275_ (
    .A_N(host_wr_valid),
    .B(host_rd_req),
    .C(host_rd_addr[3]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand3_1 _276_ (
    .A(_124_),
    .B(_125_),
    .C(_126_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand3_1 _277_ (
    .A(_049_),
    .B(_114_),
    .C(sram_addr[4]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nand2_1 _278_ (
    .A(host_wr_valid),
    .B(host_wr_addr[4]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand3b_1 _279_ (
    .A_N(host_wr_valid),
    .B(host_rd_req),
    .C(host_rd_addr[4]),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand3_1 _280_ (
    .A(_127_),
    .B(_128_),
    .C(_129_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand3_1 _281_ (
    .A(_049_),
    .B(_114_),
    .C(sram_addr[5]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand2_1 _282_ (
    .A(host_wr_valid),
    .B(host_wr_addr[5]),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand3b_1 _283_ (
    .A_N(host_wr_valid),
    .B(host_rd_req),
    .C(host_rd_addr[5]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand3_1 _284_ (
    .A(_130_),
    .B(_131_),
    .C(_132_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand3_1 _285_ (
    .A(_049_),
    .B(_114_),
    .C(sram_addr[6]),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nand2_1 _286_ (
    .A(host_wr_valid),
    .B(host_wr_addr[6]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nand3b_1 _287_ (
    .A_N(host_wr_valid),
    .B(host_rd_req),
    .C(host_rd_addr[6]),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nand3_1 _288_ (
    .A(_133_),
    .B(_134_),
    .C(_135_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand3_1 _289_ (
    .A(_049_),
    .B(_114_),
    .C(sram_addr[7]),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nand2_1 _290_ (
    .A(host_wr_valid),
    .B(host_wr_addr[7]),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nand3b_1 _291_ (
    .A_N(host_wr_valid),
    .B(host_rd_req),
    .C(host_rd_addr[7]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand3_1 _292_ (
    .A(_136_),
    .B(_137_),
    .C(_138_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand3_1 _293_ (
    .A(_049_),
    .B(_114_),
    .C(sram_addr[8]),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nand2_1 _294_ (
    .A(host_wr_valid),
    .B(host_wr_addr[8]),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nand3b_1 _295_ (
    .A_N(host_wr_valid),
    .B(host_rd_req),
    .C(host_rd_addr[8]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nand3_1 _296_ (
    .A(_139_),
    .B(_140_),
    .C(_141_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand3_1 _297_ (
    .A(_049_),
    .B(_114_),
    .C(sram_addr[9]),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand2_1 _298_ (
    .A(host_wr_valid),
    .B(host_wr_addr[9]),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nand3b_1 _299_ (
    .A_N(host_wr_valid),
    .B(host_rd_req),
    .C(host_rd_addr[9]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand3_1 _300_ (
    .A(_142_),
    .B(_143_),
    .C(_144_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand3_1 _301_ (
    .A(_049_),
    .B(_114_),
    .C(sram_addr[10]),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nand2_1 _302_ (
    .A(host_wr_valid),
    .B(host_wr_addr[10]),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand3b_1 _303_ (
    .A_N(host_wr_valid),
    .B(host_rd_req),
    .C(host_rd_addr[10]),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nand3_1 _304_ (
    .A(_145_),
    .B(_146_),
    .C(_147_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand3_1 _305_ (
    .A(_049_),
    .B(_114_),
    .C(sram_addr[11]),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nand2_1 _306_ (
    .A(host_wr_valid),
    .B(host_wr_addr[11]),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand3b_1 _307_ (
    .A_N(host_wr_valid),
    .B(host_rd_req),
    .C(host_rd_addr[11]),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nand3_1 _308_ (
    .A(_148_),
    .B(_149_),
    .C(_150_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand3_1 _309_ (
    .A(_049_),
    .B(_114_),
    .C(sram_addr[12]),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nand2_1 _310_ (
    .A(host_wr_valid),
    .B(host_wr_addr[12]),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nand3b_1 _311_ (
    .A_N(host_wr_valid),
    .B(host_rd_req),
    .C(host_rd_addr[12]),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nand3_1 _312_ (
    .A(_151_),
    .B(_152_),
    .C(_153_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand3_1 _313_ (
    .A(_049_),
    .B(_114_),
    .C(sram_addr[13]),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nand2_1 _314_ (
    .A(host_wr_valid),
    .B(host_wr_addr[13]),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nand3b_1 _315_ (
    .A_N(host_wr_valid),
    .B(host_rd_req),
    .C(host_rd_addr[13]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nand3_1 _316_ (
    .A(_154_),
    .B(_155_),
    .C(_156_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand3_1 _317_ (
    .A(_049_),
    .B(_114_),
    .C(sram_addr[14]),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand2_1 _318_ (
    .A(host_wr_valid),
    .B(host_wr_addr[14]),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nand3b_1 _319_ (
    .A_N(host_wr_valid),
    .B(host_rd_req),
    .C(host_rd_addr[14]),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nand3_1 _320_ (
    .A(_157_),
    .B(_158_),
    .C(_159_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand3_1 _321_ (
    .A(_049_),
    .B(_114_),
    .C(sram_addr[15]),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nand2_1 _322_ (
    .A(host_wr_valid),
    .B(host_wr_addr[15]),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nand3b_1 _323_ (
    .A_N(host_wr_valid),
    .B(host_rd_req),
    .C(host_rd_addr[15]),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand3_1 _324_ (
    .A(_160_),
    .B(_161_),
    .C(_162_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _325_ (
    .A(_049_),
    .B(_114_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__dfrtp_1 _326_ (
    .CLK(clk),
    .D(_001_),
    .Q(sram_wdata[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _327_ (
    .CLK(clk),
    .D(_002_),
    .Q(sram_wdata[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _328_ (
    .CLK(clk),
    .D(_003_),
    .Q(sram_wdata[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _329_ (
    .CLK(clk),
    .D(_004_),
    .Q(sram_wdata[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _330_ (
    .CLK(clk),
    .D(_005_),
    .Q(sram_wdata[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _331_ (
    .CLK(clk),
    .D(_006_),
    .Q(sram_wdata[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _332_ (
    .CLK(clk),
    .D(_007_),
    .Q(sram_wdata[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _333_ (
    .CLK(clk),
    .D(_008_),
    .Q(sram_wdata[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _334_ (
    .CLK(clk),
    .D(_009_),
    .Q(sram_wdata[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _335_ (
    .CLK(clk),
    .D(_010_),
    .Q(sram_wdata[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _336_ (
    .CLK(clk),
    .D(_011_),
    .Q(sram_wdata[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _337_ (
    .CLK(clk),
    .D(_012_),
    .Q(sram_wdata[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _338_ (
    .CLK(clk),
    .D(_013_),
    .Q(sram_wdata[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _339_ (
    .CLK(clk),
    .D(_014_),
    .Q(sram_wdata[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _340_ (
    .CLK(clk),
    .D(_015_),
    .Q(sram_wdata[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _341_ (
    .CLK(clk),
    .D(_016_),
    .Q(sram_wdata[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _342_ (
    .CLK(clk),
    .D(_017_),
    .Q(sram_wdata[16]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _343_ (
    .CLK(clk),
    .D(_018_),
    .Q(sram_wdata[17]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _344_ (
    .CLK(clk),
    .D(_019_),
    .Q(sram_wdata[18]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _345_ (
    .CLK(clk),
    .D(_020_),
    .Q(sram_wdata[19]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _346_ (
    .CLK(clk),
    .D(_021_),
    .Q(sram_wdata[20]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _347_ (
    .CLK(clk),
    .D(_022_),
    .Q(sram_wdata[21]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _348_ (
    .CLK(clk),
    .D(_023_),
    .Q(sram_wdata[22]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _349_ (
    .CLK(clk),
    .D(_024_),
    .Q(sram_wdata[23]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _350_ (
    .CLK(clk),
    .D(_025_),
    .Q(sram_wdata[24]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _351_ (
    .CLK(clk),
    .D(_026_),
    .Q(sram_wdata[25]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _352_ (
    .CLK(clk),
    .D(_027_),
    .Q(sram_wdata[26]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _353_ (
    .CLK(clk),
    .D(_028_),
    .Q(sram_wdata[27]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _354_ (
    .CLK(clk),
    .D(_029_),
    .Q(sram_wdata[28]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _355_ (
    .CLK(clk),
    .D(_030_),
    .Q(sram_wdata[29]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _356_ (
    .CLK(clk),
    .D(_031_),
    .Q(sram_wdata[30]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _357_ (
    .CLK(clk),
    .D(_032_),
    .Q(sram_wdata[31]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _358_ (
    .CLK(clk),
    .D(host_wr_valid),
    .Q(sram_we),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _359_ (
    .CLK(clk),
    .D(_000_),
    .Q(sram_req),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _360_ (
    .CLK(clk),
    .D(_033_),
    .Q(sram_addr[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _361_ (
    .CLK(clk),
    .D(_034_),
    .Q(sram_addr[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _362_ (
    .CLK(clk),
    .D(_035_),
    .Q(sram_addr[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _363_ (
    .CLK(clk),
    .D(_036_),
    .Q(sram_addr[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _364_ (
    .CLK(clk),
    .D(_037_),
    .Q(sram_addr[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _365_ (
    .CLK(clk),
    .D(_038_),
    .Q(sram_addr[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _366_ (
    .CLK(clk),
    .D(_039_),
    .Q(sram_addr[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _367_ (
    .CLK(clk),
    .D(_040_),
    .Q(sram_addr[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _368_ (
    .CLK(clk),
    .D(_041_),
    .Q(sram_addr[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _369_ (
    .CLK(clk),
    .D(_042_),
    .Q(sram_addr[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _370_ (
    .CLK(clk),
    .D(_043_),
    .Q(sram_addr[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _371_ (
    .CLK(clk),
    .D(_044_),
    .Q(sram_addr[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _372_ (
    .CLK(clk),
    .D(_045_),
    .Q(sram_addr[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _373_ (
    .CLK(clk),
    .D(_046_),
    .Q(sram_addr[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _374_ (
    .CLK(clk),
    .D(_047_),
    .Q(sram_addr[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _375_ (
    .CLK(clk),
    .D(_048_),
    .Q(sram_addr[15]),
    .RESET_B(rst_n)
  );
  assign host_rd_data = sram_rdata;
  assign host_rd_valid = sram_rvalid;
  assign host_wr_ready = 1'h1;
endmodule
